In [3]:
import pandas as pd

In [4]:
# carregando o dataset do formato "csv" corretamente usando o separador ";"
df = pd.read_csv('./datasets/GasPricesinBrazil_2004-2019.csv', sep = ';')

In [5]:
df

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,...,3.690,0.818,0.018,2.756,0,2.756,2.756,0,6,2019
106819,106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,...,3.789,0.95,0.038,2.451,0.402,1.9842,2.8661,0.164,6,2019
106820,106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,...,3.499,0.914,0.065,1.998,0,1.9981,1.9981,0,6,2019
106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,3.490,0.646,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019
106822,106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,0.005,...,3.699,1.179,0.001,2.518,0,2.5175,2.5175,0,6,2019

In [6]:
# carrega o numero de linhas denominada(se colocar nada carrega somente 5)
df.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004

In [7]:
# carrega as 10 primeiras linhas do dataset
df.head(10)

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004
5,5,2004-05-09,2004-05-15,NORDESTE,BAHIA,ETANOL HIDRATADO,408,R$/l,1.383,0.132,...,2.050,0.426,0.095,0.957,0.128,0.5686,1.35,0.134,5,2004
6,6,2004-05-09,2004-05-15,NORDESTE,CEARA,ETANOL HIDRATADO,278,R$/l,1.453,0.218,...,1.950,0.353,0.150,1.1,0.068,0.7332,1.294,0.062,5,2004
7,7,2004-05-09,2004-05-15,NORDESTE,MARANHAO,ETANOL HIDRATADO,105,R$/l,1.631,0.158,...,2.000,0.515,0.097,1.116,0.091,0.9923,1.36183,0.082,5,2004
8,8,2004-05-09,2004-05-15,NORDESTE,PARAIBA,ETANOL HIDRATADO,125,R$/l,1.284,0.130,...,1.699,0.353,0.101,0.931,0.072,0.7577,1.2972,0.077,5,2004
9,9,2004-05-09,2004-05-15,NORDESTE,PERNAMBUCO,ETANOL HIDRATADO,423,R$/l,1.224,0.141,...,1.700,0.277,0.115,0.947,0.091,0.5643,1.3541,0.096,5,2004

In [8]:
# mostra as informções do dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106823 entries, 0 to 106822
Data columns (total 21 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Unnamed: 0                     106823 non-null  int64
 1   DATA INICIAL                   106823 non-null  object
 2   DATA FINAL                     106823 non-null  object
 3   REGIÃO                         106823 non-null  object
 4   ESTADO                         106823 non-null  object
 5   PRODUTO                        106823 non-null  object
 6   NÚMERO DE POSTOS PESQUISADOS   106823 non-null  int64
 7   UNIDADE DE MEDIDA              106823 non-null  object
 8   PREÇO MÉDIO REVENDA            106823 non-null  float64
 9   DESVIO PADRÃO REVENDA          106823 non-null  float64
 10  PREÇO MÍNIMO REVENDA           106823 non-null  float64
 11  PREÇO MÁXIMO REVENDA           106823 non-null  float64
 12  MARGEM MÉDIA REVENDA           106823 non-null  object
 13  COEF DE VARIAÇÃO REVENDA       106823 non-null  float64
 14  PREÇO MÉDIO DISTRIBUIÇÃO       106823 non-null  object
 15  DESVIO PADRÃO DISTRIBUIÇÃO     106823 non-null  object
 16  PREÇO MÍNIMO DISTRIBUIÇÃO      106823 non-null  object
 17  PREÇO MÁXIMO DISTRIBUIÇÃO      106823 non-null  object
 18  COEF DE VARIAÇÃO DISTRIBUIÇÃO  106823 non-null  object
 19  MÊS                            106823 non-null  int64
 20  ANO                            106823 non-null  int64
dtypes: float64(5), int64(4), object(12)
memory usage: 17.1+ MB

In [9]:
# mostra o tipo,como mostrado este é um DataFrame
type(df)

pandas.core.frame.DataFrame

In [10]:
# mostra o corpo do dataframe, linhas x colunas
df.shape

(106823, 21)

In [11]:
print(f"O DataFrame possui {df.shape[0]} linhas!")

O DataFrame possui 106823 linhas!

In [12]:
print(f'O DataFrame possui {df.shape[1]} colunas!')

O DataFrame possui 21 colunas!

In [13]:
alunos = pd.DataFrame({
    'nome': ['Rodrigo', 'Ricardo', 'Barbara'],
    'idade': [20, 23, 21],
    'curso': ['Ciência da Computação', 'Arquitetura', 'Design']
})

In [14]:
alunos

      nome  idade                  curso
0  Rodrigo     20  Ciência da Computação
1  Ricardo     23            Arquitetura
2  Barbara     21                 Design

In [15]:
df.columns

Index(['Unnamed: 0', 'DATA INICIAL', 'DATA FINAL', 'REGIÃO', 'ESTADO',
       'PRODUTO', 'NÚMERO DE POSTOS PESQUISADOS', 'UNIDADE DE MEDIDA',
       'PREÇO MÉDIO REVENDA', 'DESVIO PADRÃO REVENDA', 'PREÇO MÍNIMO REVENDA',
       'PREÇO MÁXIMO REVENDA', 'MARGEM MÉDIA REVENDA',
       'COEF DE VARIAÇÃO REVENDA', 'PREÇO MÉDIO DISTRIBUIÇÃO',
       'DESVIO PADRÃO DISTRIBUIÇÃO', 'PREÇO MÍNIMO DISTRIBUIÇÃO',
       'PREÇO MÁXIMO DISTRIBUIÇÃO', 'COEF DE VARIAÇÃO DISTRIBUIÇÃO', 'MÊS',
       'ANO'],
      dtype='object')

In [16]:
list(df.columns)

['Unnamed: 0',
 'DATA INICIAL',
 'DATA FINAL',
 'REGIÃO',
 'ESTADO',
 'PRODUTO',
 'NÚMERO DE POSTOS PESQUISADOS',
 'UNIDADE DE MEDIDA',
 'PREÇO MÉDIO REVENDA',
 'DESVIO PADRÃO REVENDA',
 'PREÇO MÍNIMO REVENDA',
 'PREÇO MÁXIMO REVENDA',
 'MARGEM MÉDIA REVENDA',
 'COEF DE VARIAÇÃO REVENDA',
 'PREÇO MÉDIO DISTRIBUIÇÃO',
 'DESVIO PADRÃO DISTRIBUIÇÃO',
 'PREÇO MÍNIMO DISTRIBUIÇÃO',
 'PREÇO MÁXIMO DISTRIBUIÇÃO',
 'COEF DE VARIAÇÃO DISTRIBUIÇÃO',
 'MÊS',
 'ANO']

In [17]:
type(df.columns)

pandas.core.indexes.base.Index

In [18]:
# para criar uma copia do DataFrame e renomear ele
alunos_editado = alunos.rename(columns={
    'nome':'primeiro nome',
    'curso': 'Área'
})

In [19]:
alunos_editado

  primeiro nome  idade                   Área
0       Rodrigo     20  Ciência da Computação
1       Ricardo     23            Arquitetura
2       Barbara     21                 Design

In [20]:
# para renomear o proprio DataFrame em questao, utilizar o parametro "inplace = True"
alunos.rename(columns={
    'nome': 'Nome',
    'idade': 'Idade',
    'curso': 'Curso'
}, inplace = True)

In [21]:
alunos

      Nome  Idade                  Curso
0  Rodrigo     20  Ciência da Computação
1  Ricardo     23            Arquitetura
2  Barbara     21                 Design

In [22]:
# renomeia o nome de todas as colunas atraves de uma lista, bom para DataFrame pequenos
alunos.columns = ['NOME', 'IDADE', 'CURSO']

In [23]:
alunos

      NOME  IDADE                  CURSO
0  Rodrigo     20  Ciência da Computação
1  Ricardo     23            Arquitetura
2  Barbara     21                 Design

In [24]:
df.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004

In [25]:
#seleciona uma coluna inteira
df['ESTADO']

0            DISTRITO FEDERAL
1                       GOIAS
2                 MATO GROSSO
3          MATO GROSSO DO SUL
4                     ALAGOAS
                 ...
106818    RIO GRANDE DO NORTE
106819      RIO GRANDE DO SUL
106820         SANTA CATARINA
106821              SAO PAULO
106822                SERGIPE
Name: ESTADO, Length: 106823, dtype: object

In [26]:
#seleciona um coluna inteira, não funciona em colunas que tem espaço no nome
df.MÊS

0         5
1         5
2         5
3         5
4         5
         ..
106818    6
106819    6
106820    6
106821    6
106822    6
Name: MÊS, Length: 106823, dtype: int64

In [27]:
type(df['ESTADO'])

pandas.core.series.Series

In [28]:
# selecionando a observação indexada no indice [1] do dataframe
df.iloc[1]

Unnamed: 0                                      1
DATA INICIAL                           2004-05-09
DATA FINAL                             2004-05-15
REGIÃO                               CENTRO OESTE
ESTADO                                      GOIAS
PRODUTO                          ETANOL HIDRATADO
NÚMERO DE POSTOS PESQUISADOS                  387
UNIDADE DE MEDIDA                            R$/l
PREÇO MÉDIO REVENDA                         1.162
DESVIO PADRÃO REVENDA                       0.114
PREÇO MÍNIMO REVENDA                         0.89
PREÇO MÁXIMO REVENDA                        1.449
MARGEM MÉDIA REVENDA                        0.399
COEF DE VARIAÇÃO REVENDA                    0.098
PREÇO MÉDIO DISTRIBUIÇÃO                    0.763
DESVIO PADRÃO DISTRIBUIÇÃO                  0.088
PREÇO MÍNIMO DISTRIBUIÇÃO                  0.5013
PREÇO MÁXIMO DISTRIBUIÇÃO                    1.05
COEF DE VARIAÇÃO DISTRIBUIÇÃO               0.115
MÊS                                             5
ANO                                          2004
Name: 1, dtype: object

In [29]:
# CRIANDO UMA SERIES
#cria um dataframe a partir de uma lista de elementos (pelo visto não da para chamar ele dps)
pd.Series([6.5,7.0,7.5])

0    6.5
1    7.0
2    7.5
dtype: float64

In [30]:
# é possivel alterar o nome dos indices
pd.Series([6.5,7.0,7.5], index = ['nota1', 'nota2', 'trabalho'])

nota1       6.5
nota2       7.0
trabalho    7.5
dtype: float64

In [31]:
# a series retornada referente a coluna, não é uma copia, mas sim uma referencia/view a coluna do dataframe
produto_view = df['PRODUTO']
produto_view

0         ETANOL HIDRATADO
1         ETANOL HIDRATADO
2         ETANOL HIDRATADO
3         ETANOL HIDRATADO
4         ETANOL HIDRATADO
                ...
106818                 GNV
106819                 GNV
106820                 GNV
106821                 GNV
106822                 GNV
Name: PRODUTO, Length: 106823, dtype: object

In [32]:
# retorna uma copia da coluna produto
produto_copy_bkp = df['PRODUTO'].copy()
produto_copy_bkp

0         ETANOL HIDRATADO
1         ETANOL HIDRATADO
2         ETANOL HIDRATADO
3         ETANOL HIDRATADO
4         ETANOL HIDRATADO
                ...
106818                 GNV
106819                 GNV
106820                 GNV
106821                 GNV
106822                 GNV
Name: PRODUTO, Length: 106823, dtype: object

In [33]:
# atribui um unico valor a coluna
df['PRODUTO'] = 'Combustivel'

In [34]:
df.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,Combustivel,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,Combustivel,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,Combustivel,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,Combustivel,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,Combustivel,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004

In [35]:
# cria variaves para o numero de linhas e colunas 
nrows, ncols = df.shape

In [36]:
#cria uma lista de novos produtos
novos_produtos = [f'Produto{i}'for i in range (nrows)]
len(novos_produtos)

106823

In [37]:
#a quantidade de elementos da lista 'novos_produtos' é igual ao numero de linhas do dataframe
df['PRODUTO'] = novos_produtos

In [38]:
df.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,Produto0,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,Produto1,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,Produto2,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,Produto3,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,Produto4,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004

In [39]:
print(produto_view)
print('\n')
print(produto_copy_bkp)

0         ETANOL HIDRATADO
1         ETANOL HIDRATADO
2         ETANOL HIDRATADO
3         ETANOL HIDRATADO
4         ETANOL HIDRATADO
                ...
106818                 GNV
106819                 GNV
106820                 GNV
106821                 GNV
106822                 GNV
Name: PRODUTO, Length: 106823, dtype: object


0         ETANOL HIDRATADO
1         ETANOL HIDRATADO
2         ETANOL HIDRATADO
3         ETANOL HIDRATADO
4         ETANOL HIDRATADO
                ...
106818                 GNV
106819                 GNV
106820                 GNV
106821                 GNV
106822                 GNV
Name: PRODUTO, Length: 106823, dtype: object

In [40]:
#voltando para os produtos originais atraves da copia
df['PRODUTO'] = produto_copy_bkp

In [41]:
df.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004

In [42]:
df['PREÇO MÉDIO REVENDA (dolar)'] = df['PREÇO MÉDIO REVENDA'] / 5

In [43]:
#cria um dataframe com o indice sendo string
pesquisa_de_satisfacao = pd.DataFrame({
    'bom': [50,70,45],
    'ruim':[167,50,73],
    'pessimo':[26,10,15]
}, index = ['Xbox','PlayStation5', 'Switch'])

In [44]:
pesquisa_de_satisfacao

              bom  ruim  pessimo
Xbox           50   167       26
PlayStation5   70    50       10
Switch         45    73       15

In [45]:
pesquisa_de_satisfacao.index

Index(['Xbox', 'PlayStation5', 'Switch'], dtype='object')

In [46]:
data_juncao = pd.DataFrame({
    'X': ['abc1234', 'abc1234', 'abc1234', 'efg5678', 'efg5678'],
    'Y': ['Grupo 1', 'Grupo 2', 'Grupo 3', 'Grupo 1', 'Grupo 2']
})

In [47]:
data_juncao

         X        Y
0  abc1234  Grupo 1
1  abc1234  Grupo 2
2  abc1234  Grupo 3
3  efg5678  Grupo 1
4  efg5678  Grupo 2

In [48]:
novos_indices = data_juncao['X'] + '' + ['Y']

In [49]:
df

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,PREÇO MÉDIO REVENDA (dolar)
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004,0.2576
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004,0.2324
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004,0.2778
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004,0.2524
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004,0.2362
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,...,0.818,0.018,2.756,0,2.756,2.756,0,6,2019,0.7148
106819,106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,...,0.95,0.038,2.451,0.402,1.9842,2.8661,0.164,6,2019,0.6802
106820,106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,...,0.914,0.065,1.998,0,1.9981,1.9981,0,6,2019,0.5824
106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,0.646,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019,0.6040
106822,106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,0.005,...,1.179,0.001,2.518,0,2.5175,2.5175,0,6,2019,0.7394

In [50]:
#retorna as informações do indice 1
df.iloc[1]

Unnamed: 0                                      1
DATA INICIAL                           2004-05-09
DATA FINAL                             2004-05-15
REGIÃO                               CENTRO OESTE
ESTADO                                      GOIAS
PRODUTO                          ETANOL HIDRATADO
NÚMERO DE POSTOS PESQUISADOS                  387
UNIDADE DE MEDIDA                            R$/l
PREÇO MÉDIO REVENDA                         1.162
DESVIO PADRÃO REVENDA                       0.114
PREÇO MÍNIMO REVENDA                         0.89
PREÇO MÁXIMO REVENDA                        1.449
MARGEM MÉDIA REVENDA                        0.399
COEF DE VARIAÇÃO REVENDA                    0.098
PREÇO MÉDIO DISTRIBUIÇÃO                    0.763
DESVIO PADRÃO DISTRIBUIÇÃO                  0.088
PREÇO MÍNIMO DISTRIBUIÇÃO                  0.5013
PREÇO MÁXIMO DISTRIBUIÇÃO                    1.05
COEF DE VARIAÇÃO DISTRIBUIÇÃO               0.115
MÊS                                             5
ANO                                          2004
PREÇO MÉDIO REVENDA (dolar)                0.2324
Name: 1, dtype: object

In [51]:
#retorna as informações dos primeiros 6 indices
df.iloc[:6]

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,PREÇO MÉDIO REVENDA (dolar)
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004,0.2576
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004,0.2324
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004,0.2778
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004,0.2524
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004,0.2362
5,5,2004-05-09,2004-05-15,NORDESTE,BAHIA,ETANOL HIDRATADO,408,R$/l,1.383,0.132,...,0.426,0.095,0.957,0.128,0.5686,1.35,0.134,5,2004,0.2766

In [52]:
#retorna as informações dos indices digitados na lista
df.iloc[[1,5,10,15]]

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,PREÇO MÉDIO REVENDA (dolar)
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004,0.2324
5,5,2004-05-09,2004-05-15,NORDESTE,BAHIA,ETANOL HIDRATADO,408,R$/l,1.383,0.132,...,0.426,0.095,0.957,0.128,0.5686,1.35,0.134,5,2004,0.2766
10,10,2004-05-09,2004-05-15,NORDESTE,PIAUI,ETANOL HIDRATADO,89,R$/l,1.573,0.134,...,0.494,0.085,1.079,0.078,0.8857,1.2499,0.072,5,2004,0.3146
15,15,2004-05-09,2004-05-15,NORTE,AMAZONAS,ETANOL HIDRATADO,53,R$/l,1.578,0.123,...,0.441,0.078,1.137,0.068,0.9515,1.2109,0.06,5,2004,0.3156

In [53]:
#retorna a informação da linha de indice 1 e coluna de indice 6
df.iloc[1,6]

np.int64(387)

In [54]:
pesquisa_de_satisfacao

              bom  ruim  pessimo
Xbox           50   167       26
PlayStation5   70    50       10
Switch         45    73       15

In [55]:
#retorna a informação do indice atraves do seu rotulo/nome
pesquisa_de_satisfacao.loc['Xbox']

bom         50
ruim       167
pessimo     26
Name: Xbox, dtype: int64

In [56]:
#retorna as informações dos rotulos dos indices digitados na lista
pesquisa_de_satisfacao.loc[['Xbox', 'PlayStation5']]

              bom  ruim  pessimo
Xbox           50   167       26
PlayStation5   70    50       10

In [57]:
#retorna as informações dos rotulos de todos os indices (:) e das colunas digitadas (tudo pelo nome pois foi utilizado o 'loc'
pesquisa_de_satisfacao.loc[:,['ruim','pessimo']]

              ruim  pessimo
Xbox           167       26
PlayStation5    50       10
Switch          73       15

In [58]:
df.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,PREÇO MÉDIO REVENDA (dolar)
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004,0.2576
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004,0.2324
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004,0.2778
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004,0.2524
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004,0.2362

In [59]:
### ATENÇÃO!!! indices onde os rotulos são o proprio numero do indice tambem é possivel usar o 'loc' como no exemplo abaixo

In [60]:
df.loc[1]

Unnamed: 0                                      1
DATA INICIAL                           2004-05-09
DATA FINAL                             2004-05-15
REGIÃO                               CENTRO OESTE
ESTADO                                      GOIAS
PRODUTO                          ETANOL HIDRATADO
NÚMERO DE POSTOS PESQUISADOS                  387
UNIDADE DE MEDIDA                            R$/l
PREÇO MÉDIO REVENDA                         1.162
DESVIO PADRÃO REVENDA                       0.114
PREÇO MÍNIMO REVENDA                         0.89
PREÇO MÁXIMO REVENDA                        1.449
MARGEM MÉDIA REVENDA                        0.399
COEF DE VARIAÇÃO REVENDA                    0.098
PREÇO MÉDIO DISTRIBUIÇÃO                    0.763
DESVIO PADRÃO DISTRIBUIÇÃO                  0.088
PREÇO MÍNIMO DISTRIBUIÇÃO                  0.5013
PREÇO MÁXIMO DISTRIBUIÇÃO                    1.05
COEF DE VARIAÇÃO DISTRIBUIÇÃO               0.115
MÊS                                             5
ANO                                          2004
PREÇO MÉDIO REVENDA (dolar)                0.2324
Name: 1, dtype: object

In [61]:
# retorna as informações das colunas escritas
df[['ESTADO', 'PRODUTO']]

                     ESTADO           PRODUTO
0          DISTRITO FEDERAL  ETANOL HIDRATADO
1                     GOIAS  ETANOL HIDRATADO
2               MATO GROSSO  ETANOL HIDRATADO
3        MATO GROSSO DO SUL  ETANOL HIDRATADO
4                   ALAGOAS  ETANOL HIDRATADO
...                     ...               ...
106818  RIO GRANDE DO NORTE               GNV
106819    RIO GRANDE DO SUL               GNV
106820       SANTA CATARINA               GNV
106821            SAO PAULO               GNV
106822              SERGIPE               GNV

[106823 rows x 2 columns]

In [62]:
# retorna todas as linhas de um criterio especifico, neste caso coluna indice 6(NÚMERO DE POSTOS PESQUISADOS) maior que 100
#vai passando de linha em linha (df.shape[0]) onde if o id.iloc[i,6] posição da linha que esta passando e coluna 6 são maiores que 100
df.iloc[[i for i in range(df.shape[0]) if df.iloc[i,6] > 100]]

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,PREÇO MÉDIO REVENDA (dolar)
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004,0.2576
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004,0.2324
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004,0.2778
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004,0.2524
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004,0.2362
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106797,106797,2019-06-23,2019-06-29,NORDESTE,PERNAMBUCO,GLP,165,R$/13Kg,66.735,3.701,...,13.237,0.055,53.498,3.184,46,60,0.06,6,2019,13.3470
106799,106799,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GLP,221,R$/13Kg,65.010,5.812,...,17.475,0.089,47.535,3.934,39,58.2,0.083,6,2019,13.0020
106801,106801,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GLP,374,R$/13Kg,69.442,5.413,...,18.18,0.078,51.262,6.52,37.028,68,0.127,6,2019,13.8884
106805,106805,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GLP,1017,R$/13Kg,66.893,6.100,...,17.679,0.091,49.214,5.071,40.19,72,0.103,6,2019,13.3786
106817,106817,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GNV,124,R$/m3,3.111,0.260,...,0.707,0.084,2.404,0.174,2.126,2.7909,0.072,6,2019,0.6222

In [63]:
df.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,PREÇO MÉDIO REVENDA (dolar)
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004,0.2576
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004,0.2324
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004,0.2778
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004,0.2524
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004,0.2362

In [64]:
#utilizado para DELETAR uma coluna do DataFrame
del df['Unnamed: 0']

In [65]:
#utilizado para DELETAR uma coluna do DataFrame
del df['PREÇO MÉDIO REVENDA (dolar)']

In [66]:
#utilizado para salvar um DataFrame em arquivo csv, passsando o diretorio, pasta e por fim, o nome do arquivo
# por padrão, esse metodo salva os indices como coluna (igual o q removemos antes) por isso utilizamos 'index = False'.
#por padrão, o metodo utilizado o "," como separador das colunas. Caso queira alteralo, utilize o sep =''
df.to_csv('./datasets/GasPricesinBrazil_2004-2019-preprocessado.csv', index = False)

In [67]:
#carrega o dataframe
df = pd.read_csv('./datasets/GasPricesinBrazil_2004-2019-preprocessado.csv')

In [68]:
#mostra somente os valores disponiveis na coluna, sem repetir eles
df['ESTADO'].unique()

array(['DISTRITO FEDERAL', 'GOIAS', 'MATO GROSSO', 'MATO GROSSO DO SUL',
       'ALAGOAS', 'BAHIA', 'CEARA', 'MARANHAO', 'PARAIBA', 'PERNAMBUCO',
       'PIAUI', 'RIO GRANDE DO NORTE', 'SERGIPE', 'ACRE', 'AMAPA',
       'AMAZONAS', 'PARA', 'RONDONIA', 'RORAIMA', 'TOCANTINS',
       'ESPIRITO SANTO', 'MINAS GERAIS', 'RIO DE JANEIRO', 'SAO PAULO',
       'PARANA', 'RIO GRANDE DO SUL', 'SANTA CATARINA'], dtype=object)

In [69]:
#salva em uma variavel uma filtragem de valores booleanos(True/False) de uma series, retornando uma series de valores booleanos
selecao_sao_paulo = df['ESTADO'] == 'SAO PAULO'

In [70]:
selecao_sao_paulo

0         False
1         False
2         False
3         False
4         False
          ...
106818    False
106819    False
106820    False
106821     True
106822    False
Name: ESTADO, Length: 106823, dtype: bool

In [71]:
type(selecao_sao_paulo)

pandas.core.series.Series

In [72]:
selecao_sao_paulo.shape

(106823,)

In [73]:
df.shape

(106823, 20)

In [74]:
#mostra somente as linhas com o valor da variavel True, assim fazendo a filtragem
#.head() não é obrigatorio, usado so para melhor visualização
df[selecao_sao_paulo].head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
23,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,0.590,1.150,0.198,0.111,0.57,0.056,0.4271,1.4123,0.098,5,2004
50,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,0.590,1.150,0.19,0.108,0.576,0.05,0.43204,0.9724,0.087,5,2004
77,2004-05-23,2004-05-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4077,R$/l,0.823,0.071,0.620,1.199,0.209,0.086,0.614,0.063,0.34951,1.412,0.103,5,2004
104,2004-05-30,2004-06-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4073,R$/l,0.887,0.075,0.639,1.359,0.216,0.085,0.671,0.075,0.3398,1.0669,0.112,5,2004
131,2004-06-06,2004-06-12,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4082,R$/l,0.894,0.071,0.669,1.199,0.205,0.079,0.689,0.072,0.47797,1.0669,0.104,6,2004

In [75]:
#tambem é possível utilizar com o loc
df.loc[selecao_sao_paulo].head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
23,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,0.590,1.150,0.198,0.111,0.57,0.056,0.4271,1.4123,0.098,5,2004
50,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,0.590,1.150,0.19,0.108,0.576,0.05,0.43204,0.9724,0.087,5,2004
77,2004-05-23,2004-05-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4077,R$/l,0.823,0.071,0.620,1.199,0.209,0.086,0.614,0.063,0.34951,1.412,0.103,5,2004
104,2004-05-30,2004-06-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4073,R$/l,0.887,0.075,0.639,1.359,0.216,0.085,0.671,0.075,0.3398,1.0669,0.112,5,2004
131,2004-06-06,2004-06-12,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4082,R$/l,0.894,0.071,0.669,1.199,0.205,0.079,0.689,0.072,0.47797,1.0669,0.104,6,2004

In [76]:
#cria um dataframe com a filtragem escrita
postos_sp = df.query('ESTADO == "SAO PAULO"')

In [77]:
#.reset_index() serve para reiniciar o indice, não utilizando o passado e criando um novo de acordo com o dataframe
#tambem cria um coluna com os indices antigos
postos_sp_reset = postos_sp.reset_index()

In [78]:
postos_sp_reset.head()

,index,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,23,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,...,1.150,0.198,0.111,0.57,0.056,0.4271,1.4123,0.098,5,2004
1,50,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,...,1.150,0.19,0.108,0.576,0.05,0.43204,0.9724,0.087,5,2004
2,77,2004-05-23,2004-05-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4077,R$/l,0.823,0.071,...,1.199,0.209,0.086,0.614,0.063,0.34951,1.412,0.103,5,2004
3,104,2004-05-30,2004-06-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4073,R$/l,0.887,0.075,...,1.359,0.216,0.085,0.671,0.075,0.3398,1.0669,0.112,5,2004
4,131,2004-06-06,2004-06-12,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4082,R$/l,0.894,0.071,...,1.199,0.205,0.079,0.689,0.072,0.47797,1.0669,0.104,6,2004

In [79]:
#drop = True serve para não criar essa nova coluna com os indices do antigo dataframe
postos_sp_reset.reset_index(drop = True).head()

,index,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,23,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,...,1.150,0.198,0.111,0.57,0.056,0.4271,1.4123,0.098,5,2004
1,50,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,...,1.150,0.19,0.108,0.576,0.05,0.43204,0.9724,0.087,5,2004
2,77,2004-05-23,2004-05-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4077,R$/l,0.823,0.071,...,1.199,0.209,0.086,0.614,0.063,0.34951,1.412,0.103,5,2004
3,104,2004-05-30,2004-06-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4073,R$/l,0.887,0.075,...,1.359,0.216,0.085,0.671,0.075,0.3398,1.0669,0.112,5,2004
4,131,2004-06-06,2004-06-12,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4082,R$/l,0.894,0.071,...,1.199,0.205,0.079,0.689,0.072,0.47797,1.0669,0.104,6,2004

In [80]:
#tambem é possivel fazer tudo isso em um unico comando
postos_sp = df.query('ESTADO == "SAO PAULO"').reset_index(drop = True)

In [81]:
# & = and, | = or, ~ = not
#salva em uma variavel duas condições em valores booleanos

selecao = (df['ESTADO'] == 'RIO DE JANEIRO') & (df['PREÇO MÉDIO REVENDA'] > 2)

In [82]:
#transforma esssa variavel em um dataframe, resetando o indice e apagando a coluna gerada
rj_maior2 = df[selecao].reset_index(drop = True)

In [83]:
rj_maior2.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,2006-02-26,2006-03-04,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,881,R$/l,2.028,0.148,1.589,2.550,0.222,0.073,1.806,0.11,1.31,2.1358,0.061,2,2006
1,2006-03-05,2006-03-11,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,889,R$/l,2.125,0.149,1.779,2.550,0.286,0.070,1.839,0.117,1.438,2.2801,0.064,3,2006
2,2006-03-12,2006-03-18,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,902,R$/l,2.163,0.138,1.799,2.599,0.268,0.064,1.895,0.134,1.43,2.3454,0.071,3,2006
3,2006-03-19,2006-03-25,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,898,R$/l,2.166,0.146,1.760,2.568,0.231,0.067,1.935,0.14,1.438,2.2925,0.072,3,2006
4,2006-03-26,2006-04-01,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,890,R$/l,2.172,0.143,1.789,2.550,0.209,0.066,1.963,0.133,1.438,2.2513,0.068,3,2006

In [84]:
#salva em uma variavel duas condições em valores booleanos
selecao2 = (df['ESTADO'] != 'RIO DE JANEIRO') & (df['ESTADO'] != 'MATO GROSSO')

In [85]:
#ve no dataframe a condição estabelecida na variavel
df[selecao2].head().reset_index(drop = True)

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
3,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004
4,2004-05-09,2004-05-15,NORDESTE,BAHIA,ETANOL HIDRATADO,408,R$/l,1.383,0.132,0.999,2.050,0.426,0.095,0.957,0.128,0.5686,1.35,0.134,5,2004

In [86]:
# outro jeito de fazer essa filtragem, demora mais porem ocupa menos espaço, melhor para arquivos com muuuuitas linhas
postos_rj = df['ESTADO'] == 'RIO DE JANEIRO'
postos_rj = df[postos_rj]

In [87]:
#cria a outra condição em outra variavel, utilizando o dataframe criado de referencia
postos_rj_maior2 = postos_rj['PREÇO MÉDIO REVENDA'] > 2
#transforma esssa variavel em um dataframe, resetando o indice e apagando a coluna gerada
postos_rj_maior2 = postos_rj[postos_rj_maior2].reset_index(drop = True)

In [88]:
postos_rj_maior2.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,2006-02-26,2006-03-04,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,881,R$/l,2.028,0.148,1.589,2.550,0.222,0.073,1.806,0.11,1.31,2.1358,0.061,2,2006
1,2006-03-05,2006-03-11,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,889,R$/l,2.125,0.149,1.779,2.550,0.286,0.070,1.839,0.117,1.438,2.2801,0.064,3,2006
2,2006-03-12,2006-03-18,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,902,R$/l,2.163,0.138,1.799,2.599,0.268,0.064,1.895,0.134,1.43,2.3454,0.071,3,2006
3,2006-03-19,2006-03-25,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,898,R$/l,2.166,0.146,1.760,2.568,0.231,0.067,1.935,0.14,1.438,2.2925,0.072,3,2006
4,2006-03-26,2006-04-01,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,890,R$/l,2.172,0.143,1.789,2.550,0.209,0.066,1.963,0.133,1.438,2.2513,0.068,3,2006

In [89]:
#EXERCICIO RJ, SP, GASOLINA COMUM E MAIOR QUE 2

In [90]:
selecao1 = (df['ESTADO'] == 'RIO DE JANEIRO') | (df['ESTADO'] == 'SAO PAULO')

In [91]:
postos_rj_sp = df[selecao1]

In [92]:
selecao2 = postos_rj_sp['PRODUTO'] == 'GASOLINA COMUM'

In [93]:
gasolina = postos_rj_sp[selecao2]

In [94]:
selecao3 = gasolina['PREÇO MÉDIO REVENDA'] > 2

In [95]:
postos_sp_rj_gasolina_preco_maior_que_2 = gasolina[selecao3].reset_index(drop = True)

In [96]:
postos_sp_rj_gasolina_preco_maior_que_2.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,2004-05-09,2004-05-15,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1071,R$/l,2.045,0.109,1.70,2.599,0.254,0.053,1.791,0.047,1.6363,1.9594,0.026,5,2004
1,2004-05-16,2004-05-22,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1055,R$/l,2.040,0.113,1.70,2.599,0.252,0.055,1.788,0.049,1.5943,1.99651,0.027,5,2004
2,2004-05-23,2004-05-29,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1091,R$/l,2.042,0.108,1.70,2.599,0.252,0.053,1.79,0.046,1.63596,2.2137,0.026,5,2004
3,2004-05-30,2004-06-05,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1055,R$/l,2.053,0.111,1.73,2.599,0.251,0.054,1.802,0.055,1.64,2.21425,0.031,5,2004
4,2004-06-06,2004-06-12,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1091,R$/l,2.063,0.107,1.76,2.599,0.247,0.052,1.816,0.054,1.64,2.32425,0.03,6,2004

In [97]:
print(postos_sp_rj_gasolina_preco_maior_que_2['ESTADO'].unique())
print(postos_sp_rj_gasolina_preco_maior_que_2['PRODUTO'].unique())

['RIO DE JANEIRO' 'SAO PAULO']
['GASOLINA COMUM']

In [98]:
selecao = (df['ANO'] == 2008) | (df['ANO'] == 2010) | (df['ANO'] == 2012)

In [99]:
ano_08_10_12 = df[selecao]

In [100]:
ano_08_10_12['ANO'].unique()

array([2008, 2010, 2012])

In [101]:
sele = df.query('ANO in [2008, 2010, 2012]')

In [102]:
sele.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
5098,2008-01-06,2008-01-12,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,80,R$/l,1.806,0.082,1.709,1.950,0.29,0.045,1.516,0.061,1.3892,1.6157,0.04,1,2008
5099,2008-01-06,2008-01-12,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,255,R$/l,1.616,0.100,1.470,1.899,0.293,0.062,1.323,0.05,1.2242,1.6173,0.038,1,2008
5100,2008-01-06,2008-01-12,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,142,R$/l,1.581,0.095,1.390,1.850,0.278,0.060,1.303,0.073,1.14,1.45,0.056,1,2008
5101,2008-01-06,2008-01-12,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,133,R$/l,1.831,0.046,1.680,1.910,0.382,0.025,1.449,0.044,1.3247,1.5514,0.03,1,2008
5102,2008-01-06,2008-01-12,NORDESTE,ALAGOAS,ETANOL HIDRATADO,97,R$/l,1.699,0.098,1.530,1.999,0.199,0.058,1.5,0.062,1.39,1.7689,0.041,1,2008

In [103]:
ano_08_10_12.shape

(19576, 20)

In [104]:
sele.shape

(19576, 20)

In [105]:
bol = df['ANO'].isin([2008,2010,2012])

In [106]:
df[bol]

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
5098,2008-01-06,2008-01-12,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,80,R$/l,1.806,0.082,1.709,1.950,0.29,0.045,1.516,0.061,1.3892,1.6157,0.04,1,2008
5099,2008-01-06,2008-01-12,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,255,R$/l,1.616,0.100,1.470,1.899,0.293,0.062,1.323,0.05,1.2242,1.6173,0.038,1,2008
5100,2008-01-06,2008-01-12,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,142,R$/l,1.581,0.095,1.390,1.850,0.278,0.060,1.303,0.073,1.14,1.45,0.056,1,2008
5101,2008-01-06,2008-01-12,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,133,R$/l,1.831,0.046,1.680,1.910,0.382,0.025,1.449,0.044,1.3247,1.5514,0.03,1,2008
5102,2008-01-06,2008-01-12,NORDESTE,ALAGOAS,ETANOL HIDRATADO,97,R$/l,1.699,0.098,1.530,1.999,0.199,0.058,1.5,0.062,1.39,1.7689,0.041,1,2008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55754,2012-12-30,2013-01-05,NORDESTE,RIO GRANDE DO NORTE,GNV,17,R$/m3,1.891,0.015,1.860,1.900,0.466,0.008,1.425,0.098,1.2657,1.4789,0.069,12,2012
55755,2012-12-30,2013-01-05,SUL,RIO GRANDE DO SUL,GNV,34,R$/m3,1.980,0.040,1.919,2.140,0.566,0.020,1.414,0.028,1.3997,1.4608,0.02,12,2012
55756,2012-12-30,2013-01-05,SUL,SANTA CATARINA,GNV,41,R$/m3,2.003,0.034,1.879,2.099,-,0.017,-,-,-,-,-,12,2012
55757,2012-12-30,2013-01-05,SUDESTE,SAO PAULO,GNV,82,R$/m3,1.598,0.199,1.399,2.599,0.397,0.125,1.201,0.182,0.8354,1.535,0.152,12,2012
55758,2012-12-30,2013-01-05,NORDESTE,SERGIPE,GNV,11,R$/m3,1.847,0.033,1.790,1.899,0.504,0.018,1.343,0.178,1.1253,1.543,0.133,12,2012

In [107]:
df_pre = df.copy()

In [108]:
df_pre.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106823 entries, 0 to 106822
Data columns (total 20 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   DATA INICIAL                   106823 non-null  object
 1   DATA FINAL                     106823 non-null  object
 2   REGIÃO                         106823 non-null  object
 3   ESTADO                         106823 non-null  object
 4   PRODUTO                        106823 non-null  object
 5   NÚMERO DE POSTOS PESQUISADOS   106823 non-null  int64
 6   UNIDADE DE MEDIDA              106823 non-null  object
 7   PREÇO MÉDIO REVENDA            106823 non-null  float64
 8   DESVIO PADRÃO REVENDA          106823 non-null  float64
 9   PREÇO MÍNIMO REVENDA           106823 non-null  float64
 10  PREÇO MÁXIMO REVENDA           106823 non-null  float64
 11  MARGEM MÉDIA REVENDA           106823 non-null  object
 12  COEF DE VARIAÇÃO REVENDA       106823 non-null  float64
 13  PREÇO MÉDIO DISTRIBUIÇÃO       106823 non-null  object
 14  DESVIO PADRÃO DISTRIBUIÇÃO     106823 non-null  object
 15  PREÇO MÍNIMO DISTRIBUIÇÃO      106823 non-null  object
 16  PREÇO MÁXIMO DISTRIBUIÇÃO      106823 non-null  object
 17  COEF DE VARIAÇÃO DISTRIBUIÇÃO  106823 non-null  object
 18  MÊS                            106823 non-null  int64
 19  ANO                            106823 non-null  int64
dtypes: float64(5), int64(3), object(12)
memory usage: 16.3+ MB

In [109]:
#serve para mudar o tipo da coluna para datetime, utilizado em datas
df_pre['DATA FINAL'] = pd.to_datetime(df_pre['DATA FINAL'])

In [110]:
#convertendo atributos/colunas para 'numeric'
for atributo2 in ['MARGEM MÉDIA REVENDA','PREÇO MÉDIO DISTRIBUIÇÃO','DESVIO PADRÃO DISTRIBUIÇÃO','PREÇO MÍNIMO DISTRIBUIÇÃO','PREÇO MÁXIMO DISTRIBUIÇÃO','COEF DE VARIAÇÃO DISTRIBUIÇÃO']:
#converte a coluna (de valores string) para um tipo numerico
#em caso de erro na conversão (p. ex., uma string que não representa um número), um valor vazio (null/nan)
#atribuido no lugar
    df_pre[atributo2] = pd.to_numeric(df_pre[atributo2], errors='coerce')

In [111]:
df_pre.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106823 entries, 0 to 106822
Data columns (total 20 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   DATA INICIAL                   106823 non-null  object
 1   DATA FINAL                     106823 non-null  datetime64[ns]
 2   REGIÃO                         106823 non-null  object
 3   ESTADO                         106823 non-null  object
 4   PRODUTO                        106823 non-null  object
 5   NÚMERO DE POSTOS PESQUISADOS   106823 non-null  int64
 6   UNIDADE DE MEDIDA              106823 non-null  object
 7   PREÇO MÉDIO REVENDA            106823 non-null  float64
 8   DESVIO PADRÃO REVENDA          106823 non-null  float64
 9   PREÇO MÍNIMO REVENDA           106823 non-null  float64
 10  PREÇO MÁXIMO REVENDA           106823 non-null  float64
 11  MARGEM MÉDIA REVENDA           103392 non-null  float64
 12  COEF DE VARIAÇÃO REVENDA       106823 non-null  float64
 13  PREÇO MÉDIO DISTRIBUIÇÃO       103423 non-null  float64
 14  DESVIO PADRÃO DISTRIBUIÇÃO     103423 non-null  float64
 15  PREÇO MÍNIMO DISTRIBUIÇÃO      103423 non-null  float64
 16  PREÇO MÁXIMO DISTRIBUIÇÃO      103423 non-null  float64
 17  COEF DE VARIAÇÃO DISTRIBUIÇÃO  103423 non-null  float64
 18  MÊS                            106823 non-null  int64
 19  ANO                            106823 non-null  int64
dtypes: datetime64[ns](1), float64(11), int64(3), object(5)
memory usage: 16.3+ MB

In [112]:
#cria uma serie/mascara onde mostra todas as linhas onde possui valor nulo para a coluna designada
mask = df_pre['PREÇO MÉDIO DISTRIBUIÇÃO'].isnull()

In [113]:
#passa a mascara no dataframe original
df[mask]

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
1903,2005-09-25,2005-10-01,NORTE,PARA,ETANOL HIDRATADO,2,R$/l,1.694,0.283,1.690,2.090,-,0.167,-,-,-,-,-,9,2005
1958,2005-10-09,2005-10-15,NORTE,RORAIMA,ETANOL HIDRATADO,3,R$/l,2.000,0.000,2.000,2.000,-,0.000,-,-,-,-,-,10,2005
2012,2005-10-23,2005-10-29,NORTE,RORAIMA,ETANOL HIDRATADO,3,R$/l,2.277,0.023,2.250,2.290,-,0.010,-,-,-,-,-,10,2005
2497,2006-02-26,2006-03-04,NORTE,RORAIMA,ETANOL HIDRATADO,11,R$/l,2.182,0.040,2.100,2.200,-,0.018,-,-,-,-,-,2,2006
3199,2006-08-27,2006-09-02,NORTE,RORAIMA,ETANOL HIDRATADO,22,R$/l,2.285,0.068,1.980,2.300,-,0.030,-,-,-,-,-,8,2006
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106664,2019-06-16,2019-06-22,SUDESTE,MINAS GERAIS,GNV,5,R$/m3,3.445,0.147,3.347,3.699,-,0.043,-,-,-,-,-,6,2019
106666,2019-06-16,2019-06-22,SUL,PARANA,GNV,7,R$/m3,3.132,0.295,3.049,3.890,-,0.094,-,-,-,-,-,6,2019
106811,2019-06-23,2019-06-29,SUDESTE,ESPIRITO SANTO,GNV,4,R$/m3,3.299,0.005,3.290,3.299,-,0.002,-,-,-,-,-,6,2019
106813,2019-06-23,2019-06-29,SUDESTE,MINAS GERAIS,GNV,6,R$/m3,3.548,0.100,3.495,3.699,-,0.028,-,-,-,-,-,6,2019
106815,2019-06-23,2019-06-29,SUL,PARANA,GNV,1,R$/m3,3.290,0.000,3.290,3.290,-,0.000,-,-,-,-,-,6,2019

In [114]:
#substitui o valor NaN por 0 em todos os lugares que tiver valor nulo
df_pre_fill = df_pre.fillna(0)
df_pre_fill.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106823 entries, 0 to 106822
Data columns (total 20 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   DATA INICIAL                   106823 non-null  object
 1   DATA FINAL                     106823 non-null  datetime64[ns]
 2   REGIÃO                         106823 non-null  object
 3   ESTADO                         106823 non-null  object
 4   PRODUTO                        106823 non-null  object
 5   NÚMERO DE POSTOS PESQUISADOS   106823 non-null  int64
 6   UNIDADE DE MEDIDA              106823 non-null  object
 7   PREÇO MÉDIO REVENDA            106823 non-null  float64
 8   DESVIO PADRÃO REVENDA          106823 non-null  float64
 9   PREÇO MÍNIMO REVENDA           106823 non-null  float64
 10  PREÇO MÁXIMO REVENDA           106823 non-null  float64
 11  MARGEM MÉDIA REVENDA           106823 non-null  float64
 12  COEF DE VARIAÇÃO REVENDA       106823 non-null  float64
 13  PREÇO MÉDIO DISTRIBUIÇÃO       106823 non-null  float64
 14  DESVIO PADRÃO DISTRIBUIÇÃO     106823 non-null  float64
 15  PREÇO MÍNIMO DISTRIBUIÇÃO      106823 non-null  float64
 16  PREÇO MÁXIMO DISTRIBUIÇÃO      106823 non-null  float64
 17  COEF DE VARIAÇÃO DISTRIBUIÇÃO  106823 non-null  float64
 18  MÊS                            106823 non-null  int64
 19  ANO                            106823 non-null  int64
dtypes: datetime64[ns](1), float64(11), int64(3), object(5)
memory usage: 16.3+ MB

In [115]:
#preenche os espaços nulos da coluna 'MARGEM MÉDIA REVENDA' com o valor escolhido ou calculado.
df_pre_fill2 = df_pre2.fillna(value={
    'MARGEM MÉDIA REVENDA': df_pre2['PREÇO MÁXIMO REVENDA'] - df_pre2['PREÇO MÍNIMO REVENDA']
    
})

NameError: name 'df_pre2' is not defined

In [116]:
df_pre_fill2.info()

NameError: name 'df_pre_fill2' is not defined

In [117]:
#apaga TODAS as linhas que posssuem valor NaN(nulo), inplace = True é para ser feito no df_pre, e nao passar um serie ou copia
df_pre.dropna(inplace = True)

In [ ]:
df_pre.info()

In [118]:
#salva o novo dataframe tratado sem valores nulo! Utilizar o index = False para não criar uma coluna com os indices
df_pre.to_csv('./datasets/GasPricesinBrazil_2004-2019-preprocessado-final.csv', index = False)

In [119]:
# carregando o dataset final do formato "csv"
df_final = pd.read_csv('./datasets/GasPricesinBrazil_2004-2019-preprocessado-final.csv')

In [120]:
#retorna um df mostrando as descrições de cada coluna, mostrando seu valor maximo(max), minimo(min), desvio padrao(std) e etc
df_final.describe()

,NÚMERO DE POSTOS PESQUISADOS,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
count,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000
mean,240.511935,10.784472,0.652589,9.334931,12.458686,2.225151,0.045749,8.559322,0.559441,7.414814,9.805621,0.046640,6.485067,2011.737001
std,408.039174,17.685852,1.346422,15.024383,20.801190,4.375085,0.024488,13.603686,1.256914,11.681366,15.933999,0.042114,3.442155,4.410491
min,1.000000,0.766000,0.000000,0.590000,0.999000,0.001000,0.000000,0.506000,0.000000,0.325700,0.599200,0.000000,1.000000,2004.000000
25%,47.000000,2.073000,0.073000,1.900000,2.330000,0.282000,0.030000,1.795000,0.047000,1.674400,1.945600,0.021000,4.000000,2008.000000
50%,108.000000,2.723000,0.115000,2.509000,3.000000,0.383000,0.042000,2.335000,0.077000,2.220000,2.507050,0.031000,6.000000,2012.000000
75%,251.000000,3.745000,0.190000,3.490000,4.150000,0.560000,0.058000,3.307000,0.151000,3.142800,3.520000,0.061000,9.000000,2016.000000
max,4167.000000,99.357000,10.748000,90.000000,120.000000,36.847000,0.262000,83.137000,18.385000,83.000000,94.500000,0.780000,12.000000,2019.000000

In [121]:
#por ser um df, é possivel selecionar as colunas que deseja ver as descrições
df_final.describe()[['DESVIO PADRÃO REVENDA', 'MARGEM MÉDIA REVENDA']]

       DESVIO PADRÃO REVENDA  MARGEM MÉDIA REVENDA
count          103392.000000         103392.000000
mean                0.652589              2.225151
std                 1.346422              4.375085
min                 0.000000              0.001000
25%                 0.073000              0.282000
50%                 0.115000              0.383000
75%                 0.190000              0.560000
max                10.748000             36.847000

In [122]:
#atraves do "loc" é possivel passar os indices que deseja consultar apenas escrevendo o nome
df_final.describe()[['DESVIO PADRÃO REVENDA', 'MARGEM MÉDIA REVENDA']].loc[['min', 'max']]

     DESVIO PADRÃO REVENDA  MARGEM MÉDIA REVENDA
min                  0.000                 0.001
max                 10.748                36.847

In [123]:
#tambem é possivel consultar usando o .min() para ver o minimo, tambem tem o .max(), .std() e entre outros
menor_preco_minimo_revenda = df_final['PREÇO MÍNIMO REVENDA'].min()
print(f'O menor preço minimo de revenda é {menor_preco_minimo_revenda:.2F}')

O menor preço minimo de revenda é 0.59

In [124]:
mean = df_final['PREÇO MÍNIMO REVENDA'].mean()
std = df_final['PREÇO MÍNIMO REVENDA'].std()
print(f'A média do PREÇO MÍNIMO REVENDA é {mean:.2f} e o desvio padrão é {std:.2f}')

A média do PREÇO MÍNIMO REVENDA é 9.33 e o desvio padrão é 15.02

In [125]:
#mostra os valores unicos da coluna ESTADO
df_final['ESTADO'].unique()

array(['DISTRITO FEDERAL', 'GOIAS', 'MATO GROSSO', 'MATO GROSSO DO SUL',
       'ALAGOAS', 'BAHIA', 'CEARA', 'MARANHAO', 'PARAIBA', 'PERNAMBUCO',
       'PIAUI', 'RIO GRANDE DO NORTE', 'SERGIPE', 'ACRE', 'AMAPA',
       'AMAZONAS', 'PARA', 'RONDONIA', 'RORAIMA', 'TOCANTINS',
       'ESPIRITO SANTO', 'MINAS GERAIS', 'RIO DE JANEIRO', 'SAO PAULO',
       'PARANA', 'RIO GRANDE DO SUL', 'SANTA CATARINA'], dtype=object)

In [126]:
#o "sorted()" ordena os valores unicos em ordem crescente/alfabetica
sorted(df_final['ESTADO'].unique())

['ACRE',
 'ALAGOAS',
 'AMAPA',
 'AMAZONAS',
 'BAHIA',
 'CEARA',
 'DISTRITO FEDERAL',
 'ESPIRITO SANTO',
 'GOIAS',
 'MARANHAO',
 'MATO GROSSO',
 'MATO GROSSO DO SUL',
 'MINAS GERAIS',
 'PARA',
 'PARAIBA',
 'PARANA',
 'PERNAMBUCO',
 'PIAUI',
 'RIO DE JANEIRO',
 'RIO GRANDE DO NORTE',
 'RIO GRANDE DO SUL',
 'RONDONIA',
 'RORAIMA',
 'SANTA CATARINA',
 'SAO PAULO',
 'SERGIPE',
 'TOCANTINS']

In [127]:
sorted(df_final['MÊS'].unique())

[np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9),
 np.int64(10),
 np.int64(11),
 np.int64(12)]

In [128]:
#retorna em ordem decrescente, a quantidade de linhas/registros para cada estado
df_final['ESTADO'].value_counts()

ESTADO
BAHIA                  4263
RIO DE JANEIRO         4262
SAO PAULO              4261
RIO GRANDE DO SUL      4249
PARAIBA                4240
PERNAMBUCO             4236
SERGIPE                4202
SANTA CATARINA         4164
MINAS GERAIS           4142
ESPIRITO SANTO         4079
MATO GROSSO DO SUL     4076
ALAGOAS                4020
RIO GRANDE DO NORTE    3999
CEARA                  3964
PARANA                 3902
AMAZONAS               3713
MATO GROSSO            3703
PARA                   3477
MARANHAO               3470
ACRE                   3463
RORAIMA                3457
TOCANTINS              3453
GOIAS                  3449
RONDONIA               3441
PIAUI                  3394
DISTRITO FEDERAL       3317
AMAPA                  2996
Name: count, dtype: int64

In [129]:
#transforma a series em datafrma utilizando o .to_frame()
cont = df_final['ESTADO'].value_counts().to_frame()

In [130]:
#renomeia a coluna e o indice do df cont
cont.rename(columns={
    'count':'CONTAGEM'
    
},index={
    'BAHIA': 'BAHIANO'
} ,inplace = True)

In [131]:
cont

                     CONTAGEM
ESTADO
BAHIANO                  4263
RIO DE JANEIRO           4262
SAO PAULO                4261
RIO GRANDE DO SUL        4249
PARAIBA                  4240
PERNAMBUCO               4236
SERGIPE                  4202
SANTA CATARINA           4164
MINAS GERAIS             4142
ESPIRITO SANTO           4079
MATO GROSSO DO SUL       4076
ALAGOAS                  4020
RIO GRANDE DO NORTE      3999
CEARA                    3964
PARANA                   3902
AMAZONAS                 3713
MATO GROSSO              3703
PARA                     3477
MARANHAO                 3470
ACRE                     3463
RORAIMA                  3457
TOCANTINS                3453
GOIAS                    3449
RONDONIA                 3441
PIAUI                    3394
DISTRITO FEDERAL         3317
AMAPA                    2996

In [132]:
#cria um novo DataFrame
df =pd.DataFrame({
    'A': [1, 2, 3, 4],
    'B': [10, 20, 30, 40],
    'C': [100, 200, 300, 400]  
}, index = ['Linha 1', 'Linha 2', 'Linha 3', 'Linha 4'])

In [133]:
#cria uma função para somar a series
def nossa_soma(series):
    return series.sum()

In [134]:
#cria uma coluna com a funcao "nossa_soma" que vai somando os valores de cada linha. (axis=1: Linhas/ axis=0: Colunas)
df['SOMA (A, B, C)'] = df.apply(nossa_soma, axis = 1)

In [135]:
df

         A   B    C  SOMA (A, B, C)
Linha 1  1  10  100             111
Linha 2  2  20  200             222
Linha 3  3  30  300             333
Linha 4  4  40  400             444

In [136]:
#cria um indice com a funcao "nossa_soma" que vai somando os valores de cada coluna. (axis=1: Linhas/ axis=0: Colunas)
df.loc['Linha 5'] = df.apply(nossa_soma, axis = 0)

In [137]:
df

          A    B     C  SOMA (A, B, C)
Linha 1   1   10   100             111
Linha 2   2   20   200             222
Linha 3   3   30   300             333
Linha 4   4   40   400             444
Linha 5  10  100  1000            1110

In [138]:
#cria uma coluna com a função lambda(vc coloca oq vai acontecer dps)que vai pegar a média dos valores de cada linha
#onde so vai pegar os valores das colunas A, B, C
#(axis=1: Linhas/ axis=0: Colunas)
df['Média'] = df[['A', 'B', 'C']].apply(lambda series: series.mean(), axis = 1)

In [139]:
df

          A    B     C  SOMA (A, B, C)  Média
Linha 1   1   10   100             111   37.0
Linha 2   2   20   200             222   74.0
Linha 3   3   30   300             333  111.0
Linha 4   4   40   400             444  148.0
Linha 5  10  100  1000            1110  370.0

In [140]:
#renomeia o nome da coluna, o inplace serve para a mudança ser no proprio dataframe e n em uma series
df.rename(columns = {
    'Média':'MEDIA(A, B, C)'
}, inplace = True)

In [141]:
df

          A    B     C  SOMA (A, B, C)  MEDIA(A, B, C)
Linha 1   1   10   100             111            37.0
Linha 2   2   20   200             222            74.0
Linha 3   3   30   300             333           111.0
Linha 4   4   40   400             444           148.0
Linha 5  10  100  1000            1110           370.0

In [142]:
#cria uma coluna usando a função lambda onde mostra os valores da coluna C vezes 2.
df['C * 2'] = df['C'].apply(lambda x: x * 2)

In [143]:
df

          A    B     C  SOMA (A, B, C)  MEDIA(A, B, C)  C * 2
Linha 1   1   10   100             111            37.0    200
Linha 2   2   20   200             222            74.0    400
Linha 3   3   30   300             333           111.0    600
Linha 4   4   40   400             444           148.0    800
Linha 5  10  100  1000            1110           370.0   2000

In [144]:
#tambem é possivel criar essa coluna de um jeito mais facil, sem precisar usar o lambda
df['A * 2'] = df['A'] * 2

In [145]:
df

          A    B     C  SOMA (A, B, C)  MEDIA(A, B, C)  C * 2  A * 2
Linha 1   1   10   100             111            37.0    200      2
Linha 2   2   20   200             222            74.0    400      4
Linha 3   3   30   300             333           111.0    600      6
Linha 4   4   40   400             444           148.0    800      8
Linha 5  10  100  1000            1110           370.0   2000     20

In [146]:
#cria uma series
nomes = pd.Series(['João', 'Maria', 'Leonardo'])

In [147]:
nomes

0        João
1       Maria
2    Leonardo
dtype: object

In [148]:
#faz uma funcao lambda para transformar os valores de uma series em letra maiuscula
nomes.map(lambda x: x.upper())

0        JOÃO
1       MARIA
2    LEONARDO
dtype: object

In [149]:
#tambem é possivel fazer essa mesma funcao utilizando essa funcao do proprio pandas
nomes = nomes.str.upper()

In [150]:
nomes

0        JOÃO
1       MARIA
2    LEONARDO
dtype: object

In [151]:
#cria grupos de cada elemento da coluna 'REGIÃO'
grupos = df_final.groupby(['REGIÃO'])

In [152]:
#retorna os indices das linhas/observações de cada grupo
grupos.indices

{'CENTRO OESTE': array([     0,      1,      2, ..., 103363, 103364, 103383],
       shape=(14545,)),
 'NORDESTE': array([     4,      5,      6, ..., 103385, 103387, 103391],
       shape=(35788,)),
 'NORTE': array([    13,     14,     15, ..., 103374, 103375, 103379],
       shape=(24000,)),
 'SUDESTE': array([    20,     21,     22, ..., 103377, 103386, 103390],
       shape=(16744,)),
 'SUL': array([    24,     25,     26, ..., 103376, 103388, 103389],
       shape=(12315,))}

In [153]:
#retorna os grupos obtidos pelo groupby
grupos.groups

{'CENTRO OESTE': [0, 1, 2, 3, 27, 28, 29, 30, 54, 55, 56, 57, 81, 82, 83, 84, 108, 109, 110, 111, 135, 136, 137, 138, 162, 163, 164, 165, 189, 190, 191, 192, 216, 217, 218, 219, 243, 244, 245, 246, 270, 271, 272, 273, 297, 298, 299, 300, 324, 325, 326, 327, 351, 352, 353, 354, 378, 379, 380, 381, 405, 406, 407, 408, 432, 433, 434, 435, 459, 460, 461, 462, 486, 487, 488, 489, 513, 514, 515, 516, 540, 541, 542, 543, 567, 568, 569, 570, 594, 595, 596, 597, 621, 622, 623, 624, 648, 649, 650, 651, ...], 'NORDESTE': [4, 5, 6, 7, 8, 9, 10, 11, 12, 31, 32, 33, 34, 35, 36, 37, 38, 39, 58, 59, 60, 61, 62, 63, 64, 65, 66, 85, 86, 87, 88, 89, 90, 91, 92, 93, 112, 113, 114, 115, 116, 117, 118, 119, 120, 139, 140, 141, 142, 143, 144, 145, 146, 147, 166, 167, 168, 169, 170, 171, 172, 173, 174, 193, 194, 195, 196, 197, 198, 199, 200, 201, 220, 221, 222, 223, 224, 225, 226, 227, 228, 247, 248, 249, 250, 251, 252, 253, 254, 255, 274, 275, 276, 277, 278, 279, 280, 281, 282, 301, ...], 'NORTE': [13, 14, 15, 16, 17, 18, 19, 40, 41, 42, 43, 44, 45, 46, 67, 68, 69, 70, 71, 72, 73, 94, 95, 96, 97, 98, 99, 100, 121, 122, 123, 124, 125, 126, 127, 148, 149, 150, 151, 152, 153, 154, 175, 176, 177, 178, 179, 180, 181, 202, 203, 204, 205, 206, 207, 208, 229, 230, 231, 232, 233, 234, 235, 256, 257, 258, 259, 260, 261, 262, 283, 284, 285, 286, 287, 288, 289, 310, 311, 312, 313, 314, 315, 316, 337, 338, 339, 340, 341, 342, 343, 364, 365, 366, 367, 368, 369, 370, 391, 392, ...], 'SUDESTE': [20, 21, 22, 23, 47, 48, 49, 50, 74, 75, 76, 77, 101, 102, 103, 104, 128, 129, 130, 131, 155, 156, 157, 158, 182, 183, 184, 185, 209, 210, 211, 212, 236, 237, 238, 239, 263, 264, 265, 266, 290, 291, 292, 293, 317, 318, 319, 320, 344, 345, 346, 347, 371, 372, 373, 374, 398, 399, 400, 401, 425, 426, 427, 428, 452, 453, 454, 455, 479, 480, 481, 482, 506, 507, 508, 509, 533, 534, 535, 536, 560, 561, 562, 563, 587, 588, 589, 590, 614, 615, 616, 617, 641, 642, 643, 644, 668, 669, 670, 671, ...], 'SUL': [24, 25, 26, 51, 52, 53, 78, 79, 80, 105, 106, 107, 132, 133, 134, 159, 160, 161, 186, 187, 188, 213, 214, 215, 240, 241, 242, 267, 268, 269, 294, 295, 296, 321, 322, 323, 348, 349, 350, 375, 376, 377, 402, 403, 404, 429, 430, 431, 456, 457, 458, 483, 484, 485, 510, 511, 512, 537, 538, 539, 564, 565, 566, 591, 592, 593, 618, 619, 620, 645, 646, 647, 672, 673, 674, 699, 700, 701, 726, 727, 728, 753, 754, 755, 780, 781, 782, 807, 808, 809, 834, 835, 836, 861, 862, 863, 888, 889, 890, 915, ...]}

In [154]:
#retorna um dataframe apenas com as observações do grupo 'SUDESTE'
grupos.get_group('SUDESTE').reset_index(drop = True)

C:\Users\Claudia Rodrigues\AppData\Local\Temp\ipykernel_19432\1202157450.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  grupos.get_group('SUDESTE').reset_index(drop = True)

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,2004-05-09,2004-05-15,SUDESTE,ESPIRITO SANTO,ETANOL HIDRATADO,306,R$/l,1.148,0.116,0.890,1.490,0.267,0.101,0.881,0.095,0.6259,1.1381,0.108,5,2004
1,2004-05-09,2004-05-15,SUDESTE,MINAS GERAIS,ETANOL HIDRATADO,1238,R$/l,1.205,0.120,0.920,1.875,0.389,0.100,0.816,0.123,0.3797,1.4370,0.151,5,2004
2,2004-05-09,2004-05-15,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,952,R$/l,1.098,0.154,0.740,1.890,0.312,0.140,0.786,0.173,0.3260,1.2630,0.220,5,2004
3,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,0.590,1.150,0.198,0.111,0.570,0.056,0.4271,1.4123,0.098,5,2004
4,2004-05-16,2004-05-22,SUDESTE,ESPIRITO SANTO,ETANOL HIDRATADO,307,R$/l,1.144,0.115,0.880,1.470,0.280,0.101,0.864,0.091,0.6259,1.1384,0.105,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16739,2019-06-23,2019-06-29,SUDESTE,MINAS GERAIS,GLP,508,R$/13Kg,70.032,5.518,55.000,95.000,16.271,0.079,53.761,4.956,45.2700,74.1000,0.092,6,2019
16740,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GLP,221,R$/13Kg,65.010,5.812,50.000,79.000,17.475,0.089,47.535,3.934,39.0000,58.2000,0.083,6,2019
16741,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GLP,1017,R$/13Kg,66.893,6.100,50.000,89.900,17.679,0.091,49.214,5.071,40.1900,72.0000,0.103,6,2019
16742,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GNV,124,R$/m3,3.111,0.260,2.799,3.799,0.707,0.084,2.404,0.174,2.1260,2.7909,0.072,6,2019
16743,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,2.699,3.490,0.646,0.076,2.374,0.165,2.0179,2.5093,0.070,6,2019

In [155]:
#retorna algumas estatisticas descritivas para as observações de cada grupo
grupos.describe()

             NÚMERO DE POSTOS PESQUISADOS                                      \
                                    count        mean         std  min    25%
REGIÃO
CENTRO OESTE                      14545.0  144.898453  105.699340  1.0   80.0
NORDESTE                          35788.0  124.721834  113.110808  1.0   41.0
NORTE                             24000.0   67.835958   52.961342  1.0   31.0
SUDESTE                           16744.0  726.068024  787.588935  1.0  168.0
SUL                               12315.0  366.266423  233.276285  1.0  188.0

                                   PREÇO MÉDIO REVENDA             ...   MÊS  \
                50%    75%     max               count       mean  ...   75%
REGIÃO                                                             ...
CENTRO OESTE  128.0  192.0   766.0             14545.0  12.299706  ...   9.0
NORDESTE       95.0  169.0   625.0             35788.0   9.558746  ...  10.0
NORTE          53.0   95.0   383.0             24000.0  12.633086  ...   9.0
SUDESTE       412.0  996.0  4167.0             16744.0   9.828218  ...   9.0
SUL           368.0  563.0  1416.0             12315.0  10.254388  ...   9.0

                        ANO                                                 \
               max    count         mean       std     min     25%     50%
REGIÃO
CENTRO OESTE  12.0  14545.0  2011.773599  4.409036  2004.0  2008.0  2012.0
NORDESTE      12.0  35788.0  2011.704454  4.418046  2004.0  2008.0  2012.0
NORTE         12.0  24000.0  2011.812083  4.410914  2004.0  2008.0  2012.0
SUDESTE       12.0  16744.0  2011.707895  4.395436  2004.0  2008.0  2012.0
SUL           12.0  12315.0  2011.681608  4.408312  2004.0  2008.0  2012.0


                 75%     max
REGIÃO
CENTRO OESTE  2016.0  2019.0
NORDESTE      2016.0  2019.0
NORTE         2016.0  2019.0
SUDESTE       2016.0  2019.0
SUL           2015.0  2019.0

[5 rows x 112 columns]

In [156]:
#é possivel ver o valores minimos das colunas de cada grupo
grupos.min()

,DATA INICIAL,DATA FINAL,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
REGIÃO,,,,,,,,,,,,,,,,,,,
CENTRO OESTE,2004-05-09,2004-05-15,DISTRITO FEDERAL,ETANOL HIDRATADO,1,R$/13Kg,1.097,0.0,0.87,1.099,0.031,0.0,0.737,0.0,0.38790,0.8359,0.0,1,2004
NORDESTE,2004-05-09,2004-05-15,ALAGOAS,ETANOL HIDRATADO,1,R$/13Kg,0.975,0.0,0.79,0.999,0.039,0.0,0.586,0.0,0.36320,0.5992,0.0,1,2004
NORTE,2004-05-09,2004-05-15,ACRE,ETANOL HIDRATADO,1,R$/13Kg,1.226,0.0,1.05,1.300,0.022,0.0,0.674,0.0,0.51022,0.9612,0.0,1,2004
SUDESTE,2004-05-09,2004-05-15,ESPIRITO SANTO,ETANOL HIDRATADO,1,R$/13Kg,0.766,0.0,0.59,1.099,0.001,0.0,0.506,0.0,0.32570,0.7822,0.0,1,2004
SUL,2004-05-09,2004-05-15,PARANA,ETANOL HIDRATADO,1,R$/13Kg,0.922,0.0,0.73,1.199,0.025,0.0,0.667,0.0,0.43000,0.7044,0.0,1,2004

In [157]:
#é possivel ver o valores maximos das colunas de cada grupo
grupos.max()

,DATA INICIAL,DATA FINAL,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
REGIÃO,,,,,,,,,,,,,,,,,,,
CENTRO OESTE,2019-06-23,2019-06-29,MATO GROSSO DO SUL,ÓLEO DIESEL S10,766,R$/m3,99.357,9.711,90.0,120.0,36.847,0.262,83.137,18.385,83.00,94.50,0.419,12,2019
NORDESTE,2019-06-23,2019-06-29,SERGIPE,ÓLEO DIESEL S10,625,R$/m3,79.630,10.748,75.0,90.0,31.819,0.228,59.411,13.435,55.35,89.90,0.608,12,2019
NORTE,2019-06-23,2019-06-29,TOCANTINS,ÓLEO DIESEL S10,383,R$/m3,87.270,10.675,85.0,110.0,27.989,0.168,72.428,12.428,72.39,88.00,0.368,12,2019
SUDESTE,2019-06-23,2019-06-29,SAO PAULO,ÓLEO DIESEL S10,4167,R$/m3,79.192,9.632,60.0,100.0,29.917,0.201,53.944,7.165,46.93,76.05,0.780,12,2019
SUL,2019-06-23,2019-06-29,SANTA CATARINA,ÓLEO DIESEL S10,1416,R$/m3,72.088,10.270,65.0,95.0,24.717,0.187,54.802,8.716,47.38,74.00,0.435,12,2019

In [158]:
#tambem é possivel fazer assim, sem precisar guardar o grupo em um variavel
df_final.groupby(['REGIÃO']).min()

,DATA INICIAL,DATA FINAL,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
REGIÃO,,,,,,,,,,,,,,,,,,,
CENTRO OESTE,2004-05-09,2004-05-15,DISTRITO FEDERAL,ETANOL HIDRATADO,1,R$/13Kg,1.097,0.0,0.87,1.099,0.031,0.0,0.737,0.0,0.38790,0.8359,0.0,1,2004
NORDESTE,2004-05-09,2004-05-15,ALAGOAS,ETANOL HIDRATADO,1,R$/13Kg,0.975,0.0,0.79,0.999,0.039,0.0,0.586,0.0,0.36320,0.5992,0.0,1,2004
NORTE,2004-05-09,2004-05-15,ACRE,ETANOL HIDRATADO,1,R$/13Kg,1.226,0.0,1.05,1.300,0.022,0.0,0.674,0.0,0.51022,0.9612,0.0,1,2004
SUDESTE,2004-05-09,2004-05-15,ESPIRITO SANTO,ETANOL HIDRATADO,1,R$/13Kg,0.766,0.0,0.59,1.099,0.001,0.0,0.506,0.0,0.32570,0.7822,0.0,1,2004
SUL,2004-05-09,2004-05-15,PARANA,ETANOL HIDRATADO,1,R$/13Kg,0.922,0.0,0.73,1.199,0.025,0.0,0.667,0.0,0.43000,0.7044,0.0,1,2004

In [159]:
#faz um grupo com de duas colunas
grupos = df_final.groupby(['REGIÃO', 'PRODUTO'])

In [160]:
grupos.describe()

                              NÚMERO DE POSTOS PESQUISADOS               \
                                                     count         mean
REGIÃO       PRODUTO
CENTRO OESTE ETANOL HIDRATADO                       3122.0   155.514414
             GASOLINA COMUM                         3134.0   155.447352
             GLP                                    3098.0   202.113944
             GNV                                     847.0     3.759150
             ÓLEO DIESEL                            3134.0   131.940332
             ÓLEO DIESEL S10                        1210.0    76.054545
NORDESTE     ETANOL HIDRATADO                       7046.0   154.143770
             GASOLINA COMUM                         7063.0   174.051678
             GLP                                    6410.0   127.294072
             GNV                                    5176.0    17.498068
             ÓLEO DIESEL                            7061.0   135.536185
             ÓLEO DIESEL S10                        3032.0    93.857190
NORTE        ETANOL HIDRATADO                       5177.0    47.731312
             GASOLINA COMUM                         5464.0    77.837665
             GLP                                    5327.0    91.767224
             GNV                                     243.0     1.378601
             ÓLEO DIESEL                            5465.0    68.135956
             ÓLEO DIESEL S10                        2324.0    40.495267
SUDESTE      ETANOL HIDRATADO                       3137.0  1038.720115
             GASOLINA COMUM                         3140.0  1051.909236
             GLP                                    3137.0   757.155881
             GNV                                    2841.0    81.839493
             ÓLEO DIESEL                            3140.0   771.300955
             ÓLEO DIESEL S10                        1349.0   419.743514
SUL          ETANOL HIDRATADO                       2353.0   454.889928
             GASOLINA COMUM                         2354.0   495.972387
             GLP                                    2343.0   487.431498
             GNV                                    1899.0    21.242759
             ÓLEO DIESEL                            2354.0   364.170348
             ÓLEO DIESEL S10                        1012.0   230.283597

                                                                         \
                                      std   min     25%    50%      75%
REGIÃO       PRODUTO
CENTRO OESTE ETANOL HIDRATADO   79.854557   4.0   88.00  140.0   206.75
             GASOLINA COMUM     80.157376   6.0   88.00  139.0   205.75
             GLP               147.885877   2.0  107.00  133.0   224.75
             GNV                 2.007924   1.0    2.00    3.0     5.00
             ÓLEO DIESEL        77.849589   6.0   78.00  116.0   174.00
             ÓLEO DIESEL S10    38.150505   5.0   45.25   73.0   100.00
NORDESTE     ETANOL HIDRATADO  120.286118   1.0   61.00  109.0   202.00
             GASOLINA COMUM    124.697374   3.0   95.00  124.0   227.00
             GLP                98.377845   2.0   49.00   90.0   200.00
             GNV                 9.433991   1.0   10.00   16.0    24.00
             ÓLEO DIESEL       107.442412   2.0   56.00  103.0   156.00
             ÓLEO DIESEL S10    71.693189   2.0   41.00   58.0   143.25
NORTE        ETANOL HIDRATADO   31.786616   1.0   18.00   40.0    74.00
             GASOLINA COMUM     54.775646   4.0   36.75   59.0   110.25
             GLP                65.669797   3.0   31.00   84.0   124.00
             GNV                 0.633659   1.0    1.00    1.0     2.00
             ÓLEO DIESEL        46.695648   4.0   33.00   52.0    98.00
             ÓLEO DIESEL S10    31.537397   1.0   16.00   34.0    52.00
SUDESTE      ETANOL HIDRATADO  930.107749   6.0  295.00  729.0  1323.00
             GASOLINA COMUM    927.410130  16.0  299.00  740.0  1369.25
             GLP               652.378178   4.0  223.00  411.0  1096.00
             GNV                73.698316   1.0   15.00   55.0   127.00
             ÓLEO DIESEL       684.255256  12.0  208.00  587.0   910.00
             ÓLEO DIESEL S10   383.141155   9.0  100.00  307.0   467.00
SUL          ETANOL HIDRATADO  179.365613  11.0  361.00  501.0   566.00
             GASOLINA COMUM    176.038512  15.0  377.00  519.0   612.00
             GLP               229.566227  12.0  298.00  527.0   703.00
             GNV                10.805715   1.0   13.00   20.0    29.00
             ÓLEO DIESEL       153.844415  23.0  240.00  360.0   470.00
             ÓLEO DIESEL S10    69.705482   7.0  183.75  244.0   285.00

                                      PREÇO MÉDIO REVENDA             ...  \
                                  max               count       mean  ...
REGIÃO       PRODUTO                                                  ...
CENTRO OESTE ETANOL HIDRATADO   487.0              3122.0   2.135670  ...
             GASOLINA COMUM     492.0              3134.0   3.077476  ...
             GLP                766.0              3098.0  48.176747  ...
             GNV                 10.0               847.0   1.856312  ...
             ÓLEO DIESEL        430.0              3134.0   2.481286  ...
             ÓLEO DIESEL S10    185.0              1210.0   3.294752  ...
NORDESTE     ETANOL HIDRATADO   543.0              7046.0   2.320266  ...
             GASOLINA COMUM     625.0              7063.0   3.001887  ...
             GLP                493.0              6410.0  41.966090  ...
             GNV                 51.0              5176.0   1.881722  ...
             ÓLEO DIESEL        535.0              7061.0   2.346950  ...
             ÓLEO DIESEL S10    277.0              3032.0   3.041966  ...
NORTE        ETANOL HIDRATADO   150.0              5177.0   2.511624  ...
             GASOLINA COMUM     265.0              5464.0   3.149501  ...
             GLP                383.0              5327.0  47.065572  ...
             GNV                  5.0               243.0   2.084399  ...
             ÓLEO DIESEL        240.0              5465.0   2.571048  ...
             ÓLEO DIESEL S10    146.0              2324.0   3.316231  ...
SUDESTE      ETANOL HIDRATADO  4111.0              3137.0   2.163621  ...
             GASOLINA COMUM    4167.0              3140.0   3.000565  ...
             GLP               2165.0              3137.0  42.081544  ...
             GNV                294.0              2841.0   1.716074  ...
             ÓLEO DIESEL       3237.0              3140.0   2.339699  ...
             ÓLEO DIESEL S10   1374.0              1349.0   3.056194  ...
SUL          ETANOL HIDRATADO   871.0              2353.0   2.268156  ...
             GASOLINA COMUM     924.0              2354.0   2.972569  ...
             GLP               1416.0              2343.0  43.490318  ...
             GNV                 60.0              1899.0   1.865612  ...
             ÓLEO DIESEL        712.0              2354.0   2.332293  ...
             ÓLEO DIESEL S10    368.0              1012.0   2.981775  ...

                                MÊS           ANO                         \
                                75%   max   count         mean       std
REGIÃO       PRODUTO
CENTRO OESTE ETANOL HIDRATADO  10.0  12.0  3122.0  2011.434017  4.394183
             GASOLINA COMUM    10.0  12.0  3134.0  2011.430759  4.386836
             GLP                9.0  12.0  3098.0  2011.428341  4.396427
             GNV                9.0  12.0   847.0  2010.829988  4.113278
             ÓLEO DIESEL       10.0  12.0  3134.0  2011.430759  4.386836
             ÓLEO DIESEL S10    9.0  12.0  1210.0  2015.970248  1.858726
NORDESTE     ETANOL HIDRATADO  10.0  12.0  7046.0  2011.421516  4.384794
             GASOLINA COMUM    10.0  12.0  7063.0  2011.431262  4.384914
             GLP               10.0  12.0  6410.0  2011.185335  4.499854
             GNV                9.0  12.0  5176.0  2011.103168  4.305101
             ÓLEO DIESEL       10.0  12.0  7061.0  2011.430676  4.384742
             ÓLEO DIESEL S10    9.0  12.0  3032.0  2015.759894  1.886695
NORTE        ETANOL HIDRATADO  10.0  12.0  5177.0  2011.228511  4.354524
             GASOLINA COMUM    10.0  12.0  5464.0  2011.438141  4.390784
             GLP               10.0  12.0  5327.0  2011.399850  4.416971
             GNV                9.5  12.0   243.0  2012.016461  4.600545
             ÓLEO DIESEL       10.0  12.0  5465.0  2011.441537  4.391184
             ÓLEO DIESEL S10    9.0  12.0  2324.0  2015.786145  1.875909
SUDESTE      ETANOL HIDRATADO  10.0  12.0  3137.0  2011.426522  4.382876
             GASOLINA COMUM    10.0  12.0  3140.0  2011.433121  4.386074
             GLP               10.0  12.0  3137.0  2011.435448  4.387525
             GNV                9.0  12.0  2841.0  2011.001760  4.309545
             ÓLEO DIESEL       10.0  12.0  3140.0  2011.433121  4.386074
             ÓLEO DIESEL S10    9.0  12.0  1349.0  2015.762046  1.886744
SUL          ETANOL HIDRATADO  10.0  12.0  2353.0  2011.427539  4.383987
             GASOLINA COMUM    10.0  12.0  2354.0  2011.430331  4.385148
             GLP               10.0  12.0  2343.0  2011.409731  4.385300
             GNV                9.0  12.0  1899.0  2010.783570  4.355395
             ÓLEO DIESEL       10.0  12.0  2354.0  2011.430331  4.385148
             ÓLEO DIESEL S10    9.0  12.0  1012.0  2015.755929  1.888775


                                  min     25%     50%     75%     max
REGIÃO       PRODUTO
CENTRO OESTE ETANOL HIDRATADO  2004.0  2008.0  2011.0  2015.0  2019.0
             GASOLINA COMUM    2004.0  2008.0  2011.0  2015.0  2019.0
             GLP               2004.0  2008.0  2011.0  2015.0  2019.0
             GNV               2004.0  2007.0  2011.0  2014.0  2019.0
             ÓLEO DIESEL       2004.0  2008.0  2011.0  2015.0  2019.0
             ÓLEO DIESEL S10   2013.0  2014.0  2016.0  2018.0  2019.0
NORDESTE     ETANOL HIDRATADO  2004.0  2008.0  2011.0  2015.0  2019.0
             GASOLINA COMUM    2004.0  2008.0  2011.0  2015.0  2019.0
             GLP               2004.0  2007.0  2011.0  2015.0  2019.0
             GNV               2004.0  2007.0  2011.0  2015.0  2019.0
             ÓLEO DIESEL       2004.0  2008.0  2011.0  2015.0  2019.0
             ÓLEO DIESEL S10   2012.0  2014.0  2016.0  2017.0  2019.0
NORTE        ETANOL HIDRATADO  2004.0  2007.0  2011.0  2015.0  2019.0
             GASOLINA COMUM    2004.0  2008.0  2011.0  2015.0  2019.0
             GLP               2004.0  2008.0  2011.0  2015.0  2019.0
             GNV               2005.0  2007.0  2013.0  2016.0  2019.0
             ÓLEO DIESEL       2004.0  2008.0  2011.0  2015.0  2019.0
             ÓLEO DIESEL S10   2012.0  2014.0  2016.0  2017.0  2019.0
SUDESTE      ETANOL HIDRATADO  2004.0  2008.0  2011.0  2015.0  2019.0
             GASOLINA COMUM    2004.0  2008.0  2011.0  2015.0  2019.0
             GLP               2004.0  2008.0  2011.0  2015.0  2019.0
             GNV               2004.0  2007.0  2011.0  2015.0  2019.0
             ÓLEO DIESEL       2004.0  2008.0  2011.0  2015.0  2019.0
             ÓLEO DIESEL S10   2012.0  2014.0  2016.0  2017.0  2019.0
SUL          ETANOL HIDRATADO  2004.0  2008.0  2011.0  2015.0  2019.0
             GASOLINA COMUM    2004.0  2008.0  2011.0  2015.0  2019.0
             GLP               2004.0  2008.0  2011.0  2015.0  2019.0
             GNV               2004.0  2007.0  2010.0  2015.0  2019.0
             ÓLEO DIESEL       2004.0  2008.0  2011.0  2015.0  2019.0
             ÓLEO DIESEL S10   2012.0  2014.0  2016.0  2017.0  2019.0

[30 rows x 112 columns]

In [161]:
#retorna o maximo do preço médio de revenda de cada produto de cada regiao
grupos['PREÇO MÉDIO REVENDA'].max()

REGIÃO        PRODUTO
CENTRO OESTE  ETANOL HIDRATADO     3.598
              GASOLINA COMUM       4.963
              GLP                 99.357
              GNV                  3.239
              ÓLEO DIESEL          4.162
              ÓLEO DIESEL S10      4.200
NORDESTE      ETANOL HIDRATADO     3.927
              GASOLINA COMUM       4.951
              GLP                 79.630
              GNV                  3.811
              ÓLEO DIESEL          4.010
              ÓLEO DIESEL S10      4.027
NORTE         ETANOL HIDRATADO     4.102
              GASOLINA COMUM       5.362
              GLP                 87.270
              GNV                  3.240
              ÓLEO DIESEL          4.774
              ÓLEO DIESEL S10      4.878
SUDESTE       ETANOL HIDRATADO     4.115
              GASOLINA COMUM       5.119
              GLP                 79.192
              GNV                  3.399
              ÓLEO DIESEL          3.994
              ÓLEO DIESEL S10      4.080
SUL           ETANOL HIDRATADO     4.287
              GASOLINA COMUM       4.953
              GLP                 72.088
              GNV                  3.476
              ÓLEO DIESEL          3.800
              ÓLEO DIESEL S10      3.815
Name: PREÇO MÉDIO REVENDA, dtype: float64

In [162]:
#retorna a media do preço médio de revenda de cada produto de cada regiao
grupos['PREÇO MÉDIO REVENDA'].mean()

REGIÃO        PRODUTO
CENTRO OESTE  ETANOL HIDRATADO     2.135670
              GASOLINA COMUM       3.077476
              GLP                 48.176747
              GNV                  1.856312
              ÓLEO DIESEL          2.481286
              ÓLEO DIESEL S10      3.294752
NORDESTE      ETANOL HIDRATADO     2.320266
              GASOLINA COMUM       3.001887
              GLP                 41.966090
              GNV                  1.881722
              ÓLEO DIESEL          2.346950
              ÓLEO DIESEL S10      3.041966
NORTE         ETANOL HIDRATADO     2.511624
              GASOLINA COMUM       3.149501
              GLP                 47.065572
              GNV                  2.084399
              ÓLEO DIESEL          2.571048
              ÓLEO DIESEL S10      3.316231
SUDESTE       ETANOL HIDRATADO     2.163621
              GASOLINA COMUM       3.000565
              GLP                 42.081544
              GNV                  1.716074
              ÓLEO DIESEL          2.339699
              ÓLEO DIESEL S10      3.056194
SUL           ETANOL HIDRATADO     2.268156
              GASOLINA COMUM       2.972569
              GLP                 43.490318
              GNV                  1.865612
              ÓLEO DIESEL          2.332293
              ÓLEO DIESEL S10      2.981775
Name: PREÇO MÉDIO REVENDA, dtype: float64

In [163]:
#retorna a descrição do preço médio de revenda de cada produto de cada regiao
grupos['PREÇO MÉDIO REVENDA'].describe()

                                count       mean        std     min       25%  \
REGIÃO       PRODUTO
CENTRO OESTE ETANOL HIDRATADO  3122.0   2.135670   0.561465   1.162   1.71400
             GASOLINA COMUM    3134.0   3.077476   0.615290   1.936   2.66725
             GLP               3098.0  48.176747  15.204045  28.791  37.33300
             GNV                847.0   1.856312   0.423861   1.097   1.56900
             ÓLEO DIESEL       3134.0   2.481286   0.626930   1.435   2.03300
             ÓLEO DIESEL S10   1210.0   3.294752   0.421234   2.305   2.92425
NORDESTE     ETANOL HIDRATADO  7046.0   2.320266   0.604374   1.181   1.82500
             GASOLINA COMUM    7063.0   3.001887   0.640696   1.949   2.58400
             GLP               6410.0  41.966090  12.063743  28.367  33.22875
             GNV               5176.0   1.881722   0.522996   0.975   1.59600
             ÓLEO DIESEL       7061.0   2.346950   0.605705   1.313   1.90000
             ÓLEO DIESEL S10   3032.0   3.041966   0.441550   2.130   2.60000
NORTE        ETANOL HIDRATADO  5177.0   2.511624   0.646781   1.226   2.03300
             GASOLINA COMUM    5464.0   3.149501   0.641249   1.995   2.70475
             GLP               5327.0  47.065572  14.553748  28.086  36.32950
             GNV                243.0   2.084399   0.622229   1.399   1.39900
             ÓLEO DIESEL       5465.0   2.571048   0.650994   1.450   2.08600
             ÓLEO DIESEL S10   2324.0   3.316231   0.529044   2.193   2.88300
SUDESTE      ETANOL HIDRATADO  3137.0   2.163621   0.651486   0.766   1.69200
             GASOLINA COMUM    3140.0   3.000565   0.698573   1.888   2.50200
             GLP               3137.0  42.081544  11.524738  28.026  33.63600
             GNV               2841.0   1.716074   0.462098   0.996   1.42400
             ÓLEO DIESEL       3140.0   2.339699   0.588641   1.356   1.87600
             ÓLEO DIESEL S10   1349.0   3.056194   0.418396   2.180   2.65000
SUL          ETANOL HIDRATADO  2353.0   2.268156   0.702877   0.922   1.72100
             GASOLINA COMUM    2354.0   2.972569   0.623557   1.961   2.54300
             GLP               2343.0  43.490318  11.640755  29.440  34.79250
             GNV               1899.0   1.865612   0.490703   1.168   1.49900
             ÓLEO DIESEL       2354.0   2.332293   0.527845   1.374   1.95100
             ÓLEO DIESEL S10   1012.0   2.981775   0.365470   2.151   2.66300

                                   50%       75%     max
REGIÃO       PRODUTO
CENTRO OESTE ETANOL HIDRATADO   2.0005   2.47900   3.598
             GASOLINA COMUM     2.8565   3.45975   4.963
             GLP               42.8385  55.90425  99.357
             GNV                1.7490   2.16800   3.239
             ÓLEO DIESEL        2.2465   3.01900   4.162
             ÓLEO DIESEL S10    3.3540   3.61900   4.200
NORDESTE     ETANOL HIDRATADO   2.1860   2.67000   3.927
             GASOLINA COMUM     2.7410   3.42450   4.951
             GLP               36.8550  48.35100  79.630
             GNV                1.8005   2.01125   3.811
             ÓLEO DIESEL        2.0820   2.86700   4.010
             ÓLEO DIESEL S10    3.0865   3.33800   4.027
NORTE        ETANOL HIDRATADO   2.3390   2.89600   4.102
             GASOLINA COMUM     2.9330   3.58475   5.362
             GLP               42.3110  54.07500  87.270
             GNV                2.0600   2.65000   3.240
             ÓLEO DIESEL        2.3390   3.08200   4.774
             ÓLEO DIESEL S10    3.3155   3.65300   4.878
SUDESTE      ETANOL HIDRATADO   2.0430   2.56700   4.115
             GASOLINA COMUM     2.7930   3.45150   5.119
             GLP               38.2800  49.25900  79.192
             GNV                1.6630   1.90400   3.399
             ÓLEO DIESEL        2.0825   2.82500   3.994
             ÓLEO DIESEL S10    3.0910   3.38600   4.080
SUL          ETANOL HIDRATADO   2.1130   2.60100   4.287
             GASOLINA COMUM     2.7315   3.34225   4.953
             GLP               39.9760  48.73350  72.088
             GNV                1.7020   2.15950   3.476
             ÓLEO DIESEL        2.0900   2.78450   3.800
             ÓLEO DIESEL S10    2.9910   3.25200   3.815

In [164]:
#faz uma função para retornar o minimo, maximo e a media do preço médio de revenda de cada produto de cada região
grupos['PREÇO MÉDIO REVENDA'].agg(['min', 'max','mean'])

                                  min     max       mean
REGIÃO       PRODUTO
CENTRO OESTE ETANOL HIDRATADO   1.162   3.598   2.135670
             GASOLINA COMUM     1.936   4.963   3.077476
             GLP               28.791  99.357  48.176747
             GNV                1.097   3.239   1.856312
             ÓLEO DIESEL        1.435   4.162   2.481286
             ÓLEO DIESEL S10    2.305   4.200   3.294752
NORDESTE     ETANOL HIDRATADO   1.181   3.927   2.320266
             GASOLINA COMUM     1.949   4.951   3.001887
             GLP               28.367  79.630  41.966090
             GNV                0.975   3.811   1.881722
             ÓLEO DIESEL        1.313   4.010   2.346950
             ÓLEO DIESEL S10    2.130   4.027   3.041966
NORTE        ETANOL HIDRATADO   1.226   4.102   2.511624
             GASOLINA COMUM     1.995   5.362   3.149501
             GLP               28.086  87.270  47.065572
             GNV                1.399   3.240   2.084399
             ÓLEO DIESEL        1.450   4.774   2.571048
             ÓLEO DIESEL S10    2.193   4.878   3.316231
SUDESTE      ETANOL HIDRATADO   0.766   4.115   2.163621
             GASOLINA COMUM     1.888   5.119   3.000565
             GLP               28.026  79.192  42.081544
             GNV                0.996   3.399   1.716074
             ÓLEO DIESEL        1.356   3.994   2.339699
             ÓLEO DIESEL S10    2.180   4.080   3.056194
SUL          ETANOL HIDRATADO   0.922   4.287   2.268156
             GASOLINA COMUM     1.961   4.953   2.972569
             GLP               29.440  72.088  43.490318
             GNV                1.168   3.476   1.865612
             ÓLEO DIESEL        1.374   3.800   2.332293
             ÓLEO DIESEL S10    2.151   3.815   2.981775

In [165]:
#cria um novo DataFrame
notas = pd.DataFrame({
    'nome': ['Rodrigo', 'Barbara', 'Ricardo', 'Jax'],
    'idade': [20, 21, 23, 19],
    'nota': [9.0, 8.5, 9.0, 7.6]
})

In [166]:
notas

      nome  idade  nota
0  Rodrigo     20   9.0
1  Barbara     21   8.5
2  Ricardo     23   9.0
3      Jax     19   7.6

In [167]:
#organiza por padrão de forma crescente pela coluna denominada, mudando para decrescente usando o "ascending = False"
notas.sort_values('nota', ascending = False)

      nome  idade  nota
0  Rodrigo     20   9.0
2  Ricardo     23   9.0
1  Barbara     21   8.5
3      Jax     19   7.6

In [168]:
#organiza por padrão de forma crescente pelas colunas denominadas, mudando para decrescente usando o "ascending = False"
notas.sort_values(['nota', 'nome'], ascending = [False, True], inplace = True)

In [169]:
#reseta o index e deleta a coluna que seria criada com o indice anterior
notas.reset_index(drop = True, inplace = True)

In [170]:
notas

      nome  idade  nota
0  Ricardo     23   9.0
1  Rodrigo     20   9.0
2  Barbara     21   8.5
3      Jax     19   7.6

In [171]:
df = df_final.query('ANO != 2019')

In [172]:
df

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,1.350,0.463,0.012,0.825,0.110,0.4201,0.96660,0.133,5,2004
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,1.449,0.399,0.098,0.763,0.088,0.5013,1.05000,0.115,5,2004
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,1.760,0.419,0.070,0.970,0.095,0.5614,1.16100,0.098,5,2004
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,5,2004
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,1.400,0.240,0.066,0.941,0.077,0.7441,1.03170,0.082,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99734,2018-12-30,2019-01-05,SUDESTE,RIO DE JANEIRO,GNV,122,R$/m3,3.080,0.262,2.798,3.999,0.699,0.085,2.381,0.161,2.1670,2.86970,0.068,12,2018
99735,2018-12-30,2019-01-05,NORDESTE,RIO GRANDE DO NORTE,GNV,10,R$/m3,3.465,0.060,3.370,3.590,0.759,0.017,2.706,0.000,2.7059,2.70590,0.000,12,2018
99736,2018-12-30,2019-01-05,SUL,RIO GRANDE DO SUL,GNV,16,R$/m3,3.402,0.103,3.199,3.499,1.296,0.030,2.106,0.249,1.8775,2.37240,0.118,12,2018
99737,2018-12-30,2019-01-05,SUL,SANTA CATARINA,GNV,15,R$/m3,2.944,0.124,2.790,3.199,0.670,0.042,2.274,0.283,1.8738,2.27400,0.124,12,2018
99738,2018-12-30,2019-01-05,SUDESTE,SAO PAULO,GNV,41,R$/m3,2.353,0.451,1.999,3.429,0.467,0.192,1.886,0.250,1.6400,2.33200,0.133,12,2018

In [173]:
grupos = df.groupby('PRODUTO')

In [174]:
grupos['REGIÃO'].value_counts().to_frame()

                               count
PRODUTO          REGIÃO
ETANOL HIDRATADO NORDESTE       6821
                 NORTE          5021
                 SUDESTE        3039
                 CENTRO OESTE   3022
                 SUL            2278
GASOLINA COMUM   NORDESTE       6838
                 NORTE          5289
                 SUDESTE        3040
                 CENTRO OESTE   3034
                 SUL            2279
GLP              NORDESTE       6185
                 NORTE          5152
                 SUDESTE        3037
                 CENTRO OESTE   2998
                 SUL            2268
GNV              NORDESTE       5030
                 SUDESTE        2772
                 SUL            1847
                 CENTRO OESTE    825
                 NORTE           233
ÓLEO DIESEL      NORDESTE       6836
                 NORTE          5290
                 SUDESTE        3040
                 CENTRO OESTE   3034
                 SUL            2279
ÓLEO DIESEL S10  NORDESTE       2807
                 NORTE          2149
                 SUDESTE        1249
                 CENTRO OESTE   1110
                 SUL             937

In [175]:
selecao1 = (df['ESTADO'] == "SAO PAULO") & (df['PRODUTO'] == "GASOLINA COMUM")

In [176]:
df[selecao1]

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
12003,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,GASOLINA COMUM,4107,R$/l,1.891,0.101,1.570,2.399,0.235,0.053,1.656,0.064,1.38,1.9440,0.039,5,2004
12030,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,GASOLINA COMUM,4133,R$/l,1.888,0.101,1.540,2.220,0.233,0.053,1.655,0.063,1.38,1.9319,0.038,5,2004
12057,2004-05-23,2004-05-29,SUDESTE,SAO PAULO,GASOLINA COMUM,4139,R$/l,1.894,0.095,1.570,2.399,0.234,0.050,1.660,0.065,1.39,1.9291,0.039,5,2004
12084,2004-05-30,2004-06-05,SUDESTE,SAO PAULO,GASOLINA COMUM,4139,R$/l,1.912,0.094,1.529,2.199,0.235,0.049,1.677,0.068,1.39,1.9733,0.041,5,2004
12111,2004-06-06,2004-06-12,SUDESTE,SAO PAULO,GASOLINA COMUM,4138,R$/l,1.919,0.088,1.580,2.399,0.231,0.046,1.688,0.063,1.41,2.0946,0.037,6,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99122,2018-12-02,2018-12-08,SUDESTE,SAO PAULO,GASOLINA COMUM,1648,R$/l,4.187,0.213,3.699,5.299,0.565,0.051,3.622,0.117,3.34,4.0849,0.032,12,2018
99266,2018-12-09,2018-12-15,SUDESTE,SAO PAULO,GASOLINA COMUM,1649,R$/l,4.148,0.212,3.669,4.999,0.533,0.051,3.615,0.119,3.34,4.0849,0.033,12,2018
99410,2018-12-16,2018-12-22,SUDESTE,SAO PAULO,GASOLINA COMUM,1637,R$/l,4.129,0.201,3.699,5.099,0.490,0.049,3.639,0.110,3.35,3.9892,0.030,12,2018
99553,2018-12-23,2018-12-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1641,R$/l,4.129,0.201,3.699,4.999,0.484,0.049,3.645,0.107,3.35,3.9892,0.029,12,2018
99698,2018-12-30,2019-01-05,SUDESTE,SAO PAULO,GASOLINA COMUM,1643,R$/l,4.113,0.201,3.599,4.999,0.503,0.049,3.610,0.100,3.35,3.9585,0.028,12,2018

In [178]:
selecao2 = (df[selecao1]) & (df['ANO'] == 2018)

TypeError: unsupported operand type(s) for &: 'float' and 'bool'

In [ ]:
df[selecao2]