In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('./datasets/GasPricesinBrazil_2004-2019.csv', sep=';')

In [5]:
df.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106823 entries, 0 to 106822
Data columns (total 21 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Unnamed: 0                     106823 non-null  int64
 1   DATA INICIAL                   106823 non-null  object
 2   DATA FINAL                     106823 non-null  object
 3   REGIÃO                         106823 non-null  object
 4   ESTADO                         106823 non-null  object
 5   PRODUTO                        106823 non-null  object
 6   NÚMERO DE POSTOS PESQUISADOS   106823 non-null  int64
 7   UNIDADE DE MEDIDA              106823 non-null  object
 8   PREÇO MÉDIO REVENDA            106823 non-null  float64
 9   DESVIO PADRÃO REVENDA          106823 non-null  float64
 10  PREÇO MÍNIMO REVENDA           106823 non-null  float64
 11  PREÇO MÁXIMO REVENDA           106823 non-null  float64
 12  MARGEM MÉDIA REVENDA           106823 non-null  object
 13  COEF DE VARIAÇÃO REVENDA       106823 non-null  float64
 14  PREÇO MÉDIO DISTRIBUIÇÃO       106823 non-null  object
 15  DESVIO PADRÃO DISTRIBUIÇÃO     106823 non-null  object
 16  PREÇO MÍNIMO DISTRIBUIÇÃO      106823 non-null  object
 17  PREÇO MÁXIMO DISTRIBUIÇÃO      106823 non-null  object
 18  COEF DE VARIAÇÃO DISTRIBUIÇÃO  106823 non-null  object
 19  MÊS                            106823 non-null  int64
 20  ANO                            106823 non-null  int64
dtypes: float64(5), int64(4), object(12)
memory usage: 17.1+ MB

In [10]:
def limpeza_dados(df):
    df.columns = (df.columns
                  .str.strip()
                  .str.upper()
                  .str.replace(' ', '_')
    )

    colunas_str = ['REGIÃO', 'ESTADO', 'PRODUTO']
    colunas_num = ['MARGEM_MÉDIA_REVENDA', 'PREÇO_MÉDIO_DISTRIBUIÇÃO', 'DESVIO_PADRÃO_DISTRIBUIÇÃO', 'PREÇO_MÍNIMO_DISTRIBUIÇÃO', 'PREÇO_MÁXIMO_DISTRIBUIÇÃO', 'COEF_DE_VARIAÇÃO_DISTRIBUIÇÃO']
    for coluna in colunas_str:
        df[coluna] = df[coluna].str.strip().str.upper()

    for coluna in colunas_num:
        df[coluna] = pd.to_numeric(df[coluna], errors = 'coerce')

    for coluna in ['DATA_INICIAL', 'DATA_FINAL']:
        df[coluna] = pd.to_datetime(df[coluna], errors = 'coerce')

    df = df.drop_duplicates()

    return df

In [11]:
limpeza_dados(df)

,UNNAMED:_0,DATA_INICIAL,DATA_FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO_DE_POSTOS_PESQUISADOS,UNIDADE_DE_MEDIDA,PREÇO_MÉDIO_REVENDA,DESVIO_PADRÃO_REVENDA,...,PREÇO_MÁXIMO_REVENDA,MARGEM_MÉDIA_REVENDA,COEF_DE_VARIAÇÃO_REVENDA,PREÇO_MÉDIO_DISTRIBUIÇÃO,DESVIO_PADRÃO_DISTRIBUIÇÃO,PREÇO_MÍNIMO_DISTRIBUIÇÃO,PREÇO_MÁXIMO_DISTRIBUIÇÃO,COEF_DE_VARIAÇÃO_DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.110,0.4201,0.96660,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05000,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.970,0.095,0.5614,1.16100,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.240,0.066,0.941,0.077,0.7441,1.03170,0.082,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,...,3.690,0.818,0.018,2.756,0.000,2.7560,2.75600,0.000,6,2019
106819,106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,...,3.789,0.950,0.038,2.451,0.402,1.9842,2.86610,0.164,6,2019
106820,106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,...,3.499,0.914,0.065,1.998,0.000,1.9981,1.99810,0.000,6,2019
106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,3.490,0.646,0.076,2.374,0.165,2.0179,2.50930,0.070,6,2019
106822,106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,0.005,...,3.699,1.179,0.001,2.518,0.000,2.5175,2.51750,0.000,6,2019

In [13]:
del df['UNNAMED:_0']

In [14]:
df.head()

,DATA_INICIAL,DATA_FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO_DE_POSTOS_PESQUISADOS,UNIDADE_DE_MEDIDA,PREÇO_MÉDIO_REVENDA,DESVIO_PADRÃO_REVENDA,PREÇO_MÍNIMO_REVENDA,PREÇO_MÁXIMO_REVENDA,MARGEM_MÉDIA_REVENDA,COEF_DE_VARIAÇÃO_REVENDA,PREÇO_MÉDIO_DISTRIBUIÇÃO,DESVIO_PADRÃO_DISTRIBUIÇÃO,PREÇO_MÍNIMO_DISTRIBUIÇÃO,PREÇO_MÁXIMO_DISTRIBUIÇÃO,COEF_DE_VARIAÇÃO_DISTRIBUIÇÃO,MÊS,ANO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.110,0.4201,0.96660,0.133,5,2004
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05000,0.115,5,2004
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,1.760,0.419,0.070,0.970,0.095,0.5614,1.16100,0.098,5,2004
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,5,2004
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,1.400,0.240,0.066,0.941,0.077,0.7441,1.03170,0.082,5,2004

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106823 entries, 0 to 106822
Data columns (total 20 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   DATA_INICIAL                   106823 non-null  datetime64[ns]
 1   DATA_FINAL                     106823 non-null  datetime64[ns]
 2   REGIÃO                         106823 non-null  object
 3   ESTADO                         106823 non-null  object
 4   PRODUTO                        106823 non-null  object
 5   NÚMERO_DE_POSTOS_PESQUISADOS   106823 non-null  int64
 6   UNIDADE_DE_MEDIDA              106823 non-null  object
 7   PREÇO_MÉDIO_REVENDA            106823 non-null  float64
 8   DESVIO_PADRÃO_REVENDA          106823 non-null  float64
 9   PREÇO_MÍNIMO_REVENDA           106823 non-null  float64
 10  PREÇO_MÁXIMO_REVENDA           106823 non-null  float64
 11  MARGEM_MÉDIA_REVENDA           103392 non-null  float64
 12  COEF_DE_VARIAÇÃO_REVENDA       106823 non-null  float64
 13  PREÇO_MÉDIO_DISTRIBUIÇÃO       103423 non-null  float64
 14  DESVIO_PADRÃO_DISTRIBUIÇÃO     103423 non-null  float64
 15  PREÇO_MÍNIMO_DISTRIBUIÇÃO      103423 non-null  float64
 16  PREÇO_MÁXIMO_DISTRIBUIÇÃO      103423 non-null  float64
 17  COEF_DE_VARIAÇÃO_DISTRIBUIÇÃO  103423 non-null  float64
 18  MÊS                            106823 non-null  int64
 19  ANO                            106823 non-null  int64
dtypes: datetime64[ns](2), float64(11), int64(3), object(4)
memory usage: 16.3+ MB

In [19]:
df['MÉDIA_PREÇO_MÉDIO_REVENDA'] = df.groupby(['PRODUTO', 'ANO'])['PREÇO_MÉDIO_REVENDA'].transform('mean')

In [20]:
df.head()

,DATA_INICIAL,DATA_FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO_DE_POSTOS_PESQUISADOS,UNIDADE_DE_MEDIDA,PREÇO_MÉDIO_REVENDA,DESVIO_PADRÃO_REVENDA,PREÇO_MÍNIMO_REVENDA,...,MARGEM_MÉDIA_REVENDA,COEF_DE_VARIAÇÃO_REVENDA,PREÇO_MÉDIO_DISTRIBUIÇÃO,DESVIO_PADRÃO_DISTRIBUIÇÃO,PREÇO_MÍNIMO_DISTRIBUIÇÃO,PREÇO_MÁXIMO_DISTRIBUIÇÃO,COEF_DE_VARIAÇÃO_DISTRIBUIÇÃO,MÊS,ANO,MÉDIA_PREÇO_MÉDIO_REVENDA
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,...,0.463,0.012,0.825,0.110,0.4201,0.96660,0.133,5,2004,1.528289
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,...,0.399,0.098,0.763,0.088,0.5013,1.05000,0.115,5,2004,1.528289
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,...,0.419,0.070,0.970,0.095,0.5614,1.16100,0.098,5,2004,1.528289
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,...,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,5,2004,1.528289
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,...,0.240,0.066,0.941,0.077,0.7441,1.03170,0.082,5,2004,1.528289

In [22]:
df.groupby(['ESTADO', 'PRODUTO'])['PREÇO_MÉDIO_REVENDA'].agg(['min','max','mean'])

                               min     max       mean
ESTADO    PRODUTO
ACRE      ETANOL HIDRATADO   1.795   4.102   2.682592
          GASOLINA COMUM     2.388   5.362   3.413656
          GLP               35.406  81.072  49.496222
          GNV                2.280   2.350   2.322000
          ÓLEO DIESEL        1.713   4.774   2.880958
...                            ...     ...        ...
TOCANTINS GASOLINA COMUM     2.089   5.076   3.166631
          GLP               32.406  87.270  49.950201
          GNV                2.110   3.499   2.972833
          ÓLEO DIESEL        1.450   3.839   2.359983
          ÓLEO DIESEL S10    2.172   3.876   3.018544

[161 rows x 3 columns]

In [24]:
df.to_parquet('./datasets/GasPricesinBrazil_2004-2019-tratados.parquet')