In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('./datasets/GasPricesinBrazil_2004-2019.csv', sep = ";")

In [4]:
df.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004

In [5]:
def limpar_dados(df):
    df.columns = (df.columns
        .str.strip()
        .str.upper()
        .str.replace(' ', '_')
    )

    colunas_numericas = ['MARGEM_MÉDIA_REVENDA', 'PREÇO_MÉDIO_DISTRIBUIÇÃO', 'DESVIO_PADRÃO_DISTRIBUIÇÃO', 'PREÇO_MÍNIMO_DISTRIBUIÇÃO', 'PREÇO_MÁXIMO_DISTRIBUIÇÃO', 'COEF_DE_VARIAÇÃO_DISTRIBUIÇÃO']

    for coluna in colunas_numericas:
        df[coluna] = pd.to_numeric(df[coluna], errors = 'coerce')

    for colunas_datas in ['DATA_INICIAL', 'DATA_FINAL']:
        df[colunas_datas] = pd.to_datetime(df[colunas_datas], errors='coerce')

    df = df.dropna(subset=colunas_numericas)

    df= df.drop_duplicates()

    return df

In [6]:
limpar_dados(df)

,UNNAMED:_0,DATA_INICIAL,DATA_FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO_DE_POSTOS_PESQUISADOS,UNIDADE_DE_MEDIDA,PREÇO_MÉDIO_REVENDA,DESVIO_PADRÃO_REVENDA,...,PREÇO_MÁXIMO_REVENDA,MARGEM_MÉDIA_REVENDA,COEF_DE_VARIAÇÃO_REVENDA,PREÇO_MÉDIO_DISTRIBUIÇÃO,DESVIO_PADRÃO_DISTRIBUIÇÃO,PREÇO_MÍNIMO_DISTRIBUIÇÃO,PREÇO_MÁXIMO_DISTRIBUIÇÃO,COEF_DE_VARIAÇÃO_DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.110,0.4201,0.96660,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05000,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.970,0.095,0.5614,1.16100,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.240,0.066,0.941,0.077,0.7441,1.03170,0.082,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,...,3.690,0.818,0.018,2.756,0.000,2.7560,2.75600,0.000,6,2019
106819,106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,...,3.789,0.950,0.038,2.451,0.402,1.9842,2.86610,0.164,6,2019
106820,106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,...,3.499,0.914,0.065,1.998,0.000,1.9981,1.99810,0.000,6,2019
106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,3.490,0.646,0.076,2.374,0.165,2.0179,2.50930,0.070,6,2019
106822,106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,0.005,...,3.699,1.179,0.001,2.518,0.000,2.5175,2.51750,0.000,6,2019

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106823 entries, 0 to 106822
Data columns (total 21 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   UNNAMED:_0                     106823 non-null  int64
 1   DATA_INICIAL                   106823 non-null  datetime64[ns]
 2   DATA_FINAL                     106823 non-null  datetime64[ns]
 3   REGIÃO                         106823 non-null  object
 4   ESTADO                         106823 non-null  object
 5   PRODUTO                        106823 non-null  object
 6   NÚMERO_DE_POSTOS_PESQUISADOS   106823 non-null  int64
 7   UNIDADE_DE_MEDIDA              106823 non-null  object
 8   PREÇO_MÉDIO_REVENDA            106823 non-null  float64
 9   DESVIO_PADRÃO_REVENDA          106823 non-null  float64
 10  PREÇO_MÍNIMO_REVENDA           106823 non-null  float64
 11  PREÇO_MÁXIMO_REVENDA           106823 non-null  float64
 12  MARGEM_MÉDIA_REVENDA           103392 non-null  float64
 13  COEF_DE_VARIAÇÃO_REVENDA       106823 non-null  float64
 14  PREÇO_MÉDIO_DISTRIBUIÇÃO       103423 non-null  float64
 15  DESVIO_PADRÃO_DISTRIBUIÇÃO     103423 non-null  float64
 16  PREÇO_MÍNIMO_DISTRIBUIÇÃO      103423 non-null  float64
 17  PREÇO_MÁXIMO_DISTRIBUIÇÃO      103423 non-null  float64
 18  COEF_DE_VARIAÇÃO_DISTRIBUIÇÃO  103423 non-null  float64
 19  MÊS                            106823 non-null  int64
 20  ANO                            106823 non-null  int64
dtypes: datetime64[ns](2), float64(11), int64(4), object(4)
memory usage: 17.1+ MB

In [8]:
df['AMPLITUDE_PRECO'] = df['PREÇO_MÁXIMO_REVENDA'] - df['PREÇO_MÍNIMO_REVENDA']

In [9]:
condicao = [
    df['PREÇO_MÉDIO_REVENDA'] < 5,
    df['PREÇO_MÉDIO_REVENDA'] > 7
]

valores =[
    'BAIXO',
    'ALTO'
]

df['CATEGORIA_PRECO'] = np.select(condicao, valores, default ='MEDIO')

In [10]:
df['CATEGORIA_PRECO'].value_counts()

CATEGORIA_PRECO
BAIXO    85581
ALTO     21186
MEDIO       56
Name: count, dtype: int64

In [11]:
df_rj = df[df['ESTADO'] == "RIO DE JANEIRO"]

In [12]:
df_rj.groupby('PRODUTO')['PREÇO_MÉDIO_REVENDA'].mean()

PRODUTO
ETANOL HIDRATADO     2.326825
GASOLINA COMUM       3.122638
GLP                 40.931363
GNV                  1.726745
ÓLEO DIESEL          2.345963
ÓLEO DIESEL S10      3.113778
Name: PREÇO_MÉDIO_REVENDA, dtype: float64

In [13]:
df_rj.groupby('PRODUTO')['PREÇO_MÉDIO_REVENDA'].max().sort_values(ascending=False).head()

PRODUTO
GLP                 67.679
GASOLINA COMUM       5.119
ETANOL HIDRATADO     4.115
ÓLEO DIESEL S10      4.080
ÓLEO DIESEL          3.994
Name: PREÇO_MÉDIO_REVENDA, dtype: float64

In [14]:
del df['UNNAMED:_0']

In [15]:
df.head()

,DATA_INICIAL,DATA_FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO_DE_POSTOS_PESQUISADOS,UNIDADE_DE_MEDIDA,PREÇO_MÉDIO_REVENDA,DESVIO_PADRÃO_REVENDA,PREÇO_MÍNIMO_REVENDA,...,COEF_DE_VARIAÇÃO_REVENDA,PREÇO_MÉDIO_DISTRIBUIÇÃO,DESVIO_PADRÃO_DISTRIBUIÇÃO,PREÇO_MÍNIMO_DISTRIBUIÇÃO,PREÇO_MÁXIMO_DISTRIBUIÇÃO,COEF_DE_VARIAÇÃO_DISTRIBUIÇÃO,MÊS,ANO,AMPLITUDE_PRECO,CATEGORIA_PRECO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,...,0.012,0.825,0.110,0.4201,0.96660,0.133,5,2004,0.160,BAIXO
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,...,0.098,0.763,0.088,0.5013,1.05000,0.115,5,2004,0.559,BAIXO
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,...,0.070,0.970,0.095,0.5614,1.16100,0.098,5,2004,0.580,BAIXO
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,...,0.055,0.830,0.119,0.5991,1.22242,0.143,5,2004,0.419,BAIXO
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,...,0.066,0.941,0.077,0.7441,1.03170,0.082,5,2004,0.350,BAIXO

In [16]:
df.loc[:, ['ESTADO', 'PRODUTO', 'PREÇO_MÉDIO_REVENDA']]

                     ESTADO           PRODUTO  PREÇO_MÉDIO_REVENDA
0          DISTRITO FEDERAL  ETANOL HIDRATADO                1.288
1                     GOIAS  ETANOL HIDRATADO                1.162
2               MATO GROSSO  ETANOL HIDRATADO                1.389
3        MATO GROSSO DO SUL  ETANOL HIDRATADO                1.262
4                   ALAGOAS  ETANOL HIDRATADO                1.181
...                     ...               ...                  ...
106818  RIO GRANDE DO NORTE               GNV                3.574
106819    RIO GRANDE DO SUL               GNV                3.401
106820       SANTA CATARINA               GNV                2.912
106821            SAO PAULO               GNV                3.020
106822              SERGIPE               GNV                3.697

[106823 rows x 3 columns]

In [17]:
df.loc[df['ESTADO'] == "RIO DE JANEIRO", ['PRODUTO', 'PREÇO_MÉDIO_REVENDA']]

                 PRODUTO  PREÇO_MÉDIO_REVENDA
22      ETANOL HIDRATADO                1.098
49      ETANOL HIDRATADO                1.092
76      ETANOL HIDRATADO                1.103
103     ETANOL HIDRATADO                1.149
130     ETANOL HIDRATADO                1.165
...                  ...                  ...
106718       ÓLEO DIESEL                3.569
106745   ÓLEO DIESEL S10                3.697
106772    GASOLINA COMUM                4.928
106799               GLP               65.010
106817               GNV                3.111

[4263 rows x 2 columns]

In [18]:
df.loc[df['PREÇO_MÉDIO_REVENDA'] > 7,'CATEGORIA_PRECO'] = 'MUITO ALTO'

In [19]:
df[df['CATEGORIA_PRECO'] == 'MUITO ALTO']

,DATA_INICIAL,DATA_FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO_DE_POSTOS_PESQUISADOS,UNIDADE_DE_MEDIDA,PREÇO_MÉDIO_REVENDA,DESVIO_PADRÃO_REVENDA,PREÇO_MÍNIMO_REVENDA,...,COEF_DE_VARIAÇÃO_REVENDA,PREÇO_MÉDIO_DISTRIBUIÇÃO,DESVIO_PADRÃO_DISTRIBUIÇÃO,PREÇO_MÍNIMO_DISTRIBUIÇÃO,PREÇO_MÁXIMO_DISTRIBUIÇÃO,COEF_DE_VARIAÇÃO_DISTRIBUIÇÃO,MÊS,ANO,AMPLITUDE_PRECO,CATEGORIA_PRECO
24132,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,GLP,44,R$/13Kg,33.989,0.803,32.0,...,0.024,27.165,3.062,25.0000,29.33,0.113,5,2004,4.0,MUITO ALTO
24133,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,GLP,372,R$/13Kg,30.335,1.841,27.0,...,0.061,25.007,1.756,19.4983,29.00,0.070,5,2004,9.0,MUITO ALTO
24134,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,GLP,97,R$/13Kg,38.568,2.045,33.0,...,0.053,32.855,2.296,27.7500,38.00,0.070,5,2004,11.0,MUITO ALTO
24135,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,GLP,109,R$/13Kg,33.388,2.308,29.0,...,0.069,28.803,1.764,24.0000,33.00,0.061,5,2004,10.0,MUITO ALTO
24136,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,GLP,22,R$/13Kg,32.391,1.357,27.9,...,0.042,24.750,0.354,24.5000,25.00,0.014,5,2004,5.1,MUITO ALTO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106803,2019-06-23,2019-06-29,NORTE,RORAIMA,GLP,24,R$/13Kg,84.500,0.590,83.0,...,0.007,72.390,0.000,72.3900,72.39,0.000,6,2019,2.0,MUITO ALTO
106804,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GLP,100,R$/13Kg,69.977,5.119,55.0,...,0.073,51.702,3.339,45.8000,61.50,0.065,6,2019,30.0,MUITO ALTO
106805,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GLP,1017,R$/13Kg,66.893,6.100,50.0,...,0.091,49.214,5.071,40.1900,72.00,0.103,6,2019,39.9,MUITO ALTO
106806,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GLP,26,R$/13Kg,68.128,3.421,60.0,...,0.050,54.078,3.941,46.1900,57.43,0.073,6,2019,15.0,MUITO ALTO
106807,2019-06-23,2019-06-29,NORTE,TOCANTINS,GLP,88,R$/13Kg,80.316,4.509,70.0,...,0.056,57.050,6.906,49.0000,70.00,0.121,6,2019,20.0,MUITO ALTO

In [20]:
df.iloc[:10, :5]

  DATA_INICIAL DATA_FINAL        REGIÃO              ESTADO           PRODUTO
0   2004-05-09 2004-05-15  CENTRO OESTE    DISTRITO FEDERAL  ETANOL HIDRATADO
1   2004-05-09 2004-05-15  CENTRO OESTE               GOIAS  ETANOL HIDRATADO
2   2004-05-09 2004-05-15  CENTRO OESTE         MATO GROSSO  ETANOL HIDRATADO
3   2004-05-09 2004-05-15  CENTRO OESTE  MATO GROSSO DO SUL  ETANOL HIDRATADO
4   2004-05-09 2004-05-15      NORDESTE             ALAGOAS  ETANOL HIDRATADO
5   2004-05-09 2004-05-15      NORDESTE               BAHIA  ETANOL HIDRATADO
6   2004-05-09 2004-05-15      NORDESTE               CEARA  ETANOL HIDRATADO
7   2004-05-09 2004-05-15      NORDESTE            MARANHAO  ETANOL HIDRATADO
8   2004-05-09 2004-05-15      NORDESTE             PARAIBA  ETANOL HIDRATADO
9   2004-05-09 2004-05-15      NORDESTE          PERNAMBUCO  ETANOL HIDRATADO

In [21]:
def classificar_preco(preco):
    if preco < 5:
        return 'BAIXO'
    elif preco > 7:
        return 'ALTO'
    else:
        return 'MEDIO'

In [22]:
df['CATEGORIA_PRECO_2'] = df['PREÇO_MÉDIO_REVENDA'].apply(classificar_preco)

In [23]:
df['CATEGORIA_PRECO_2'].unique()

array(['BAIXO', 'ALTO', 'MEDIO'], dtype=object)

In [24]:
def classificar_produto(produto):
    if 'GASOLINA' in produto:
        return "GASOLINA"
    elif 'ETANOL' in produto:
        return "ETANOL"
    elif 'DIESEL' in produto:
        return "DIESEL"
    else:
        return "OUTRO"

In [25]:
df['TIPO_COMBUSTIVEL'] = df['PRODUTO'].apply(classificar_produto)

In [26]:
df[df['PRODUTO'] == "GLP"]

,DATA_INICIAL,DATA_FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO_DE_POSTOS_PESQUISADOS,UNIDADE_DE_MEDIDA,PREÇO_MÉDIO_REVENDA,DESVIO_PADRÃO_REVENDA,PREÇO_MÍNIMO_REVENDA,...,DESVIO_PADRÃO_DISTRIBUIÇÃO,PREÇO_MÍNIMO_DISTRIBUIÇÃO,PREÇO_MÁXIMO_DISTRIBUIÇÃO,COEF_DE_VARIAÇÃO_DISTRIBUIÇÃO,MÊS,ANO,AMPLITUDE_PRECO,CATEGORIA_PRECO,CATEGORIA_PRECO_2,TIPO_COMBUSTIVEL
24132,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,GLP,44,R$/13Kg,33.989,0.803,32.0,...,3.062,25.0000,29.33,0.113,5,2004,4.0,MUITO ALTO,ALTO,OUTRO
24133,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,GLP,372,R$/13Kg,30.335,1.841,27.0,...,1.756,19.4983,29.00,0.070,5,2004,9.0,MUITO ALTO,ALTO,OUTRO
24134,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,GLP,97,R$/13Kg,38.568,2.045,33.0,...,2.296,27.7500,38.00,0.070,5,2004,11.0,MUITO ALTO,ALTO,OUTRO
24135,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,GLP,109,R$/13Kg,33.388,2.308,29.0,...,1.764,24.0000,33.00,0.061,5,2004,10.0,MUITO ALTO,ALTO,OUTRO
24136,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,GLP,22,R$/13Kg,32.391,1.357,27.9,...,0.354,24.5000,25.00,0.014,5,2004,5.1,MUITO ALTO,ALTO,OUTRO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106803,2019-06-23,2019-06-29,NORTE,RORAIMA,GLP,24,R$/13Kg,84.500,0.590,83.0,...,0.000,72.3900,72.39,0.000,6,2019,2.0,MUITO ALTO,ALTO,OUTRO
106804,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GLP,100,R$/13Kg,69.977,5.119,55.0,...,3.339,45.8000,61.50,0.065,6,2019,30.0,MUITO ALTO,ALTO,OUTRO
106805,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GLP,1017,R$/13Kg,66.893,6.100,50.0,...,5.071,40.1900,72.00,0.103,6,2019,39.9,MUITO ALTO,ALTO,OUTRO
106806,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GLP,26,R$/13Kg,68.128,3.421,60.0,...,3.941,46.1900,57.43,0.073,6,2019,15.0,MUITO ALTO,ALTO,OUTRO
106807,2019-06-23,2019-06-29,NORTE,TOCANTINS,GLP,88,R$/13Kg,80.316,4.509,70.0,...,6.906,49.0000,70.00,0.121,6,2019,20.0,MUITO ALTO,ALTO,OUTRO

In [27]:
def classificar_preco_detalhado(preco):
    if preco < 5:
        return 'BARATO'
    elif preco >= 5 and preco <= 7:
        return 'NORMAL'
    elif preco > 7 and preco <= 10:
        return 'CARO'
    else:
        return 'MUITO CARO'

In [28]:
df['CLASSIFICACAO'] = df['PREÇO_MÉDIO_REVENDA'].apply(classificar_preco_detalhado)

In [29]:
df['CLASSIFICACAO'].value_counts()

CLASSIFICACAO
BARATO        85581
MUITO CARO    21186
NORMAL           56
Name: count, dtype: int64

In [30]:
df.groupby('ESTADO')['PREÇO_MÉDIO_REVENDA'].agg(['min', 'max', 'mean', 'count'])

                       min     max       mean  count
ESTADO
ACRE                 1.713  81.072  13.544876   3480
ALAGOAS              1.074  69.185   9.622259   4250
AMAPA                1.504  80.081  13.435394   3403
AMAZONAS             1.399  73.916  10.368645   3889
BAHIA                1.079  63.577   9.406878   4263
CEARA                1.182  75.317  10.226637   4263
DISTRITO FEDERAL     1.216  73.929  12.197823   3483
ESPIRITO SANTO       1.135  65.438   9.534348   4260
GOIAS                1.162  74.320  11.309635   3663
MARANHAO             1.290  75.972  11.992578   3499
MATO GROSSO          1.204  99.357  12.861120   4037
MATO GROSSO DO SUL   1.097  77.911  11.045832   4246
MINAS GERAIS         1.110  79.192  10.243751   4261
PARA                 1.476  77.192  12.292955   3497
PARAIBA              1.149  68.410   9.464513   4263
PARANA               0.922  70.631   9.845426   4251
PERNAMBUCO           0.999  66.993   9.352028   4262
PIAUI                1.339  73.125  11.739773   3548
RIO DE JANEIRO       1.036  67.679   9.537528   4263
RIO GRANDE DO NORTE  0.975  72.233   9.832325   4262
RIO GRANDE DO SUL    1.168  70.729  10.061393   4263
RONDONIA             1.219  79.352  12.808276   3479
RORAIMA              1.300  85.375  13.209867   3471
SANTA CATARINA       1.197  72.088  10.115375   4262
SAO PAULO            0.766  70.800   9.485222   4263
SERGIPE              1.155  79.630   9.857946   4259
TOCANTINS            1.226  87.270  13.326909   3483

In [31]:
df.groupby(['ESTADO', 'PRODUTO'])['PREÇO_MÉDIO_REVENDA'].agg(['min', 'max', 'mean'])

                               min     max       mean
ESTADO    PRODUTO
ACRE      ETANOL HIDRATADO   1.795   4.102   2.682592
          GASOLINA COMUM     2.388   5.362   3.413656
          GLP               35.406  81.072  49.496222
          GNV                2.280   2.350   2.322000
          ÓLEO DIESEL        1.713   4.774   2.880958
...                            ...     ...        ...
TOCANTINS GASOLINA COMUM     2.089   5.076   3.166631
          GLP               32.406  87.270  49.950201
          GNV                2.110   3.499   2.972833
          ÓLEO DIESEL        1.450   3.839   2.359983
          ÓLEO DIESEL S10    2.172   3.876   3.018544

[161 rows x 3 columns]

In [32]:
df.groupby(['ESTADO', 'PRODUTO'])['PREÇO_MÉDIO_REVENDA'].mean().sort_values(ascending=False).head(10)

ESTADO              PRODUTO
MATO GROSSO         GLP        55.505054
TOCANTINS           GLP        49.950201
ACRE                GLP        49.496222
AMAPA               GLP        48.909337
MATO GROSSO DO SUL  GLP        48.686359
RORAIMA             GLP        48.621775
RONDONIA            GLP        47.109462
PARA                GLP        45.076306
DISTRITO FEDERAL    GLP        45.019664
MINAS GERAIS        GLP        44.912368
Name: PREÇO_MÉDIO_REVENDA, dtype: float64

In [33]:
clientes = pd.DataFrame({
    'id_cliente': [1, 2, 3, 4],
    'nome': ['Ana', 'Bruno', 'Carlos', 'Daniel']
})

pedidos = pd.DataFrame({
    'id_cliente': [1, 2, 2, 4],
    'produto': ['Notebook', 'Mouse', 'Teclado', 'Monitor'],
    'valor': [3500, 100, 150, 1200]
})

In [34]:
pd.merge(clientes, pedidos, on='id_cliente', how='outer')

   id_cliente    nome   produto   valor
0           1     Ana  Notebook  3500.0
1           2   Bruno     Mouse   100.0
2           2   Bruno   Teclado   150.0
3           3  Carlos       NaN     NaN
4           4  Daniel   Monitor  1200.0

In [35]:
clientes2 = pd.DataFrame({
    'id_cliente': [1, 2, 3],
    'nome': ['Ana', 'Bruno', 'Carlos']
})

pedidos2 = pd.DataFrame({
    'cliente_id': [1, 2, 2],
    'produto': ['Notebook', 'Mouse', 'Teclado'],
    'valor': [3500, 100, 150]
})

In [36]:
pd.merge(clientes2, pedidos2, left_on='id_cliente', right_on='cliente_id')

   id_cliente   nome  cliente_id   produto  valor
0           1    Ana           1  Notebook   3500
1           2  Bruno           2     Mouse    100
2           2  Bruno           2   Teclado    150

In [37]:
df_janeiro = pd.DataFrame({
    'produto': ['Gasolina', 'Etanol'],
    'preco': [6.20, 4.10]
})

df_fevereiro = pd.DataFrame({
    'produto': ['Gasolina', 'Etanol'],
    'preco': [6.30, 4.20]
})

In [38]:
pd.concat([df_janeiro,df_fevereiro])

    produto  preco
0  Gasolina    6.2
1    Etanol    4.1
0  Gasolina    6.3
1    Etanol    4.2

In [39]:
pd.concat([df_janeiro, df_fevereiro], ignore_index=True)

    produto  preco
0  Gasolina    6.2
1    Etanol    4.1
2  Gasolina    6.3
3    Etanol    4.2

In [40]:
pd.concat([df_janeiro, df_fevereiro], axis =1)

    produto  preco   produto  preco
0  Gasolina    6.2  Gasolina    6.3
1    Etanol    4.1    Etanol    4.2

In [41]:
df['ANO_ANALISE'] = df['DATA_INICIAL'].dt.year

In [42]:
duracao = df['DATA_FINAL'] - df['DATA_INICIAL']

In [43]:
df['DURACAO_DIAS'] = duracao.dt.days

In [44]:
df.head()

,DATA_INICIAL,DATA_FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO_DE_POSTOS_PESQUISADOS,UNIDADE_DE_MEDIDA,PREÇO_MÉDIO_REVENDA,DESVIO_PADRÃO_REVENDA,PREÇO_MÍNIMO_REVENDA,...,COEF_DE_VARIAÇÃO_DISTRIBUIÇÃO,MÊS,ANO,AMPLITUDE_PRECO,CATEGORIA_PRECO,CATEGORIA_PRECO_2,TIPO_COMBUSTIVEL,CLASSIFICACAO,ANO_ANALISE,DURACAO_DIAS
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,...,0.133,5,2004,0.160,BAIXO,BAIXO,ETANOL,BARATO,2004,6
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,...,0.115,5,2004,0.559,BAIXO,BAIXO,ETANOL,BARATO,2004,6
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,...,0.098,5,2004,0.580,BAIXO,BAIXO,ETANOL,BARATO,2004,6
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,...,0.143,5,2004,0.419,BAIXO,BAIXO,ETANOL,BARATO,2004,6
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,...,0.082,5,2004,0.350,BAIXO,BAIXO,ETANOL,BARATO,2004,6

In [45]:
df.groupby('ANO_ANALISE').size()

ANO_ANALISE
2004    4205
2005    6186
2006    6598
2007    6475
2008    6453
2009    6232
2010    6489
2011    6487
2012    6634
2013    7921
2014    7932
2015    7771
2016    7873
2017    7990
2018    7823
2019    3754
dtype: int64

In [46]:
df.groupby('ANO_ANALISE')['PREÇO_MÉDIO_REVENDA'].mean()

ANO_ANALISE
2004     8.351370
2005     8.362085
2006     8.917147
2007     9.027187
2008     9.167603
2009     9.559809
2010    10.042510
2011    10.248218
2012    10.443419
2013     9.516663
2014    10.088056
2015    11.339927
2016    12.717348
2017    13.761745
2018    15.786378
2019    16.077599
Name: PREÇO_MÉDIO_REVENDA, dtype: float64

In [47]:
df.groupby(['ANO_ANALISE', 'PRODUTO'])['PREÇO_MÉDIO_REVENDA'].mean()

ANO_ANALISE  PRODUTO
2004         ETANOL HIDRATADO     1.528289
             GASOLINA COMUM       2.238857
             GLP                 32.258845
             GNV                  1.146280
             ÓLEO DIESEL          1.562836
                                   ...
2019         GASOLINA COMUM       4.398127
             GLP                 72.314121
             GNV                  3.253322
             ÓLEO DIESEL          3.665228
             ÓLEO DIESEL S10      3.752556
Name: PREÇO_MÉDIO_REVENDA, Length: 88, dtype: float64

In [51]:
media = df.groupby(['PRODUTO', 'ANO'])['PREÇO_MÉDIO_REVENDA'].mean()

resultado = media.groupby(level='PRODUTO').idxmax()

resultado

PRODUTO
ETANOL HIDRATADO    (ETANOL HIDRATADO, 2019)
GASOLINA COMUM        (GASOLINA COMUM, 2018)
GLP                              (GLP, 2019)
GNV                              (GNV, 2019)
ÓLEO DIESEL              (ÓLEO DIESEL, 2019)
ÓLEO DIESEL S10      (ÓLEO DIESEL S10, 2019)
Name: PREÇO_MÉDIO_REVENDA, dtype: object

In [69]:
df_vendas = pd.DataFrame({
    'ESTADO': ['RJ', 'SP', 'MG', 'BA', 'PR'],
    'PRODUTO': ['GASOLINA', 'ETANOL', 'DIESEL', 'GASOLINA', 'ETANOL'],
    'PREÇO': [5.80, 4.20, 6.10, 5.90, 4.50]
})

df_estados = pd.DataFrame({
    'ESTADO': ['RJ', 'SP', 'MG', 'BA', 'PR'],
    'REGIÃO': ['SUDESTE', 'SUDESTE', 'SUDESTE', 'NORDESTE', 'SUL']
})
df_vendas2 = pd.DataFrame({
    'ESTADO': ['RS','SC','ES','CE'],
    'PRODUTO': ['ARROZ', 'FEIJÃO', 'CARNE','FARINHA'],
    'PREÇO': [7.00, 6.50, 20.30, 5.40]
})

In [64]:
selecao = pd.merge(df_vendas, df_estados, how='outer')
resultado = selecao[['ESTADO', 'PRODUTO', 'REGIÃO']]
resultado

  ESTADO   PRODUTO    REGIÃO
0     BA  GASOLINA  NORDESTE
1     MG    DIESEL   SUDESTE
2     PR    ETANOL       SUL
3     RJ  GASOLINA   SUDESTE
4     SP    ETANOL   SUDESTE

In [72]:
pd.concat([df_vendas, df_vendas2]).reset_index(drop = True)

  ESTADO   PRODUTO  PREÇO
0     RJ  GASOLINA    5.8
1     SP    ETANOL    4.2
2     MG    DIESEL    6.1
3     BA  GASOLINA    5.9
4     PR    ETANOL    4.5
5     RS     ARROZ    7.0
6     SC    FEIJÃO    6.5
7     ES     CARNE   20.3
8     CE   FARINHA    5.4

In [77]:
df_vendas.duplicated().sum()
df_vendas.drop_duplicates()

  ESTADO   PRODUTO  PREÇO
0     RJ  GASOLINA    5.8
1     SP    ETANOL    4.2
2     MG    DIESEL    6.1
3     BA  GASOLINA    5.9
4     PR    ETANOL    4.5

In [91]:
df.isna().sum()

DATA_INICIAL                        0
DATA_FINAL                          0
REGIÃO                              0
ESTADO                              0
PRODUTO                             0
NÚMERO_DE_POSTOS_PESQUISADOS        0
UNIDADE_DE_MEDIDA                   0
PREÇO_MÉDIO_REVENDA                 0
DESVIO_PADRÃO_REVENDA               0
PREÇO_MÍNIMO_REVENDA                0
PREÇO_MÁXIMO_REVENDA                0
MARGEM_MÉDIA_REVENDA                0
COEF_DE_VARIAÇÃO_REVENDA            0
PREÇO_MÉDIO_DISTRIBUIÇÃO         3400
DESVIO_PADRÃO_DISTRIBUIÇÃO       3400
PREÇO_MÍNIMO_DISTRIBUIÇÃO        3400
PREÇO_MÁXIMO_DISTRIBUIÇÃO        3400
COEF_DE_VARIAÇÃO_DISTRIBUIÇÃO    3400
MÊS                                 0
ANO                                 0
AMPLITUDE_PRECO                     0
CATEGORIA_PRECO                     0
CATEGORIA_PRECO_2                   0
TIPO_COMBUSTIVEL                    0
CLASSIFICACAO                       0
ANO_ANALISE                         0
DURACAO_DIAS                        0
dtype: int64

In [90]:
df['MARGEM_MÉDIA_REVENDA'] = df['MARGEM_MÉDIA_REVENDA'].fillna(df['MARGEM_MÉDIA_REVENDA'].mean())

In [104]:
df.loc[df['ESTADO'] == "RIO DE JANEIRO",['PRODUTO', 'PREÇO_MÉDIO_REVENDA']]

                 PRODUTO  PREÇO_MÉDIO_REVENDA
22      ETANOL HIDRATADO                1.098
49      ETANOL HIDRATADO                1.092
76      ETANOL HIDRATADO                1.103
103     ETANOL HIDRATADO                1.149
130     ETANOL HIDRATADO                1.165
...                  ...                  ...
106718       ÓLEO DIESEL                3.569
106745   ÓLEO DIESEL S10                3.697
106772    GASOLINA COMUM                4.928
106799               GLP               65.010
106817               GNV                3.111

[4263 rows x 2 columns]

In [105]:
df.iloc[:10,:5]

  DATA_INICIAL DATA_FINAL        REGIÃO              ESTADO           PRODUTO
0   2004-05-09 2004-05-15  CENTRO OESTE    DISTRITO FEDERAL  ETANOL HIDRATADO
1   2004-05-09 2004-05-15  CENTRO OESTE               GOIAS  ETANOL HIDRATADO
2   2004-05-09 2004-05-15  CENTRO OESTE         MATO GROSSO  ETANOL HIDRATADO
3   2004-05-09 2004-05-15  CENTRO OESTE  MATO GROSSO DO SUL  ETANOL HIDRATADO
4   2004-05-09 2004-05-15      NORDESTE             ALAGOAS  ETANOL HIDRATADO
5   2004-05-09 2004-05-15      NORDESTE               BAHIA  ETANOL HIDRATADO
6   2004-05-09 2004-05-15      NORDESTE               CEARA  ETANOL HIDRATADO
7   2004-05-09 2004-05-15      NORDESTE            MARANHAO  ETANOL HIDRATADO
8   2004-05-09 2004-05-15      NORDESTE             PARAIBA  ETANOL HIDRATADO
9   2004-05-09 2004-05-15      NORDESTE          PERNAMBUCO  ETANOL HIDRATADO

In [106]:
df.groupby('PRODUTO')['PREÇO_MÉDIO_REVENDA'].agg(['min','max','mean'])

                     min     max       mean
PRODUTO
ETANOL HIDRATADO   0.766   4.459   2.318497
GASOLINA COMUM     1.888   5.362   3.048132
GLP               28.026  99.357  44.513081
GNV                0.975   4.020   1.898992
ÓLEO DIESEL        1.313   4.774   2.422245
ÓLEO DIESEL S10    2.130   4.878   3.136145

In [116]:
df['MÉDIA_PREÇO_MÉDIO_REVENDA'] = df.groupby('PRODUTO')['PREÇO_MÉDIO_REVENDA'].transform('mean')

In [117]:
df.head()

,DATA_INICIAL,DATA_FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO_DE_POSTOS_PESQUISADOS,UNIDADE_DE_MEDIDA,PREÇO_MÉDIO_REVENDA,DESVIO_PADRÃO_REVENDA,PREÇO_MÍNIMO_REVENDA,...,MÊS,ANO,AMPLITUDE_PRECO,CATEGORIA_PRECO,CATEGORIA_PRECO_2,TIPO_COMBUSTIVEL,CLASSIFICACAO,ANO_ANALISE,DURACAO_DIAS,MÉDIA_PREÇO_MÉDIO_REVENDA
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,...,5,2004,0.160,BAIXO,BAIXO,ETANOL,BARATO,2004,6,2.318497
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,...,5,2004,0.559,BAIXO,BAIXO,ETANOL,BARATO,2004,6,2.318497
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,...,5,2004,0.580,BAIXO,BAIXO,ETANOL,BARATO,2004,6,2.318497
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,...,5,2004,0.419,BAIXO,BAIXO,ETANOL,BARATO,2004,6,2.318497
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,...,5,2004,0.350,BAIXO,BAIXO,ETANOL,BARATO,2004,6,2.318497

In [118]:
df['MÉDIA_PREÇO_MÉDIO_REVENDA'].value_counts()

MÉDIA_PREÇO_MÉDIO_REVENDA
3.048132     21194
2.422245     21194
44.513081    21186
2.318497     21102
1.898992     13034
3.136145      9113
Name: count, dtype: int64

In [121]:
df['DIA_FINAL'] = df['DATA_FINAL'].dt.day
df['MÊS_FINAL'] = df['DATA_FINAL'].dt.month
df['ANO_FINAL'] = df['DATA_FINAL'].dt.year

In [122]:
df.head()

,DATA_INICIAL,DATA_FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO_DE_POSTOS_PESQUISADOS,UNIDADE_DE_MEDIDA,PREÇO_MÉDIO_REVENDA,DESVIO_PADRÃO_REVENDA,PREÇO_MÍNIMO_REVENDA,...,CATEGORIA_PRECO_2,TIPO_COMBUSTIVEL,CLASSIFICACAO,ANO_ANALISE,DURACAO_DIAS,MÉDIA_PREÇO_MÉDIO_REVENDA,DATA,DIA_FINAL,MÊS_FINAL,ANO_FINAL
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,...,BAIXO,ETANOL,BARATO,2004,6,2.318497,15,15,5,2004
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,...,BAIXO,ETANOL,BARATO,2004,6,2.318497,15,15,5,2004
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,...,BAIXO,ETANOL,BARATO,2004,6,2.318497,15,15,5,2004
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,...,BAIXO,ETANOL,BARATO,2004,6,2.318497,15,15,5,2004
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,...,BAIXO,ETANOL,BARATO,2004,6,2.318497,15,15,5,2004

In [125]:
df.to_parquet('./datasets/dados_processados.parquet')

df_parquet = pd.read_parquet('./datasets/dados_processados.parquet')

In [126]:
df_parquet.head()

,DATA_INICIAL,DATA_FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO_DE_POSTOS_PESQUISADOS,UNIDADE_DE_MEDIDA,PREÇO_MÉDIO_REVENDA,DESVIO_PADRÃO_REVENDA,PREÇO_MÍNIMO_REVENDA,...,CATEGORIA_PRECO_2,TIPO_COMBUSTIVEL,CLASSIFICACAO,ANO_ANALISE,DURACAO_DIAS,MÉDIA_PREÇO_MÉDIO_REVENDA,DATA,DIA_FINAL,MÊS_FINAL,ANO_FINAL
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,...,BAIXO,ETANOL,BARATO,2004,6,2.318497,15,15,5,2004
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,...,BAIXO,ETANOL,BARATO,2004,6,2.318497,15,15,5,2004
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,...,BAIXO,ETANOL,BARATO,2004,6,2.318497,15,15,5,2004
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,...,BAIXO,ETANOL,BARATO,2004,6,2.318497,15,15,5,2004
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,...,BAIXO,ETANOL,BARATO,2004,6,2.318497,15,15,5,2004