In [157]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('./datasets/GasPricesinBrazil_2004-2019.csv',sep=';')

In [6]:
df.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106823 entries, 0 to 106822
Data columns (total 21 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Unnamed: 0                     106823 non-null  int64
 1   DATA INICIAL                   106823 non-null  object
 2   DATA FINAL                     106823 non-null  object
 3   REGIÃO                         106823 non-null  object
 4   ESTADO                         106823 non-null  object
 5   PRODUTO                        106823 non-null  object
 6   NÚMERO DE POSTOS PESQUISADOS   106823 non-null  int64
 7   UNIDADE DE MEDIDA              106823 non-null  object
 8   PREÇO MÉDIO REVENDA            106823 non-null  float64
 9   DESVIO PADRÃO REVENDA          106823 non-null  float64
 10  PREÇO MÍNIMO REVENDA           106823 non-null  float64
 11  PREÇO MÁXIMO REVENDA           106823 non-null  float64
 12  MARGEM MÉDIA REVENDA           106823 non-null  object
 13  COEF DE VARIAÇÃO REVENDA       106823 non-null  float64
 14  PREÇO MÉDIO DISTRIBUIÇÃO       106823 non-null  object
 15  DESVIO PADRÃO DISTRIBUIÇÃO     106823 non-null  object
 16  PREÇO MÍNIMO DISTRIBUIÇÃO      106823 non-null  object
 17  PREÇO MÁXIMO DISTRIBUIÇÃO      106823 non-null  object
 18  COEF DE VARIAÇÃO DISTRIBUIÇÃO  106823 non-null  object
 19  MÊS                            106823 non-null  int64
 20  ANO                            106823 non-null  int64
dtypes: float64(5), int64(4), object(12)
memory usage: 17.1+ MB

In [9]:
df.shape

(106823, 21)

In [13]:
df.columns

Index(['Unnamed: 0', 'DATA INICIAL', 'DATA FINAL', 'REGIÃO', 'ESTADO',
       'PRODUTO', 'NÚMERO DE POSTOS PESQUISADOS', 'UNIDADE DE MEDIDA',
       'PREÇO MÉDIO REVENDA', 'DESVIO PADRÃO REVENDA', 'PREÇO MÍNIMO REVENDA',
       'PREÇO MÁXIMO REVENDA', 'MARGEM MÉDIA REVENDA',
       'COEF DE VARIAÇÃO REVENDA', 'PREÇO MÉDIO DISTRIBUIÇÃO',
       'DESVIO PADRÃO DISTRIBUIÇÃO', 'PREÇO MÍNIMO DISTRIBUIÇÃO',
       'PREÇO MÁXIMO DISTRIBUIÇÃO', 'COEF DE VARIAÇÃO DISTRIBUIÇÃO', 'MÊS',
       'ANO'],
      dtype='object')

In [19]:
df['ESTADO'].unique()

array(['DISTRITO FEDERAL', 'GOIAS', 'MATO GROSSO', 'MATO GROSSO DO SUL',
       'ALAGOAS', 'BAHIA', 'CEARA', 'MARANHAO', 'PARAIBA', 'PERNAMBUCO',
       'PIAUI', 'RIO GRANDE DO NORTE', 'SERGIPE', 'ACRE', 'AMAPA',
       'AMAZONAS', 'PARA', 'RONDONIA', 'RORAIMA', 'TOCANTINS',
       'ESPIRITO SANTO', 'MINAS GERAIS', 'RIO DE JANEIRO', 'SAO PAULO',
       'PARANA', 'RIO GRANDE DO SUL', 'SANTA CATARINA'], dtype=object)

In [20]:
df['PRODUTO'].unique()

array(['ETANOL HIDRATADO', 'GASOLINA COMUM', 'GLP', 'GNV', 'ÓLEO DIESEL',
       'ÓLEO DIESEL S10'], dtype=object)

In [24]:
df['PREÇO MÉDIO REVENDA'].min()

np.float64(0.765999999999999)

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106823 entries, 0 to 106822
Data columns (total 21 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Unnamed: 0                     106823 non-null  int64
 1   DATA INICIAL                   106823 non-null  object
 2   DATA FINAL                     106823 non-null  object
 3   REGIÃO                         106823 non-null  object
 4   ESTADO                         106823 non-null  object
 5   PRODUTO                        106823 non-null  object
 6   NÚMERO DE POSTOS PESQUISADOS   106823 non-null  int64
 7   UNIDADE DE MEDIDA              106823 non-null  object
 8   PREÇO MÉDIO REVENDA            106823 non-null  float64
 9   DESVIO PADRÃO REVENDA          106823 non-null  float64
 10  PREÇO MÍNIMO REVENDA           106823 non-null  float64
 11  PREÇO MÁXIMO REVENDA           106823 non-null  float64
 12  MARGEM MÉDIA REVENDA           106823 non-null  object
 13  COEF DE VARIAÇÃO REVENDA       106823 non-null  float64
 14  PREÇO MÉDIO DISTRIBUIÇÃO       106823 non-null  object
 15  DESVIO PADRÃO DISTRIBUIÇÃO     106823 non-null  object
 16  PREÇO MÍNIMO DISTRIBUIÇÃO      106823 non-null  object
 17  PREÇO MÁXIMO DISTRIBUIÇÃO      106823 non-null  object
 18  COEF DE VARIAÇÃO DISTRIBUIÇÃO  106823 non-null  object
 19  MÊS                            106823 non-null  int64
 20  ANO                            106823 non-null  int64
dtypes: float64(5), int64(4), object(12)
memory usage: 17.1+ MB

MARGEM MÉDIA REVENDA, PREÇO MÉDIO DISTRIBUIÇÃO, DESVIO PADRÃO DISTRIBUIÇÃO, PREÇO MÍNIMO DISTRIBUIÇÃO, PREÇO MÁXIMO DISTRIBUIÇÃO, COEF DE VARIAÇÃO DISTRIBUIÇÃO

In [34]:
df['MARGEM MÉDIA REVENDA'] = pd.to_numeric(df['MARGEM MÉDIA REVENDA'], errors='coerce')

In [36]:
df.isnull().sum()

Unnamed: 0                          0
DATA INICIAL                        0
DATA FINAL                          0
REGIÃO                              0
ESTADO                              0
PRODUTO                             0
NÚMERO DE POSTOS PESQUISADOS        0
UNIDADE DE MEDIDA                   0
PREÇO MÉDIO REVENDA                 0
DESVIO PADRÃO REVENDA               0
PREÇO MÍNIMO REVENDA                0
PREÇO MÁXIMO REVENDA                0
MARGEM MÉDIA REVENDA             3431
COEF DE VARIAÇÃO REVENDA            0
PREÇO MÉDIO DISTRIBUIÇÃO            0
DESVIO PADRÃO DISTRIBUIÇÃO          0
PREÇO MÍNIMO DISTRIBUIÇÃO           0
PREÇO MÁXIMO DISTRIBUIÇÃO           0
COEF DE VARIAÇÃO DISTRIBUIÇÃO       0
MÊS                                 0
ANO                                 0
dtype: int64

In [37]:
for coluna in ['PREÇO MÉDIO DISTRIBUIÇÃO', 'DESVIO PADRÃO DISTRIBUIÇÃO', 'PREÇO MÍNIMO DISTRIBUIÇÃO', 'PREÇO MÁXIMO DISTRIBUIÇÃO', 'COEF DE VARIAÇÃO DISTRIBUIÇÃO']:
    df[coluna] = pd.to_numeric(df[coluna], errors='coerce')

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106823 entries, 0 to 106822
Data columns (total 21 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Unnamed: 0                     106823 non-null  int64
 1   DATA INICIAL                   106823 non-null  object
 2   DATA FINAL                     106823 non-null  object
 3   REGIÃO                         106823 non-null  object
 4   ESTADO                         106823 non-null  object
 5   PRODUTO                        106823 non-null  object
 6   NÚMERO DE POSTOS PESQUISADOS   106823 non-null  int64
 7   UNIDADE DE MEDIDA              106823 non-null  object
 8   PREÇO MÉDIO REVENDA            106823 non-null  float64
 9   DESVIO PADRÃO REVENDA          106823 non-null  float64
 10  PREÇO MÍNIMO REVENDA           106823 non-null  float64
 11  PREÇO MÁXIMO REVENDA           106823 non-null  float64
 12  MARGEM MÉDIA REVENDA           103392 non-null  float64
 13  COEF DE VARIAÇÃO REVENDA       106823 non-null  float64
 14  PREÇO MÉDIO DISTRIBUIÇÃO       103423 non-null  float64
 15  DESVIO PADRÃO DISTRIBUIÇÃO     103423 non-null  float64
 16  PREÇO MÍNIMO DISTRIBUIÇÃO      103423 non-null  float64
 17  PREÇO MÁXIMO DISTRIBUIÇÃO      103423 non-null  float64
 18  COEF DE VARIAÇÃO DISTRIBUIÇÃO  103423 non-null  float64
 19  MÊS                            106823 non-null  int64
 20  ANO                            106823 non-null  int64
dtypes: float64(11), int64(4), object(6)
memory usage: 17.1+ MB

In [40]:
df.isnull().sum()

Unnamed: 0                          0
DATA INICIAL                        0
DATA FINAL                          0
REGIÃO                              0
ESTADO                              0
PRODUTO                             0
NÚMERO DE POSTOS PESQUISADOS        0
UNIDADE DE MEDIDA                   0
PREÇO MÉDIO REVENDA                 0
DESVIO PADRÃO REVENDA               0
PREÇO MÍNIMO REVENDA                0
PREÇO MÁXIMO REVENDA                0
MARGEM MÉDIA REVENDA             3431
COEF DE VARIAÇÃO REVENDA            0
PREÇO MÉDIO DISTRIBUIÇÃO         3400
DESVIO PADRÃO DISTRIBUIÇÃO       3400
PREÇO MÍNIMO DISTRIBUIÇÃO        3400
PREÇO MÁXIMO DISTRIBUIÇÃO        3400
COEF DE VARIAÇÃO DISTRIBUIÇÃO    3400
MÊS                                 0
ANO                                 0
dtype: int64

In [42]:
df.isnull().sum() / len(df) * 100

Unnamed: 0                       0.000000
DATA INICIAL                     0.000000
DATA FINAL                       0.000000
REGIÃO                           0.000000
ESTADO                           0.000000
PRODUTO                          0.000000
NÚMERO DE POSTOS PESQUISADOS     0.000000
UNIDADE DE MEDIDA                0.000000
PREÇO MÉDIO REVENDA              0.000000
DESVIO PADRÃO REVENDA            0.000000
PREÇO MÍNIMO REVENDA             0.000000
PREÇO MÁXIMO REVENDA             0.000000
MARGEM MÉDIA REVENDA             3.211855
COEF DE VARIAÇÃO REVENDA         0.000000
PREÇO MÉDIO DISTRIBUIÇÃO         3.182835
DESVIO PADRÃO DISTRIBUIÇÃO       3.182835
PREÇO MÍNIMO DISTRIBUIÇÃO        3.182835
PREÇO MÁXIMO DISTRIBUIÇÃO        3.182835
COEF DE VARIAÇÃO DISTRIBUIÇÃO    3.182835
MÊS                              0.000000
ANO                              0.000000
dtype: float64

In [43]:
df.duplicated().sum()

np.int64(0)

In [44]:
for coluna in ['DATA INICIAL', 'DATA FINAL']:
    df[coluna] = pd.to_datetime(df[coluna])

In [48]:
df.dtypes.to_frame()

                                            0
Unnamed: 0                              int64
DATA INICIAL                   datetime64[ns]
DATA FINAL                     datetime64[ns]
REGIÃO                                 object
ESTADO                                 object
PRODUTO                                object
NÚMERO DE POSTOS PESQUISADOS            int64
UNIDADE DE MEDIDA                      object
PREÇO MÉDIO REVENDA                   float64
DESVIO PADRÃO REVENDA                 float64
PREÇO MÍNIMO REVENDA                  float64
PREÇO MÁXIMO REVENDA                  float64
MARGEM MÉDIA REVENDA                  float64
COEF DE VARIAÇÃO REVENDA              float64
PREÇO MÉDIO DISTRIBUIÇÃO              float64
DESVIO PADRÃO DISTRIBUIÇÃO            float64
PREÇO MÍNIMO DISTRIBUIÇÃO             float64
PREÇO MÁXIMO DISTRIBUIÇÃO             float64
COEF DE VARIAÇÃO DISTRIBUIÇÃO         float64
MÊS                                     int64
ANO                                     int64

In [49]:
gasolina = df.query('PRODUTO == "GASOLINA COMUM"')

In [50]:
gasolina

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
12064,12064,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,GASOLINA COMUM,128,R$/l,2.029,0.007,...,2.070,0.318,0.003,1.711,0.020,1.65100,1.7427,0.012,5,2004
12065,12065,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,GASOLINA COMUM,395,R$/l,2.025,0.062,...,2.220,0.296,0.031,1.729,0.036,1.66430,1.9150,0.021,5,2004
12066,12066,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,GASOLINA COMUM,194,R$/l,2.358,0.066,...,2.540,0.472,0.028,1.886,0.068,1.75000,2.0713,0.036,5,2004
12067,12067,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,GASOLINA COMUM,166,R$/l,2.120,0.075,...,2.440,0.325,0.035,1.795,0.033,1.70701,1.9703,0.018,5,2004
12068,12068,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,GASOLINA COMUM,106,R$/l,2.090,0.034,...,2.159,0.350,0.016,1.740,0.042,1.67890,1.9180,0.024,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106776,106776,2019-06-23,2019-06-29,NORTE,RORAIMA,GASOLINA COMUM,13,R$/l,4.156,0.010,...,4.170,0.444,0.002,3.712,0.060,3.64690,3.8250,0.016,6,2019
106777,106777,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GASOLINA COMUM,252,R$/l,4.087,0.173,...,4.698,0.303,0.042,3.784,0.083,3.59000,3.9980,0.022,6,2019
106778,106778,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.142,0.183,...,4.999,0.429,0.044,3.713,0.097,3.52000,4.0892,0.026,6,2019
106779,106779,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GASOLINA COMUM,43,R$/l,4.400,0.102,...,4.799,0.346,0.023,4.054,0.040,4.01000,4.1483,0.010,6,2019
106780,106780,2019-06-23,2019-06-29,NORTE,TOCANTINS,GASOLINA COMUM,46,R$/l,4.682,0.197,...,5.690,0.642,0.042,4.040,0.051,3.93000,4.1300,0.013,6,2019

In [58]:
df[df['PRODUTO'] == "GASOLINA COMUM"].reset_index(drop=True)

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,12064,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,GASOLINA COMUM,128,R$/l,2.029,0.007,...,2.070,0.318,0.003,1.711,0.020,1.65100,1.7427,0.012,5,2004
1,12065,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,GASOLINA COMUM,395,R$/l,2.025,0.062,...,2.220,0.296,0.031,1.729,0.036,1.66430,1.9150,0.021,5,2004
2,12066,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,GASOLINA COMUM,194,R$/l,2.358,0.066,...,2.540,0.472,0.028,1.886,0.068,1.75000,2.0713,0.036,5,2004
3,12067,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,GASOLINA COMUM,166,R$/l,2.120,0.075,...,2.440,0.325,0.035,1.795,0.033,1.70701,1.9703,0.018,5,2004
4,12068,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,GASOLINA COMUM,106,R$/l,2.090,0.034,...,2.159,0.350,0.016,1.740,0.042,1.67890,1.9180,0.024,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21189,106776,2019-06-23,2019-06-29,NORTE,RORAIMA,GASOLINA COMUM,13,R$/l,4.156,0.010,...,4.170,0.444,0.002,3.712,0.060,3.64690,3.8250,0.016,6,2019
21190,106777,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GASOLINA COMUM,252,R$/l,4.087,0.173,...,4.698,0.303,0.042,3.784,0.083,3.59000,3.9980,0.022,6,2019
21191,106778,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.142,0.183,...,4.999,0.429,0.044,3.713,0.097,3.52000,4.0892,0.026,6,2019
21192,106779,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GASOLINA COMUM,43,R$/l,4.400,0.102,...,4.799,0.346,0.023,4.054,0.040,4.01000,4.1483,0.010,6,2019
21193,106780,2019-06-23,2019-06-29,NORTE,TOCANTINS,GASOLINA COMUM,46,R$/l,4.682,0.197,...,5.690,0.642,0.042,4.040,0.051,3.93000,4.1300,0.013,6,2019

In [72]:
rj = df[df['ESTADO'] == "RIO DE JANEIRO"]

In [79]:
rj[rj['PRODUTO'] == "GASOLINA COMUM"]['PREÇO MÉDIO REVENDA'].mean()

np.float64(3.1226382165605093)

In [99]:
df[df['PREÇO MÉDIO REVENDA'] > 7].shape

(21186, 21)

In [105]:
grupo_estados = df.groupby('ESTADO')

In [107]:
grupo_estados['PREÇO MÉDIO REVENDA'].mean().to_frame()

                     PREÇO MÉDIO REVENDA
ESTADO
ACRE                           13.544876
ALAGOAS                         9.622259
AMAPA                          13.435394
AMAZONAS                       10.368645
BAHIA                           9.406878
CEARA                          10.226637
DISTRITO FEDERAL               12.197823
ESPIRITO SANTO                  9.534348
GOIAS                          11.309635
MARANHAO                       11.992578
MATO GROSSO                    12.861120
MATO GROSSO DO SUL             11.045832
MINAS GERAIS                   10.243751
PARA                           12.292955
PARAIBA                         9.464513
PARANA                          9.845426
PERNAMBUCO                      9.352028
PIAUI                          11.739773
RIO DE JANEIRO                  9.537528
RIO GRANDE DO NORTE             9.832325
RIO GRANDE DO SUL              10.061393
RONDONIA                       12.808276
RORAIMA                        13.209867
SANTA CATARINA                 10.115375
SAO PAULO                       9.485222
SERGIPE                         9.857946
TOCANTINS                      13.326909

In [111]:
grupo_produtos = df.groupby('PRODUTO')

In [112]:
grupo_produtos['PREÇO MÉDIO REVENDA'].mean().to_frame()

                  PREÇO MÉDIO REVENDA
PRODUTO
ETANOL HIDRATADO             2.318497
GASOLINA COMUM               3.048132
GLP                         44.513081
GNV                          1.898992
ÓLEO DIESEL                  2.422245
ÓLEO DIESEL S10              3.136145

In [127]:
selecao1 = df.groupby(['ESTADO', 'PRODUTO'])

In [128]:
grupo_estados_produtos = selecao1['PREÇO MÉDIO REVENDA'].mean()

In [129]:
grupo_estados_produtos

ESTADO     PRODUTO
ACRE       ETANOL HIDRATADO     2.682592
           GASOLINA COMUM       3.413656
           GLP                 49.496222
           GNV                  2.322000
           ÓLEO DIESEL          2.880958
                                 ...
TOCANTINS  GASOLINA COMUM       3.166631
           GLP                 49.950201
           GNV                  2.972833
           ÓLEO DIESEL          2.359983
           ÓLEO DIESEL S10      3.018544
Name: PREÇO MÉDIO REVENDA, Length: 161, dtype: float64

In [138]:
df.groupby('ESTADO')['PREÇO MÉDIO REVENDA'].agg(
    preço_minimo = 'min', 
    preco_maximo='max', 
    preco_medio='mean')

                     preço_minimo  preco_maximo  preco_medio
ESTADO
ACRE                        1.713        81.072    13.544876
ALAGOAS                     1.074        69.185     9.622259
AMAPA                       1.504        80.081    13.435394
AMAZONAS                    1.399        73.916    10.368645
BAHIA                       1.079        63.577     9.406878
CEARA                       1.182        75.317    10.226637
DISTRITO FEDERAL            1.216        73.929    12.197823
ESPIRITO SANTO              1.135        65.438     9.534348
GOIAS                       1.162        74.320    11.309635
MARANHAO                    1.290        75.972    11.992578
MATO GROSSO                 1.204        99.357    12.861120
MATO GROSSO DO SUL          1.097        77.911    11.045832
MINAS GERAIS                1.110        79.192    10.243751
PARA                        1.476        77.192    12.292955
PARAIBA                     1.149        68.410     9.464513
PARANA                      0.922        70.631     9.845426
PERNAMBUCO                  0.999        66.993     9.352028
PIAUI                       1.339        73.125    11.739773
RIO DE JANEIRO              1.036        67.679     9.537528
RIO GRANDE DO NORTE         0.975        72.233     9.832325
RIO GRANDE DO SUL           1.168        70.729    10.061393
RONDONIA                    1.219        79.352    12.808276
RORAIMA                     1.300        85.375    13.209867
SANTA CATARINA              1.197        72.088    10.115375
SAO PAULO                   0.766        70.800     9.485222
SERGIPE                     1.155        79.630     9.857946
TOCANTINS                   1.226        87.270    13.326909

In [147]:
df.groupby('ESTADO')['PREÇO MÉDIO REVENDA'].mean().sort_values().head()

ESTADO
PERNAMBUCO        9.352028
BAHIA             9.406878
PARAIBA           9.464513
SAO PAULO         9.485222
ESPIRITO SANTO    9.534348
Name: PREÇO MÉDIO REVENDA, dtype: float64

In [152]:
df['AMPLITUDE_PRECO'] = df['PREÇO MÁXIMO REVENDA'] - df['PREÇO MÍNIMO REVENDA']

In [156]:
if df['PREÇO MÉDIO REVENDA'] < 5:
    df['CATEGORIA_PRECO'] = "BAIXO"
elif df['PREÇO MÉDIO REVENDA'] > 7:
    df['CATEGORIA_PRECO'] = "ALTO"
elif df['PREÇO MÉDIO REVENDA'] > 5 and df['PREÇO MÉDIO REVENDA'] < 7:
    df['CATEGORIA_PRECO'] = "MEDIO"

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [158]:
condicao = [
    df['PREÇO MÉDIO REVENDA'] < 5,
    df['PREÇO MÉDIO REVENDA'] > 7
]

valores = [
    'BAIXO',
    'ALTO'
]

df['CATEGORIA_PRECO'] = np.select(condicao, valores, default = 'MEDIO')

In [166]:
df['CATEGORIA_PRECO'].value_counts()

CATEGORIA_PRECO
BAIXO    85581
ALTO     21186
MEDIO       56
Name: count, dtype: int64

In [177]:
def limpar_dados(df):
    df.columns = (df.columns
                 .str.strip()
                 .str.upper()
                 .str.replace(" ", "_")
                 )
    for colunas_numericas in ['PREÇO_MÉDIO_DISTRIBUIÇÃO', 'DESVIO_PADRÃO_DISTRIBUIÇÃO', 'PREÇO_MÍNIMO_DISTRIBUIÇÃO', 'PREÇO_MÁXIMO_DISTRIBUIÇÃO', 'COEF_DE_VARIAÇÃO_DISTRIBUIÇÃO']:
        df[colunas_numericas] = pd.to_numeric(df[colunas_numericas], errors = 'coerce')

    for colunas_data in ['DATA_INICIAL', 'DATA_FINAL']:
        df[colunas_data] = pd.to_datetime(df[colunas_data])
    df = df.fillna('DESCONHECIDO')
    df = df.drop_duplicates()


    return df

In [176]:
df = pd.read_csv('./datasets/GasPricesinBrazil_2004-2019.csv', sep=';')

In [178]:
limpar_dados(df)

,UNNAMED:_0,DATA_INICIAL,DATA_FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO_DE_POSTOS_PESQUISADOS,UNIDADE_DE_MEDIDA,PREÇO_MÉDIO_REVENDA,DESVIO_PADRÃO_REVENDA,...,PREÇO_MÁXIMO_REVENDA,MARGEM_MÉDIA_REVENDA,COEF_DE_VARIAÇÃO_REVENDA,PREÇO_MÉDIO_DISTRIBUIÇÃO,DESVIO_PADRÃO_DISTRIBUIÇÃO,PREÇO_MÍNIMO_DISTRIBUIÇÃO,PREÇO_MÁXIMO_DISTRIBUIÇÃO,COEF_DE_VARIAÇÃO_DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,...,3.690,0.818,0.018,2.756,0.0,2.756,2.756,0.0,6,2019
106819,106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,...,3.789,0.95,0.038,2.451,0.402,1.9842,2.8661,0.164,6,2019
106820,106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,...,3.499,0.914,0.065,1.998,0.0,1.9981,1.9981,0.0,6,2019
106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,3.490,0.646,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019
106822,106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,0.005,...,3.699,1.179,0.001,2.518,0.0,2.5175,2.5175,0.0,6,2019

In [179]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106823 entries, 0 to 106822
Data columns (total 21 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   UNNAMED:_0                     106823 non-null  int64
 1   DATA_INICIAL                   106823 non-null  datetime64[ns]
 2   DATA_FINAL                     106823 non-null  datetime64[ns]
 3   REGIÃO                         106823 non-null  object
 4   ESTADO                         106823 non-null  object
 5   PRODUTO                        106823 non-null  object
 6   NÚMERO_DE_POSTOS_PESQUISADOS   106823 non-null  int64
 7   UNIDADE_DE_MEDIDA              106823 non-null  object
 8   PREÇO_MÉDIO_REVENDA            106823 non-null  float64
 9   DESVIO_PADRÃO_REVENDA          106823 non-null  float64
 10  PREÇO_MÍNIMO_REVENDA           106823 non-null  float64
 11  PREÇO_MÁXIMO_REVENDA           106823 non-null  float64
 12  MARGEM_MÉDIA_REVENDA           106823 non-null  object
 13  COEF_DE_VARIAÇÃO_REVENDA       106823 non-null  float64
 14  PREÇO_MÉDIO_DISTRIBUIÇÃO       103423 non-null  float64
 15  DESVIO_PADRÃO_DISTRIBUIÇÃO     103423 non-null  float64
 16  PREÇO_MÍNIMO_DISTRIBUIÇÃO      103423 non-null  float64
 17  PREÇO_MÁXIMO_DISTRIBUIÇÃO      103423 non-null  float64
 18  COEF_DE_VARIAÇÃO_DISTRIBUIÇÃO  103423 non-null  float64
 19  MÊS                            106823 non-null  int64
 20  ANO                            106823 non-null  int64
dtypes: datetime64[ns](2), float64(10), int64(4), object(5)
memory usage: 17.1+ MB