In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('./datasets/igr.csv', encoding='latin1',sep=';')

In [5]:
df.head()

,Razão Social (Registro ANS),Cobertura,Porte,Classificação no Mês,Classificação no Mês Anterior,out/22,set/22,ago/22,jul/22,jun/22,mai/22,abr/22,mar/22,fev/22,jan/22,dez/21,nov/21,Competência,Data de atualização
0,CAIXA DE ASSISTÊNCIA DO SETOR DE ENERGIA -EVI...,Médico Hospitalar,Pequeno,80,90.0,"3,56","4,13","4,33","1,83","3,61","6,20","6,72","9,16","8,31","9,05","5,02","6,01",202210,15/11/2022 05:40:45
1,ABERTTA SAÚDE - ASSOCIAÇÃO BENEFICENTE DOS EMP...,Médico Hospitalar,Médio,206,187.0,"0,20","0,41","0,41","0,20","0,00","0,00","0,00","0,21","0,21","0,21","0,21","0,41",202210,15/11/2022 05:40:45
2,ADVANCE PLANOS DE SAÚDE LTDA (335657),Médico Hospitalar,Pequeno,51,33.0,"8,72","17,33","12,89","12,79","4,23","33,73","29,37","33,38","8,30","20,64","28,76","24,54",202210,15/11/2022 05:40:45
3,AGROS - INSTITUTO UFV DE SEGURIDADE SOCIAL (36...,Médico Hospitalar,Pequeno,177,197.0,"0,00","0,00","0,00","0,00","0,66","0,66","0,66","0,00","0,00","0,66","1,32","3,28",202210,15/11/2022 05:40:45
4,ALCANCE SAÚDE EIRELI (416975),Médico Hospitalar,Pequeno,177,197.0,"0,00","0,00","0,00","0,00","0,00","0,00","0,00","2,24","2,25","6,78","4,54","4,56",202210,15/11/2022 05:40:45

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 915 entries, 0 to 914
Data columns (total 19 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Razão Social (Registro ANS)    915 non-null    object
 1   Cobertura                      915 non-null    object
 2   Porte                          915 non-null    object
 3   Classificação no Mês           915 non-null    int64
 4   Classificação no Mês Anterior  911 non-null    float64
 5   out/22                         915 non-null    object
 6   set/22                         911 non-null    object
 7   ago/22                         911 non-null    object
 8   jul/22                         909 non-null    object
 9   jun/22                         908 non-null    object
 10  mai/22                         907 non-null    object
 11  abr/22                         905 non-null    object
 12  mar/22                         903 non-null    object
 13  fev/22                         899 non-null    object
 14  jan/22                         897 non-null    object
 15  dez/21                         896 non-null    object
 16  nov/21                         894 non-null    object
 17  Competência                    915 non-null    int64
 18  Data de atualização            915 non-null    object
dtypes: float64(1), int64(2), object(16)
memory usage: 135.9+ KB

In [7]:
df.shape

(915, 19)

In [10]:
df.isnull().sum()

Razão Social (Registro ANS)       0
Cobertura                         0
Porte                             0
Classificação no Mês              0
Classificação no Mês Anterior     4
out/22                            0
set/22                            4
ago/22                            4
jul/22                            6
jun/22                            7
mai/22                            8
abr/22                           10
mar/22                           12
fev/22                           16
jan/22                           18
dez/21                           19
nov/21                           21
Competência                       0
Data de atualização               0
dtype: int64

In [14]:
df[df.isnull().any(axis=1)].head()

,Razão Social (Registro ANS),Cobertura,Porte,Classificação no Mês,Classificação no Mês Anterior,out/22,set/22,ago/22,jul/22,jun/22,mai/22,abr/22,mar/22,fev/22,jan/22,dez/21,nov/21,Competência,Data de atualização
20,ANGELI SISTEMAS DE SAUDE S.A. (421871),Médico Hospitalar,Pequeno,39,27.0,"14,42","26,46","0,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202210,15/11/2022 05:40:45
273,LIVRI OPERADORA DE PLANO DE SAÚDE LTDA (422479),Médico Hospitalar,Pequeno,177,197.0,"0,00","0,00","0,00","0,00","0,00","0,00","0,00",NaN,NaN,NaN,NaN,NaN,202210,15/11/2022 05:40:45
311,PLAN SAÚDE LTDA (422771),Médico Hospitalar,Pequeno,177,197.0,"0,00","0,00","0,00","0,00","12,58","13,48","14,33","0,00","0,00",NaN,NaN,NaN,202210,15/11/2022 05:40:45
330,PRESERVE SAUDE ASSISTENCIA MEDICA LTDA (422959),Médico Hospitalar,Pequeno,177,197.0,"0,00","0,00","0,00","0,00","0,00","0,00",NaN,NaN,NaN,NaN,NaN,NaN,202210,15/11/2022 05:40:45
391,SOCIEDADE PORTUGUESA DE BENEFICENCIA (422762),Médico Hospitalar,Pequeno,35,17.0,"16,34","37,20","41,04","21,22","0,00","0,00","0,00",NaN,NaN,NaN,NaN,NaN,202210,15/11/2022 05:40:45

In [ ]:
def limpeza_dados(df):
    df.columns = (df.columns
                  .str.strip()
                  .str.upper()
                  .str.replace(' ', '_')
    )
                
    colunas_num = ['NOV/21', 'DEZ/21', 'JAN/22', 'FEV/22', 'MAR/22', 'ABR/22','MAI/22', 'JUN/22', 'JUL/22', 'AGO/22', 'SET/22', 'OUT/22' ]
    colunas_str = ['RAZÃO_SOCIAL_(REGISTRO_ANS)', 'COBERTURA', 'PORTE']

    for coluna in colunas_num:
        df[coluna] = df[coluna].str.replace(',', '.')
        df[coluna] = pd.to_numeric(df[coluna], errors='coerce')

    for coluna in colunas_str:
        df[coluna] = df[coluna].str.upper()
    
    df.drop_duplicates()

    return df

In [16]:
df = limpeza_dados(df)

In [17]:
df.head()

,RAZÃO_SOCIAL_(REGISTRO_ANS),COBERTURA,PORTE,CLASSIFICAÇÃO_NO_MÊS,CLASSIFICAÇÃO_NO_MÊS_ANTERIOR,OUT/22,SET/22,AGO/22,JUL/22,JUN/22,MAI/22,ABR/22,MAR/22,FEV/22,JAN/22,DEZ/21,NOV/21,COMPETÊNCIA,DATA_DE_ATUALIZAÇÃO
0,CAIXA DE ASSISTÊNCIA DO SETOR DE ENERGIA -EVI...,MÉDICO HOSPITALAR,PEQUENO,80,90.0,3.56,4.13,4.33,1.83,3.61,6.20,6.72,9.16,8.31,9.05,5.02,6.01,202210,15/11/2022 05:40:45
1,ABERTTA SAÚDE - ASSOCIAÇÃO BENEFICENTE DOS EMP...,MÉDICO HOSPITALAR,MÉDIO,206,187.0,0.20,0.41,0.41,0.20,0.00,0.00,0.00,0.21,0.21,0.21,0.21,0.41,202210,15/11/2022 05:40:45
2,ADVANCE PLANOS DE SAÚDE LTDA (335657),MÉDICO HOSPITALAR,PEQUENO,51,33.0,8.72,17.33,12.89,12.79,4.23,33.73,29.37,33.38,8.30,20.64,28.76,24.54,202210,15/11/2022 05:40:45
3,AGROS - INSTITUTO UFV DE SEGURIDADE SOCIAL (36...,MÉDICO HOSPITALAR,PEQUENO,177,197.0,0.00,0.00,0.00,0.00,0.66,0.66,0.66,0.00,0.00,0.66,1.32,3.28,202210,15/11/2022 05:40:45
4,ALCANCE SAÚDE EIRELI (416975),MÉDICO HOSPITALAR,PEQUENO,177,197.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2.24,2.25,6.78,4.54,4.56,202210,15/11/2022 05:40:45

In [21]:
df.isnull().sum()

RAZÃO_SOCIAL_(REGISTRO_ANS)       0
COBERTURA                         0
PORTE                             0
CLASSIFICAÇÃO_NO_MÊS              0
CLASSIFICAÇÃO_NO_MÊS_ANTERIOR     4
OUT/22                            0
SET/22                            4
AGO/22                            4
JUL/22                            6
JUN/22                            7
MAI/22                            8
ABR/22                           10
MAR/22                           12
FEV/22                           16
JAN/22                           18
DEZ/21                           19
NOV/21                           21
COMPETÊNCIA                       0
DATA_DE_ATUALIZAÇÃO               0
dtype: int64

In [29]:
df.groupby('RAZÃO_SOCIAL_(REGISTRO_ANS)')['CLASSIFICAÇÃO_NO_MÊS'].max().sort_values(ascending=False)

RAZÃO_SOCIAL_(REGISTRO_ANS)
PROASA - PROGRAMA ADVENTISTA DE  SAÚDE (310522)                       211
UNIMED PARÁ DE MINAS COOPERATIVA DE TRABALHO MÉDICO LTDA. (304344)    211
ASSOCIAÇÃO FUNDO DE PROTEÇÃO À SAÚDE (416584)                         211
ASSOCIAÇÃO SANTA CASA SAÚDE DE ARAÇATUBA (418803)                     211
SANTA CASA DE MISERICORDIA DE SAO JOAQUIM DA BARRA (345091)           211
                                                                     ...
DENTAL MASTER LTDA - EPP (413747)                                       1
HAPPYMED PLANO DE SAÚDE LTDA (422444)                                   1
IDEAL ODONTO ASSISTÊNCIA ODONTOLÓGICA LTDA. (414921)                    1
SMART DENTAL ODONTOLOGIA EIRELI - ME (420298)                           1
SUL AMÉRICA ODONTOLÓGICO S/A (417815)                                   1
Name: CLASSIFICAÇÃO_NO_MÊS, Length: 915, dtype: int64

In [35]:
df['DATA_DE_ATUALIZAÇÃO'] = pd.to_datetime(df['DATA_DE_ATUALIZAÇÃO'], dayfirst=True)

In [36]:
df.head()

,RAZÃO_SOCIAL_(REGISTRO_ANS),COBERTURA,PORTE,CLASSIFICAÇÃO_NO_MÊS,CLASSIFICAÇÃO_NO_MÊS_ANTERIOR,OUT/22,SET/22,AGO/22,JUL/22,JUN/22,MAI/22,ABR/22,MAR/22,FEV/22,JAN/22,DEZ/21,NOV/21,COMPETÊNCIA,DATA_DE_ATUALIZAÇÃO
0,CAIXA DE ASSISTÊNCIA DO SETOR DE ENERGIA -EVI...,MÉDICO HOSPITALAR,PEQUENO,80,90.0,3.56,4.13,4.33,1.83,3.61,6.20,6.72,9.16,8.31,9.05,5.02,6.01,202210,2022-11-15 05:40:45
1,ABERTTA SAÚDE - ASSOCIAÇÃO BENEFICENTE DOS EMP...,MÉDICO HOSPITALAR,MÉDIO,206,187.0,0.20,0.41,0.41,0.20,0.00,0.00,0.00,0.21,0.21,0.21,0.21,0.41,202210,2022-11-15 05:40:45
2,ADVANCE PLANOS DE SAÚDE LTDA (335657),MÉDICO HOSPITALAR,PEQUENO,51,33.0,8.72,17.33,12.89,12.79,4.23,33.73,29.37,33.38,8.30,20.64,28.76,24.54,202210,2022-11-15 05:40:45
3,AGROS - INSTITUTO UFV DE SEGURIDADE SOCIAL (36...,MÉDICO HOSPITALAR,PEQUENO,177,197.0,0.00,0.00,0.00,0.00,0.66,0.66,0.66,0.00,0.00,0.66,1.32,3.28,202210,2022-11-15 05:40:45
4,ALCANCE SAÚDE EIRELI (416975),MÉDICO HOSPITALAR,PEQUENO,177,197.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2.24,2.25,6.78,4.54,4.56,202210,2022-11-15 05:40:45

In [37]:
df['DATA'] = df['DATA_DE_ATUALIZAÇÃO'].dt.date
df['HORÁRIO'] = df['DATA_DE_ATUALIZAÇÃO'].dt.time

In [38]:
df.head()

,RAZÃO_SOCIAL_(REGISTRO_ANS),COBERTURA,PORTE,CLASSIFICAÇÃO_NO_MÊS,CLASSIFICAÇÃO_NO_MÊS_ANTERIOR,OUT/22,SET/22,AGO/22,JUL/22,JUN/22,...,ABR/22,MAR/22,FEV/22,JAN/22,DEZ/21,NOV/21,COMPETÊNCIA,DATA_DE_ATUALIZAÇÃO,DATA,HORÁRIO
0,CAIXA DE ASSISTÊNCIA DO SETOR DE ENERGIA -EVI...,MÉDICO HOSPITALAR,PEQUENO,80,90.0,3.56,4.13,4.33,1.83,3.61,...,6.72,9.16,8.31,9.05,5.02,6.01,202210,2022-11-15 05:40:45,2022-11-15,05:40:45
1,ABERTTA SAÚDE - ASSOCIAÇÃO BENEFICENTE DOS EMP...,MÉDICO HOSPITALAR,MÉDIO,206,187.0,0.20,0.41,0.41,0.20,0.00,...,0.00,0.21,0.21,0.21,0.21,0.41,202210,2022-11-15 05:40:45,2022-11-15,05:40:45
2,ADVANCE PLANOS DE SAÚDE LTDA (335657),MÉDICO HOSPITALAR,PEQUENO,51,33.0,8.72,17.33,12.89,12.79,4.23,...,29.37,33.38,8.30,20.64,28.76,24.54,202210,2022-11-15 05:40:45,2022-11-15,05:40:45
3,AGROS - INSTITUTO UFV DE SEGURIDADE SOCIAL (36...,MÉDICO HOSPITALAR,PEQUENO,177,197.0,0.00,0.00,0.00,0.00,0.66,...,0.66,0.00,0.00,0.66,1.32,3.28,202210,2022-11-15 05:40:45,2022-11-15,05:40:45
4,ALCANCE SAÚDE EIRELI (416975),MÉDICO HOSPITALAR,PEQUENO,177,197.0,0.00,0.00,0.00,0.00,0.00,...,0.00,2.24,2.25,6.78,4.54,4.56,202210,2022-11-15 05:40:45,2022-11-15,05:40:45

In [39]:
del df['DATA_DE_ATUALIZAÇÃO']

In [40]:
df.head()

,RAZÃO_SOCIAL_(REGISTRO_ANS),COBERTURA,PORTE,CLASSIFICAÇÃO_NO_MÊS,CLASSIFICAÇÃO_NO_MÊS_ANTERIOR,OUT/22,SET/22,AGO/22,JUL/22,JUN/22,MAI/22,ABR/22,MAR/22,FEV/22,JAN/22,DEZ/21,NOV/21,COMPETÊNCIA,DATA,HORÁRIO
0,CAIXA DE ASSISTÊNCIA DO SETOR DE ENERGIA -EVI...,MÉDICO HOSPITALAR,PEQUENO,80,90.0,3.56,4.13,4.33,1.83,3.61,6.20,6.72,9.16,8.31,9.05,5.02,6.01,202210,2022-11-15,05:40:45
1,ABERTTA SAÚDE - ASSOCIAÇÃO BENEFICENTE DOS EMP...,MÉDICO HOSPITALAR,MÉDIO,206,187.0,0.20,0.41,0.41,0.20,0.00,0.00,0.00,0.21,0.21,0.21,0.21,0.41,202210,2022-11-15,05:40:45
2,ADVANCE PLANOS DE SAÚDE LTDA (335657),MÉDICO HOSPITALAR,PEQUENO,51,33.0,8.72,17.33,12.89,12.79,4.23,33.73,29.37,33.38,8.30,20.64,28.76,24.54,202210,2022-11-15,05:40:45
3,AGROS - INSTITUTO UFV DE SEGURIDADE SOCIAL (36...,MÉDICO HOSPITALAR,PEQUENO,177,197.0,0.00,0.00,0.00,0.00,0.66,0.66,0.66,0.00,0.00,0.66,1.32,3.28,202210,2022-11-15,05:40:45
4,ALCANCE SAÚDE EIRELI (416975),MÉDICO HOSPITALAR,PEQUENO,177,197.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2.24,2.25,6.78,4.54,4.56,202210,2022-11-15,05:40:45

In [45]:
df['CLASSIFICAÇÃO_NO_MÊS'].mean()

np.float64(87.98469945355191)

In [60]:
def categorias(classificacao):
    condicao = [
        classificacao < 25,
        classificacao < 50,
        classificacao < 125,
        classificacao >= 125
    ]

    valores = [
        'RUIM',
        'MÉDIO',
        'BOM',
        'MUITO BOM'
    ]

    df['CATEGORIA_CLASSIFICAÇÃO_NO_MÊS'] = np.select(condicao, valores, default='MUITO RUIM')

In [61]:
categorias(df['CLASSIFICAÇÃO_NO_MÊS'])

In [62]:
df.head()

,RAZÃO_SOCIAL_(REGISTRO_ANS),COBERTURA,PORTE,CLASSIFICAÇÃO_NO_MÊS,CLASSIFICAÇÃO_NO_MÊS_ANTERIOR,OUT/22,SET/22,AGO/22,JUL/22,JUN/22,...,ABR/22,MAR/22,FEV/22,JAN/22,DEZ/21,NOV/21,COMPETÊNCIA,DATA,HORÁRIO,CATEGORIA_CLASSIFICAÇÃO_NO_MÊS
0,CAIXA DE ASSISTÊNCIA DO SETOR DE ENERGIA -EVI...,MÉDICO HOSPITALAR,PEQUENO,80,90.0,3.56,4.13,4.33,1.83,3.61,...,6.72,9.16,8.31,9.05,5.02,6.01,202210,2022-11-15,05:40:45,BOM
1,ABERTTA SAÚDE - ASSOCIAÇÃO BENEFICENTE DOS EMP...,MÉDICO HOSPITALAR,MÉDIO,206,187.0,0.20,0.41,0.41,0.20,0.00,...,0.00,0.21,0.21,0.21,0.21,0.41,202210,2022-11-15,05:40:45,MUITO BOM
2,ADVANCE PLANOS DE SAÚDE LTDA (335657),MÉDICO HOSPITALAR,PEQUENO,51,33.0,8.72,17.33,12.89,12.79,4.23,...,29.37,33.38,8.30,20.64,28.76,24.54,202210,2022-11-15,05:40:45,BOM
3,AGROS - INSTITUTO UFV DE SEGURIDADE SOCIAL (36...,MÉDICO HOSPITALAR,PEQUENO,177,197.0,0.00,0.00,0.00,0.00,0.66,...,0.66,0.00,0.00,0.66,1.32,3.28,202210,2022-11-15,05:40:45,MUITO BOM
4,ALCANCE SAÚDE EIRELI (416975),MÉDICO HOSPITALAR,PEQUENO,177,197.0,0.00,0.00,0.00,0.00,0.00,...,0.00,2.24,2.25,6.78,4.54,4.56,202210,2022-11-15,05:40:45,MUITO BOM

In [63]:
df['CATEGORIA_CLASSIFICAÇÃO_NO_MÊS'].value_counts()

CATEGORIA_CLASSIFICAÇÃO_NO_MÊS
MUITO BOM    342
RUIM         306
BOM          192
MÉDIO         75
Name: count, dtype: int64

In [ ]:
df.to_csv('./')

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 915 entries, 0 to 914
Data columns (total 21 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   RAZÃO_SOCIAL_(REGISTRO_ANS)     915 non-null    object
 1   COBERTURA                       915 non-null    object
 2   PORTE                           915 non-null    object
 3   CLASSIFICAÇÃO_NO_MÊS            915 non-null    int64
 4   CLASSIFICAÇÃO_NO_MÊS_ANTERIOR   911 non-null    float64
 5   OUT/22                          915 non-null    float64
 6   SET/22                          911 non-null    float64
 7   AGO/22                          911 non-null    float64
 8   JUL/22                          909 non-null    float64
 9   JUN/22                          908 non-null    float64
 10  MAI/22                          907 non-null    float64
 11  ABR/22                          905 non-null    float64
 12  MAR/22                          903 non-null    float64
 13  FEV/22                          899 non-null    float64
 14  JAN/22                          897 non-null    float64
 15  DEZ/21                          896 non-null    float64
 16  NOV/21                          894 non-null    float64
 17  COMPETÊNCIA                     915 non-null    int64
 18  DATA                            915 non-null    object
 19  HORÁRIO                         915 non-null    object
 20  CATEGORIA_CLASSIFICAÇÃO_NO_MÊS  915 non-null    object
dtypes: float64(13), int64(2), object(6)
memory usage: 150.2+ KB

In [65]:
df.duplicated().sum()

np.int64(0)

In [69]:
df['DATA_DA_ATUALIZAÇÃO'] = pd.to_datetime(df['DATA'].astype(str) + ' ' + df['HORÁRIO'].astype(str))

In [70]:
df.head()

,RAZÃO_SOCIAL_(REGISTRO_ANS),COBERTURA,PORTE,CLASSIFICAÇÃO_NO_MÊS,CLASSIFICAÇÃO_NO_MÊS_ANTERIOR,OUT/22,SET/22,AGO/22,JUL/22,JUN/22,...,MAR/22,FEV/22,JAN/22,DEZ/21,NOV/21,COMPETÊNCIA,DATA,HORÁRIO,CATEGORIA_CLASSIFICAÇÃO_NO_MÊS,DATA_DA_ATUALIZAÇÃO
0,CAIXA DE ASSISTÊNCIA DO SETOR DE ENERGIA -EVI...,MÉDICO HOSPITALAR,PEQUENO,80,90.0,3.56,4.13,4.33,1.83,3.61,...,9.16,8.31,9.05,5.02,6.01,202210,2022-11-15,05:40:45,BOM,2022-11-15 05:40:45
1,ABERTTA SAÚDE - ASSOCIAÇÃO BENEFICENTE DOS EMP...,MÉDICO HOSPITALAR,MÉDIO,206,187.0,0.20,0.41,0.41,0.20,0.00,...,0.21,0.21,0.21,0.21,0.41,202210,2022-11-15,05:40:45,MUITO BOM,2022-11-15 05:40:45
2,ADVANCE PLANOS DE SAÚDE LTDA (335657),MÉDICO HOSPITALAR,PEQUENO,51,33.0,8.72,17.33,12.89,12.79,4.23,...,33.38,8.30,20.64,28.76,24.54,202210,2022-11-15,05:40:45,BOM,2022-11-15 05:40:45
3,AGROS - INSTITUTO UFV DE SEGURIDADE SOCIAL (36...,MÉDICO HOSPITALAR,PEQUENO,177,197.0,0.00,0.00,0.00,0.00,0.66,...,0.00,0.00,0.66,1.32,3.28,202210,2022-11-15,05:40:45,MUITO BOM,2022-11-15 05:40:45
4,ALCANCE SAÚDE EIRELI (416975),MÉDICO HOSPITALAR,PEQUENO,177,197.0,0.00,0.00,0.00,0.00,0.00,...,2.24,2.25,6.78,4.54,4.56,202210,2022-11-15,05:40:45,MUITO BOM,2022-11-15 05:40:45

In [74]:
del df['HORÁRIO']

In [75]:
df.head()

,RAZÃO_SOCIAL_(REGISTRO_ANS),COBERTURA,PORTE,CLASSIFICAÇÃO_NO_MÊS,CLASSIFICAÇÃO_NO_MÊS_ANTERIOR,OUT/22,SET/22,AGO/22,JUL/22,JUN/22,MAI/22,ABR/22,MAR/22,FEV/22,JAN/22,DEZ/21,NOV/21,COMPETÊNCIA,CATEGORIA_CLASSIFICAÇÃO_NO_MÊS,DATA_DA_ATUALIZAÇÃO
0,CAIXA DE ASSISTÊNCIA DO SETOR DE ENERGIA -EVI...,MÉDICO HOSPITALAR,PEQUENO,80,90.0,3.56,4.13,4.33,1.83,3.61,6.20,6.72,9.16,8.31,9.05,5.02,6.01,202210,BOM,2022-11-15 05:40:45
1,ABERTTA SAÚDE - ASSOCIAÇÃO BENEFICENTE DOS EMP...,MÉDICO HOSPITALAR,MÉDIO,206,187.0,0.20,0.41,0.41,0.20,0.00,0.00,0.00,0.21,0.21,0.21,0.21,0.41,202210,MUITO BOM,2022-11-15 05:40:45
2,ADVANCE PLANOS DE SAÚDE LTDA (335657),MÉDICO HOSPITALAR,PEQUENO,51,33.0,8.72,17.33,12.89,12.79,4.23,33.73,29.37,33.38,8.30,20.64,28.76,24.54,202210,BOM,2022-11-15 05:40:45
3,AGROS - INSTITUTO UFV DE SEGURIDADE SOCIAL (36...,MÉDICO HOSPITALAR,PEQUENO,177,197.0,0.00,0.00,0.00,0.00,0.66,0.66,0.66,0.00,0.00,0.66,1.32,3.28,202210,MUITO BOM,2022-11-15 05:40:45
4,ALCANCE SAÚDE EIRELI (416975),MÉDICO HOSPITALAR,PEQUENO,177,197.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2.24,2.25,6.78,4.54,4.56,202210,MUITO BOM,2022-11-15 05:40:45

In [76]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 915 entries, 0 to 914
Data columns (total 20 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   RAZÃO_SOCIAL_(REGISTRO_ANS)     915 non-null    object
 1   COBERTURA                       915 non-null    object
 2   PORTE                           915 non-null    object
 3   CLASSIFICAÇÃO_NO_MÊS            915 non-null    int64
 4   CLASSIFICAÇÃO_NO_MÊS_ANTERIOR   911 non-null    float64
 5   OUT/22                          915 non-null    float64
 6   SET/22                          911 non-null    float64
 7   AGO/22                          911 non-null    float64
 8   JUL/22                          909 non-null    float64
 9   JUN/22                          908 non-null    float64
 10  MAI/22                          907 non-null    float64
 11  ABR/22                          905 non-null    float64
 12  MAR/22                          903 non-null    float64
 13  FEV/22                          899 non-null    float64
 14  JAN/22                          897 non-null    float64
 15  DEZ/21                          896 non-null    float64
 16  NOV/21                          894 non-null    float64
 17  COMPETÊNCIA                     915 non-null    int64
 18  CATEGORIA_CLASSIFICAÇÃO_NO_MÊS  915 non-null    object
 19  DATA_DA_ATUALIZAÇÃO             915 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(13), int64(2), object(4)
memory usage: 143.1+ KB

In [77]:
df.to_csv('./datasets/igr-processado.csv')

In [4]:
df_pro = pd.read_csv('./datasets/igr-processado.csv')

In [80]:
del df_pro['Unnamed: 0']

In [81]:
df_pro.head()

,RAZÃO_SOCIAL_(REGISTRO_ANS),COBERTURA,PORTE,CLASSIFICAÇÃO_NO_MÊS,CLASSIFICAÇÃO_NO_MÊS_ANTERIOR,OUT/22,SET/22,AGO/22,JUL/22,JUN/22,MAI/22,ABR/22,MAR/22,FEV/22,JAN/22,DEZ/21,NOV/21,COMPETÊNCIA,CATEGORIA_CLASSIFICAÇÃO_NO_MÊS,DATA_DA_ATUALIZAÇÃO
0,CAIXA DE ASSISTÊNCIA DO SETOR DE ENERGIA -EVI...,MÉDICO HOSPITALAR,PEQUENO,80,90.0,3.56,4.13,4.33,1.83,3.61,6.20,6.72,9.16,8.31,9.05,5.02,6.01,202210,BOM,2022-11-15 05:40:45
1,ABERTTA SAÚDE - ASSOCIAÇÃO BENEFICENTE DOS EMP...,MÉDICO HOSPITALAR,MÉDIO,206,187.0,0.20,0.41,0.41,0.20,0.00,0.00,0.00,0.21,0.21,0.21,0.21,0.41,202210,MUITO BOM,2022-11-15 05:40:45
2,ADVANCE PLANOS DE SAÚDE LTDA (335657),MÉDICO HOSPITALAR,PEQUENO,51,33.0,8.72,17.33,12.89,12.79,4.23,33.73,29.37,33.38,8.30,20.64,28.76,24.54,202210,BOM,2022-11-15 05:40:45
3,AGROS - INSTITUTO UFV DE SEGURIDADE SOCIAL (36...,MÉDICO HOSPITALAR,PEQUENO,177,197.0,0.00,0.00,0.00,0.00,0.66,0.66,0.66,0.00,0.00,0.66,1.32,3.28,202210,MUITO BOM,2022-11-15 05:40:45
4,ALCANCE SAÚDE EIRELI (416975),MÉDICO HOSPITALAR,PEQUENO,177,197.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2.24,2.25,6.78,4.54,4.56,202210,MUITO BOM,2022-11-15 05:40:45

In [6]:
import sqlite3

con = sqlite3.connect('./datasets/dados_processados.db')

df_pro.to_sql(
    name='dados_processados',
    con=con,
    if_exists='replace',
    index=False
)

con.close()