In [2]:
import pandas as pd

In [54]:
df = pd.read_csv('./datasets/distribuidoras-consumidores-livres.csv', encoding='utf-16', sep=';')

In [55]:
df.head()

,Ano,Mês,TipoMercado,RegiãoAgregada,Preço em Reais por MMBtu,Volume em mil metros cúbicos/dia
0,2019,9,Térmico,Norte-Nordeste,"18,9",15908
1,2019,9,Não Térmico,Norte-Nordeste,"49,3",7159
2,2019,9,Não Térmico,Sudeste,"48,8",26028
3,2019,9,Térmico,Sudeste-Sul-Centro-Oeste,"18,8",10520
4,2019,9,Não Térmico,Sul-Centro-Oeste,"40,1",5726

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 410 entries, 0 to 409
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Ano                               410 non-null    int64
 1   Mês                               410 non-null    int64
 2   TipoMercado                       410 non-null    object
 3   RegiãoAgregada                    410 non-null    object
 4   Preço em Reais por MMBtu          338 non-null    object
 5   Volume em mil metros cúbicos/dia  410 non-null    int64
dtypes: int64(3), object(3)
memory usage: 19.3+ KB

In [72]:
def limpeza_dados(df):
    df.columns = (df.columns
                  .str.strip()
                  .str.upper()
                  .str.replace(' ', '_')
    )
    df['PREÇO_EM_REAIS_POR_MMBTU'] = df['PREÇO_EM_REAIS_POR_MMBTU'].str.replace(',', '.')
    df['PREÇO_EM_REAIS_POR_MMBTU'] = pd.to_numeric(df['PREÇO_EM_REAIS_POR_MMBTU'], errors='coerce')

    df = df.dropna()

    return df

In [ ]:
limpeza_dados(df)

In [61]:
df = df.rename(columns = {
    'TIPOMERCADO' : 'TIPO_MERCADO',
    'REGIÃOAGREGADA': 'REGIÃO_AGREGADA'


})

In [62]:
df.head()

,ANO,MÊS,TIPO_MERCADO,REGIÃO_AGREGADA,PREÇO_EM_REAIS_POR_MMBTU,VOLUME_EM_MIL_METROS_CÚBICOS/DIA
0,2019,9,Térmico,Norte-Nordeste,18.9,15908
1,2019,9,Não Térmico,Norte-Nordeste,49.3,7159
2,2019,9,Não Térmico,Sudeste,48.8,26028
3,2019,9,Térmico,Sudeste-Sul-Centro-Oeste,18.8,10520
4,2019,9,Não Térmico,Sul-Centro-Oeste,40.1,5726

In [63]:
valores_str = ['TIPO_MERCADO', 'REGIÃO_AGREGADA']

for coluna in valores_str:
    df[coluna] = df[coluna].str.upper()

In [64]:
df

,ANO,MÊS,TIPO_MERCADO,REGIÃO_AGREGADA,PREÇO_EM_REAIS_POR_MMBTU,VOLUME_EM_MIL_METROS_CÚBICOS/DIA
0,2019,9,TÉRMICO,NORTE-NORDESTE,18.9,15908
1,2019,9,NÃO TÉRMICO,NORTE-NORDESTE,49.3,7159
2,2019,9,NÃO TÉRMICO,SUDESTE,48.8,26028
3,2019,9,TÉRMICO,SUDESTE-SUL-CENTRO-OESTE,18.8,10520
4,2019,9,NÃO TÉRMICO,SUL-CENTRO-OESTE,40.1,5726
...,...,...,...,...,...,...
405,2026,6,NÃO TÉRMICO,NORTE-NORDESTE,63.9,11464
406,2026,6,NÃO TÉRMICO,SUL-CENTRO-OESTE,70.7,6357
407,2026,6,NÃO TÉRMICO,SUDESTE,74.3,23407
408,2026,6,TÉRMICO,NORTE-NORDESTE,28.4,12000
409,2026,6,TÉRMICO,SUDESTE-SUL-CENTRO-OESTE,53.6,2590

In [ ]:
df.isnull().sum()

ANO                                  0
MÊS                                  0
TIPO_MERCADO                         0
REGIÃO_AGREGADA                      0
PREÇO_EM_REAIS_POR_MMBTU            72
VOLUME_EM_MIL_METROS_CÚBICOS/DIA     0
dtype: int64

In [71]:
df[df.isnull().any(axis=1)]

,ANO,MÊS,TIPO_MERCADO,REGIÃO_AGREGADA,PREÇO_EM_REAIS_POR_MMBTU,VOLUME_EM_MIL_METROS_CÚBICOS/DIA
151,2022,3,TÉRMICO,NORTE-NORDESTE,NaN,3831
164,2022,5,TÉRMICO,SUDESTE-SUL-CENTRO-OESTE,NaN,537
169,2022,6,TÉRMICO,SUDESTE-SUL-CENTRO-OESTE,NaN,154
174,2022,7,TÉRMICO,SUDESTE-SUL-CENTRO-OESTE,NaN,350
183,2022,9,TÉRMICO,SUDESTE-SUL-CENTRO-OESTE,NaN,864
...,...,...,...,...,...,...
354,2025,7,TÉRMICO,NORTE-NORDESTE,NaN,10952
358,2025,8,TÉRMICO,NORTE-NORDESTE,NaN,13165
359,2025,8,TÉRMICO,SUDESTE-SUL-CENTRO-OESTE,NaN,3395
360,2025,9,TÉRMICO,NORTE-NORDESTE,NaN,12933
364,2025,9,TÉRMICO,SUDESTE-SUL-CENTRO-OESTE,NaN,4396

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 410 entries, 0 to 409
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   ANO                               410 non-null    int64
 1   MÊS                               410 non-null    int64
 2   TIPO_MERCADO                      410 non-null    object
 3   REGIÃO_AGREGADA                   410 non-null    object
 4   PREÇO_EM_REAIS_POR_MMBTU          338 non-null    float64
 5   VOLUME_EM_MIL_METROS_CÚBICOS/DIA  410 non-null    int64
dtypes: float64(1), int64(3), object(2)
memory usage: 19.3+ KB

In [75]:
df.shape

(410, 6)

In [76]:
df = df.dropna()

In [77]:
df.shape

(338, 6)

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 338 entries, 0 to 409
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   ANO                               338 non-null    int64
 1   MÊS                               338 non-null    int64
 2   TIPO_MERCADO                      338 non-null    object
 3   REGIÃO_AGREGADA                   338 non-null    object
 4   PREÇO_EM_REAIS_POR_MMBTU          338 non-null    float64
 5   VOLUME_EM_MIL_METROS_CÚBICOS/DIA  338 non-null    int64
dtypes: float64(1), int64(3), object(2)
memory usage: 18.5+ KB

In [79]:
df.head()

,ANO,MÊS,TIPO_MERCADO,REGIÃO_AGREGADA,PREÇO_EM_REAIS_POR_MMBTU,VOLUME_EM_MIL_METROS_CÚBICOS/DIA
0,2019,9,TÉRMICO,NORTE-NORDESTE,18.9,15908
1,2019,9,NÃO TÉRMICO,NORTE-NORDESTE,49.3,7159
2,2019,9,NÃO TÉRMICO,SUDESTE,48.8,26028
3,2019,9,TÉRMICO,SUDESTE-SUL-CENTRO-OESTE,18.8,10520
4,2019,9,NÃO TÉRMICO,SUL-CENTRO-OESTE,40.1,5726

In [ ]:
df.groupby(['REGIÃO_AGREGADA', 'TIPO_MERCADO'])['PREÇO_EM_REAIS_POR_MMBTU'].mean().sort_values(ascending= False)

REGIÃO_AGREGADA           TIPO_MERCADO
SUL-CENTRO-OESTE          NÃO TÉRMICO     68.109756
SUDESTE                   NÃO TÉRMICO     67.652439
NORTE-NORDESTE            NÃO TÉRMICO     60.892683
SUDESTE-SUL-CENTRO-OESTE  TÉRMICO         40.119048
NORTE-NORDESTE            TÉRMICO         26.626000
Name: PREÇO_EM_REAIS_POR_MMBTU, dtype: float64

In [88]:
df.groupby('TIPO_MERCADO')['VOLUME_EM_MIL_METROS_CÚBICOS/DIA'].mean()

TIPO_MERCADO
NÃO TÉRMICO    12983.138211
TÉRMICO         8557.347826
Name: VOLUME_EM_MIL_METROS_CÚBICOS/DIA, dtype: float64